#!/bin/bash

set -e  # stop on first error

# Resolve project root dynamically
BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BOMBYX="$BASE/build/bin/bombyx-cc"

echo "Running all Bombyx tests..."

echo ">> nqueens"
$BOMBYX "$BASE/tests/im/nqueens.c" "$BASE/tests/ex/nqueens.cpp"
echo ">> fib"
$BOMBYX "$BASE/tests/im/fib.c" "$BASE/tests/ex/fib.cpp"
echo ">> listing_7"
$BOMBYX "$BASE/tests/im/listing_7.cpp" "$BASE/tests/ex/listing_7.cpp"
echo ">> listing_8"
$BOMBYX "$BASE/tests/im/listing_8.cpp" "$BASE/tests/ex/listing_8.cpp"
echo ">> listing_9"
$BOMBYX "$BASE/tests/im/listing_9.cpp" "$BASE/tests/ex/listing_9.cpp"
echo ">> listing_10"
$BOMBYX "$BASE/tests/im/listing_10.cpp" "$BASE/tests/ex/listing_10.cpp"
echo ">> listing_11"
$BOMBYX "$BASE/tests/im/listing_11.cpp" "$BASE/tests/ex/listing_11.cpp"
echo ">> listing_13"
$BOMBYX "$BASE/tests/im/listing_13.cpp" "$BASE/tests/ex/listing_13.cpp"
echo ">> test0"
$BOMBYX "$BASE/tests/im/test_0.cpp" "$BASE/tests/ex/test_0.cpp"
echo ">> test1"
$BOMBYX "$BASE/tests/im/test_1.cpp" "$BASE/tests/ex/test_1.cpp"
echo ">> test2"
$BOMBYX "$BASE/tests/im/test_2.cpp" "$BASE/tests/ex/test_2.cpp"
echo ">> test3"
$BOMBYX "$BASE/tests/im/test_3.cpp" "$BASE/tests/ex/test_3.cpp"
echo ">> test4"
$BOMBYX "$BASE/tests/im/test_4.cpp" "$BASE/tests/ex/test_4.cpp"
echo ">> test5"
$BOMBYX "$BASE/tests/im/test_5.cpp" "$BASE/tests/ex/test_5.cpp"
echo ">> test6"
$BOMBYX "$BASE/tests/im/test_6.cpp" "$BASE/tests/ex/test_6.cpp"
echo ">> test7"
$BOMBYX "$BASE/tests/im/test_7.cpp" "$BASE/tests/ex/test_7.cpp"
echo ">> test8"
$BOMBYX "$BASE/tests/im/test_8.cpp" "$BASE/tests/ex/test_8.cpp"
echo ">> Pagerank"
$BOMBYX "$BASE/Bombyx_OpenCilk_Examples/pageRank/main.cpp" \
        "$BASE/Bombyx_OpenCilk_Examples/pageRank/output/main.cpp"
echo ">> Randomwalk"
$BOMBYX "$BASE/Bombyx_OpenCilk_Examples/randomWalk/main.cpp" \
        "$BASE/Bombyx_OpenCilk_Examples/randomWalk/output/main.cpp"
echo ">> TriangleCount"
$BOMBYX "$BASE/Bombyx_OpenCilk_Examples/triangleCount/main.cpp" \
        "$BASE/Bombyx_OpenCilk_Examples/triangleCount/output/main.cpp"
echo ">> BarnesHut"
$BOMBYX "$BASE/Bombyx_OpenCilk_Examples/barnes-hut/main.cpp" \
        "$BASE/Bombyx_OpenCilk_Examples/barnes-hut//output/main.cpp"

echo ">> nqueens"
./build/bin/bombyx-cc "/Users/ranaelgahawy/Desktop/ResearchScholar/bombyx/tests/cilk5/im/nqueens.c" "/Users/ranaelgahawy/Desktop/ResearchScholar/bombyx/tests/cilk5/ex/nqueens.cpp"
echo ">> fib"
./build/bin/bombyx-cc "/Users/ranaelgahawy/Desktop/ResearchScholar/bombyx/tests/cilk5/im/fib.cpp" "/Users/ranaelgahawy/Desktop/ResearchScholar/bombyx/tests/cilk5/ex/fib.cpp" 
echo ">> cilksort"
./build/bin/bombyx-cc "/Users/ranaelgahawy/Desktop/ResearchScholar/bombyx/tests/cilk5/im/cilksort.cpp" "/Users/ranaelgahawy/Desktop/ResearchScholar/bombyx/tests/cilk5/ex/cilksort.cpp"
echo ">> qsort"
./build/bin/bombyx-cc "/Users/ranaelgahawy/Desktop/ResearchScholar/bombyx/tests/cilk5/im/qsort.cpp" "/Users/ranaelgahawy/Desktop/ResearchScholar/bombyx/tests/cilk5/ex/qsort.cpp"
echo ">> matmul"
./build/bin/bombyx-cc "/Users/ranaelgahawy/Desktop/ResearchScholar/bombyx/tests/cilk5/im/matmul.c" "/Users/ranaelgahawy/Desktop/ResearchScholar/bombyx/tests/cilk5/ex/matmul.cpp" 
echo ">> rectmul"
./build/bin/bombyx-cc "/Users/ranaelgahawy/Desktop/ResearchScholar/bombyx/tests/cilk5/im/rectmul.c" "/Users/ranaelgahawy/Desktop/ResearchScholar/bombyx/tests/cilk5/ex/rectmul.cpp"
echo "✅ Done!"
