// ===========================================================================
// Generated by bombyx-cc — #pragma BOMBYX OVERLAP Verilog wrapper
// Application : pageRank_overlap
//
// In-order streaming continuation delivery. The reentry PE pushes each
// iteration's continuation state onto STATE_FIFO and issues 1 memory
// read(s); the single in-order memReader reply channel is gathered 1 at a
// time and merged with the head of STATE_FIFO to drive the continuation PE.
//
// The loop body has 2 dependence levels of loads, so the chain is
// applyFn_reentry1 -> applyFn_reentry1_cont0 -> applyFn_reentry1_cont1, each stage issuing its own round of reads.
// Every round is an independent in-order reply channel with its own
// memReader, STATE_FIFO and merge unit; no arbitration or reply tagging is
// needed, and rounds whose element widths differ are served naturally.
//
// PE AXI-Stream ports follow the Vitis HLS convention: for an `axis` port
// `p`, the RTL exposes p_TDATA / p_TVALID / p_TREADY, plus ap_clk / ap_rst_n.
//
// External interface (everything not internal to the collapsed tasks):
//   * taskIn_*  — root task closure in (== root PE's taskIn)
//   * argOut_*  — loop completion out (== exit PE's argOut)
//   * m_axi_gmem_shared_* — ONE AXI4 memory master serving every read site
//     (ARID = site index), via the shared context-cached reader below
//   * m_axi_gmem_<pe>_* — one AXI4 memory master per remaining
//     memory-accessing PE (inline loads/stores), passed straight through
//     (Vitis default bundle name `gmem`). The per-PE s_axi_control offset
//     slave is tied idle (offset 0).
// ===========================================================================

module applyFn_overlap_wrapper_fifo #(
  parameter WIDTH = 32,
  parameter DEPTH = 512
) (
  input                  clk,
  input                  rst_n,
  input  [WIDTH-1:0]     in_data,
  input                  in_valid,
  output                 in_ready,
  output [WIDTH-1:0]     out_data,
  output                 out_valid,
  input                  out_ready
);
  localparam AW = $clog2(DEPTH); // DEPTH must be a power of two
  (* ram_style = "block" *)
  reg [WIDTH-1:0] mem [0:DEPTH-1];
  reg [AW:0] wptr, rptr;
  wire ram_empty = (wptr == rptr);
  wire full      = (wptr[AW-1:0] == rptr[AW-1:0]) && (wptr[AW] != rptr[AW]);
  assign in_ready = !full;
  wire push = in_valid && in_ready;

  // Output register: holds the head so the RAM's registered read is hidden.
  reg [WIDTH-1:0] outreg;
  reg             outreg_v;
  // Refill whenever the array has data and the output register is free.
  // Gating on !ram_empty also guarantees the read address never equals a
  // write address in the same cycle, so there is no read/write collision.
  wire pop = !ram_empty && (!outreg_v || out_ready);
  assign out_valid = outreg_v;
  assign out_data  = outreg;

  // Storage: no reset, so this infers a block RAM cleanly.
  always @(posedge clk) begin
    if (push) mem[wptr[AW-1:0]] <= in_data;
    if (pop)  outreg <= mem[rptr[AW-1:0]];
  end

  always @(posedge clk) begin
    if (!rst_n) begin
      wptr <= 0; rptr <= 0; outreg_v <= 1'b0;
    end else begin
      if (push) wptr <= wptr + 1'b1;
      if (pop)  rptr <= rptr + 1'b1;
      if (pop)            outreg_v <= 1'b1;
      else if (out_ready) outreg_v <= 1'b0;
    end
  end
endmodule

module applyFn_overlap_wrapper_arb2 #(parameter WIDTH = 32) (
  input               clk,
  input               rst_n,
  input  [WIDTH-1:0]  a_data,  input a_valid,  output a_ready,
  input  [WIDTH-1:0]  b_data,  input b_valid,  output b_ready,
  output [WIDTH-1:0]  o_data,  output o_valid, input  o_ready
);
  reg sel; // 0: prefer a, 1: prefer b
  wire pick_a = a_valid && (!b_valid || sel == 1'b0);
  assign o_valid = a_valid || b_valid;
  assign o_data  = pick_a ? a_data : b_data;
  assign a_ready = pick_a && o_ready;
  assign b_ready = !pick_a && o_valid && o_ready;
  always @(posedge clk) if (!rst_n) sel <= 0;
    else if (o_valid && o_ready) sel <= pick_a ? 1'b1 : 1'b0;
endmodule

// ===========================================================================
// applyFn_overlap_wrapper_memreader_cached — shared-port mem reader with a per-context line cache.
//
// Same shared-master idea as bombyx_mem_reader_shared (N read sites, one AXI
// master, ARID selects the stream), plus a private cache line per resident
// context in front of each stream.
//
// The context is allocated by the wrapper's admission control (a free queue of
// IDs replacing the in-flight counter), held for the whole residency of a merge
// loop, and returned at exit. It therefore identifies the loop, is dense
// (0..NUM_CTX-1), and carries no task data. That makes cache conflicts
// impossible by construction: a loop owns one entry, evicts only itself, and
// only when it advances past the line.
//
// Ordering — the reason for the completion queue
// ----------------------------------------------
// The wrapper's merge unit pairs the k-th reply of a stream with the k-th entry
// of that stream's state FIFO. A cache hit that returned immediately while an
// older miss was still outstanding would reorder replies and silently corrupt
// results. So every request — hit or miss — takes a slot in a per-stream
// in-order completion queue; a hit fills its slot at once, a miss when its R
// beat lands, and only the head is ever emitted.
//
// Misses of one stream all ride that stream's own ARID, so they return in
// order; a FIFO of slot indices therefore routes each R beat to the right slot
// with no searching.
//
// The bus is one line wide (256 bits), so a fill is a single beat and matches
// the RAMA/HBM width. A 32-bit element is taken from the line by byte offset.
// ===========================================================================

module applyFn_overlap_wrapper_mrc_fifo #(
  parameter WIDTH = 64,
  parameter DEPTH = 64
) (
  input                  clk,
  input                  rst_n,
  input  [WIDTH-1:0]     in_data,
  input                  in_valid,
  output                 in_ready,
  output [WIDTH-1:0]     out_data,
  output                 out_valid,
  input                  out_ready
);
  localparam AW = $clog2(DEPTH);
  reg [WIDTH-1:0] mem [0:DEPTH-1];
  reg [AW:0] wptr, rptr;
  wire empty = (wptr == rptr);
  wire full  = (wptr[AW-1:0] == rptr[AW-1:0]) && (wptr[AW] != rptr[AW]);
  assign in_ready  = !full;
  assign out_valid = !empty;
  assign out_data  = mem[rptr[AW-1:0]];
  always @(posedge clk) if (in_valid && in_ready) mem[wptr[AW-1:0]] <= in_data;
  always @(posedge clk) begin
    if (!rst_n) begin wptr <= 0; rptr <= 0; end
    else begin
      if (in_valid  && in_ready)  wptr <= wptr + 1'b1;
      if (out_valid && out_ready) rptr <= rptr + 1'b1;
    end
  end
endmodule


// ===========================================================================
// applyFn_overlap_wrapper_mrc_skid — two-entry skid buffer, registered in BOTH directions.
//
// i_ready is a flop output (~skid_v), not a function of o_ready, and o_valid is
// a flop. So neither the forward valid/data path nor the backward ready path
// carries combinational logic through the buffer.
//
// This is what breaks the handshake chains that dominated timing: the memory
// reader's taskIn_TREADY used to be
//
//     taskIn_TREADY[g] = rq_ready = !rq_v || hit_go[g] || ar_mine
//
// i.e. one stream's ready depended combinationally on every stream's CQ
// pointers and credit counters (via the shared AR arbiter) and then drove a
// 1024-bit register slice's clock enable in the upstream HLS PE -- measured at
// 12-13 logic levels and 4.4-4.8 ns, against a 3.333 ns budget.
//
// Costs one cycle of latency per interface; sustains one transfer per cycle,
// so no throughput is lost.
// ===========================================================================
module applyFn_overlap_wrapper_mrc_skid #(
  parameter WIDTH = 32
) (
  input                  clk,
  input                  rst_n,
  input  [WIDTH-1:0]     i_data,
  input                  i_valid,
  output                 i_ready,
  output [WIDTH-1:0]     o_data,
  output                 o_valid,
  input                  o_ready
);
  reg [WIDTH-1:0] data_r, skid_d;
  reg             valid_r, skid_v;

  assign i_ready = ~skid_v;   // flop output: no path back from o_ready
  assign o_valid = valid_r;   // flop output
  assign o_data  = data_r;

  wire i_fire = i_valid & i_ready;
  wire o_fire = valid_r & o_ready;

  always @(posedge clk) begin
    if (!rst_n) begin
      valid_r <= 1'b0;
      skid_v  <= 1'b0;
    end else if (skid_v) begin
      // holding an overflow beat; i_ready is low so nothing new arrives
      if (o_fire) begin
        data_r  <= skid_d;
        valid_r <= 1'b1;
        skid_v  <= 1'b0;
      end
    end else begin
      if (i_fire && valid_r && !o_fire) begin
        skid_d <= i_data;      // output busy and not draining -> skid
        skid_v <= 1'b1;
      end else if (i_fire) begin
        data_r  <= i_data;     // output free or draining this cycle
        valid_r <= 1'b1;
      end else if (o_fire) begin
        valid_r <= 1'b0;
      end
    end
  end
endmodule


module applyFn_overlap_wrapper_memreader_cached #(
  parameter N               = 5,
  parameter TASK_W          = 256,
  parameter ARG_W           = 256,
  parameter ADDR_W          = 64,
  parameter BUS_W           = 256,  // one line per beat
  parameter ID_W            = 3,
  parameter NUM_CTX         = 64,   // == wrapper's MAX_INFLIGHT_l1
  parameter CTX_W           = 6,
  parameter [8*N-1:0] ELEM_LOG2_VEC = {8'd2, 8'd2, 8'd3, 8'd3, 8'd2},
  parameter [8*N-1:0] ELEM_W_VEC    = {8'd32, 8'd32, 8'd64, 8'd64, 8'd32},
  parameter [8*N-1:0] IDX_W_VEC     = {8'd62, 8'd62, 8'd61, 8'd61, 8'd62},
  // per-stream cache enable: only the merge-loop sites are worth lines
  parameter [N-1:0]   CACHE_EN      = 5'b11000,
  parameter CONT_LSB        = 0,
  parameter CONT_W          = 64,
  parameter BASE_LSB        = 64,
  parameter IDX_LSB         = 128,
  parameter PKT_ADDR_LSB    = 0,
  parameter PKT_DATA_LSB    = 64,
  parameter OUTSTANDING     = 64,   // AXI credits per stream
  parameter CQ_DEPTH        = 128   // completion-queue slots per stream
) (
  input                       ap_clk,
  input                       ap_rst_n,

  input  [N*TASK_W-1:0]       taskIn_TDATA,
  input  [N-1:0]              taskIn_TVALID,
  output [N-1:0]              taskIn_TREADY,
  // context that owns each request, valid with taskIn
  input  [N*CTX_W-1:0]        taskIn_CTX,

  output [N*64-1:0]           argOut_TDATA,
  output [N-1:0]              argOut_TVALID,
  input  [N-1:0]              argOut_TREADY,

  output [N*ARG_W-1:0]        argDataOut_TDATA,
  output [N-1:0]              argDataOut_TVALID,
  input  [N-1:0]              argDataOut_TREADY,

  output                      m_axi_gmem_AWVALID,
  input                       m_axi_gmem_AWREADY,
  output [ADDR_W-1:0]         m_axi_gmem_AWADDR,
  output [ID_W-1:0]           m_axi_gmem_AWID,
  output [7:0]                m_axi_gmem_AWLEN,
  output [2:0]                m_axi_gmem_AWSIZE,
  output [1:0]                m_axi_gmem_AWBURST,
  output [1:0]                m_axi_gmem_AWLOCK,
  output [3:0]                m_axi_gmem_AWCACHE,
  output [2:0]                m_axi_gmem_AWPROT,
  output [3:0]                m_axi_gmem_AWQOS,
  output [3:0]                m_axi_gmem_AWREGION,
  output                      m_axi_gmem_AWUSER,
  output                      m_axi_gmem_WVALID,
  input                       m_axi_gmem_WREADY,
  output [BUS_W-1:0]          m_axi_gmem_WDATA,
  output [(BUS_W/8)-1:0]      m_axi_gmem_WSTRB,
  output                      m_axi_gmem_WLAST,
  output [ID_W-1:0]           m_axi_gmem_WID,
  output                      m_axi_gmem_WUSER,
  output                      m_axi_gmem_ARVALID,
  input                       m_axi_gmem_ARREADY,
  output [ADDR_W-1:0]         m_axi_gmem_ARADDR,
  output [ID_W-1:0]           m_axi_gmem_ARID,
  output [7:0]                m_axi_gmem_ARLEN,
  output [2:0]                m_axi_gmem_ARSIZE,
  output [1:0]                m_axi_gmem_ARBURST,
  output [1:0]                m_axi_gmem_ARLOCK,
  output [3:0]                m_axi_gmem_ARCACHE,
  output [2:0]                m_axi_gmem_ARPROT,
  output [3:0]                m_axi_gmem_ARQOS,
  output [3:0]                m_axi_gmem_ARREGION,
  output                      m_axi_gmem_ARUSER,
  input                       m_axi_gmem_RVALID,
  output                      m_axi_gmem_RREADY,
  input  [BUS_W-1:0]          m_axi_gmem_RDATA,
  input                       m_axi_gmem_RLAST,
  input  [ID_W-1:0]           m_axi_gmem_RID,
  input                       m_axi_gmem_RUSER,
  input  [1:0]                m_axi_gmem_RRESP,
  input                       m_axi_gmem_BVALID,
  output                      m_axi_gmem_BREADY,
  input  [1:0]                m_axi_gmem_BRESP,
  input  [ID_W-1:0]           m_axi_gmem_BID,
  input                       m_axi_gmem_BUSER,

  output [31:0]               dbg_cache_hits,
  output [31:0]               dbg_cache_misses
);

  localparam SEL_W    = (N > 1) ? $clog2(N) : 1;
  localparam LINE_LOG2 = $clog2(BUS_W/8);      // 5 for a 256-bit line
  localparam LANE_W   = LINE_LOG2;
  localparam TAG_W    = ADDR_W - LINE_LOG2;
  localparam CQ_AW    = $clog2(CQ_DEPTH);
  localparam CW       = $clog2(OUTSTANDING+1);

  // ---- input skid: decouple taskIn_TREADY from the arbiter ----------------
  // Everything downstream works off q_* instead of the ports, so the only thing
  // the upstream PE sees on its ready pin is this buffer's flop.
  wire [TASK_W-1:0] q_task  [0:N-1];
  wire [CTX_W-1:0]  q_ctx   [0:N-1];
  wire [N-1:0]      q_valid;
  wire [N-1:0]      q_ready;

  // ---- per-stream request decode -----------------------------------------
  wire [ADDR_W-1:0] s_addr [0:N-1];
  wire [CONT_W-1:0] s_cont [0:N-1];
  wire [CTX_W-1:0]  s_ctx  [0:N-1];

  genvar g;
  generate
    for (g = 0; g < N; g = g + 1) begin : gen_dec
      localparam integer EL2 = ELEM_LOG2_VEC[8*g +: 8];
      localparam integer IXW = IDX_W_VEC[8*g +: 8];

      applyFn_overlap_wrapper_mrc_skid #(.WIDTH(TASK_W + CTX_W)) u_in_skid (
        .clk(ap_clk), .rst_n(ap_rst_n),
        .i_data({taskIn_CTX[g*CTX_W +: CTX_W], taskIn_TDATA[g*TASK_W +: TASK_W]}),
        .i_valid(taskIn_TVALID[g]), .i_ready(taskIn_TREADY[g]),
        .o_data({q_ctx[g], q_task[g]}),
        .o_valid(q_valid[g]), .o_ready(q_ready[g])
      );

      wire [TASK_W-1:0] t = q_task[g];
      wire [ADDR_W-1:0] base = t[BASE_LSB +: ADDR_W];
      wire [IXW-1:0]    idx  = t[IDX_LSB  +: IXW];
      assign s_addr[g] = base + ({{(ADDR_W-IXW){1'b0}}, idx} << EL2);
      assign s_cont[g] = t[CONT_LSB +: CONT_W];
      assign s_ctx[g]  = q_ctx[g];
    end
  endgenerate

  // ---- per-stream state ---------------------------------------------------
  wire [N-1:0] cq_full, cq_head_done, out_fire, miss_go, hit_go;
  wire [N-1:0] cred_ok;
  wire [N-1:0] want_ar;                 // wants to issue a miss this cycle
  wire [N-1:0] ar_accept_oh;            // stream served this cycle, one-hot
  wire         ar_skid_ready;           // AR output register can take a beat

  // Registered line address of each stream's staged request (see the staging
  // register in gen_stream below). The AR address is taken from here rather
  // than from the combinational decode, so the AXI address path starts at a
  // flop instead of at taskIn_TDATA.
  wire [TAG_W-1:0] s_rq_tag [0:N-1];

  // ---- registered arbitration --------------------------------------------
  // The round-robin used to be consumed combinationally, so one stream's
  // cq_wp/cq_rp reached EVERY other stream's credit counter in a single cycle:
  //   cq_full[g] -> want_ar[g] -> arbiter -> ar_mine[h] -> credits[h]/D.
  // That was the whole of the remaining critical path (7-8 levels, e.g.
  // gen_stream[4].cq_wp -> gen_stream[3].credits/D at -0.782 ns). Putting a flop
  // on the grant makes the arbiter a cone from flops to a flop, and ar_mine a
  // comparison against a registered index.
  //
  // Registering a grant is only safe if the winner still wants it a cycle later.
  // want_ar[g] is monotonic until it is served: it is
  //     rq_v && !rq_hit && !cq_full[g] && cred_ok[g]
  // and while a stream waits for its grant, rq_v holds (rq_go is miss_go, which
  // is ar_mine), cq_full[g] can only fall (cq_wp advances only on this stream's
  // own allocation, cq_rp only drains) and credits can only rise (they are spent
  // only by this stream's own ar_mine). So a registered grant can never point at
  // a stream that has withdrawn.
  reg  [SEL_W-1:0] rr_ptr, grant_idx;
  reg              grant_val;
  reg  [SEL_W-1:0] grant_idx_q;
  reg              grant_val_q;
  integer k;
  reg [SEL_W:0] cand;

  // The stream being accepted this cycle must be excluded from the next grant:
  // its want_ar is still high (rq_v updates on the same edge), so without the
  // mask it would be granted twice and issue a duplicate AR.
  wire [N-1:0] want_ar_eff = want_ar & ~ar_accept_oh;

  always @* begin
    grant_val = 1'b0; grant_idx = {SEL_W{1'b0}};
    for (k = N-1; k >= 0; k = k - 1) begin
      cand = {1'b0, rr_ptr} + k[SEL_W:0];
      if (cand >= N[SEL_W:0]) cand = cand - N[SEL_W:0];
      if (want_ar_eff[cand[SEL_W-1:0]]) begin
        grant_val = 1'b1; grant_idx = cand[SEL_W-1:0];
      end
    end
  end

  // Hold the registered grant until the AR skid takes it.
  always @(posedge ap_clk) begin
    if (!ap_rst_n) begin
      grant_val_q <= 1'b0;
      grant_idx_q <= {SEL_W{1'b0}};
    end else if (!grant_val_q || ar_skid_ready) begin
      grant_val_q <= grant_val;
      grant_idx_q <= grant_idx;
    end
  end

  wire [ADDR_W-1:0] ar_addr_line =
      {s_rq_tag[grant_idx_q], {LINE_LOG2{1'b0}}};

  // AR output register. The grant used to drive ARVALID/ARADDR straight onto the
  // bus, so the arbiter sat between the stream flops and an external pin, and
  // ARREADY came back combinationally into ar_mine -> rq_go -> taskIn_TREADY.
  // With the skid the arbiter's cone now starts at flops (rq_v, rq_hit,
  // cq_full, cred_ok_r) and ends at one, and ARVALID/ARADDR are registered.
  wire [SEL_W-1:0] ar_id_out;
  applyFn_overlap_wrapper_mrc_skid #(.WIDTH(ADDR_W + SEL_W)) u_ar_skid (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .i_data({ar_addr_line, grant_idx_q}),
    .i_valid(grant_val_q), .i_ready(ar_skid_ready),
    .o_data({m_axi_gmem_ARADDR, ar_id_out}),
    .o_valid(m_axi_gmem_ARVALID), .o_ready(m_axi_gmem_ARREADY)
  );

  // A request is committed when the skid takes it, not when it reaches the bus.
  // The skid is in-order, so per-stream AR order (and hence R order) is
  // unchanged; the at-most-two beats it holds are already counted against
  // credits, so the outstanding bound still holds.
  wire ar_accept = grant_val_q && ar_skid_ready;
  // one-hot of the stream accepted this cycle, for the arbiter mask above
  assign ar_accept_oh = ar_accept ? ({{(N-1){1'b0}}, 1'b1} << grant_idx_q)
                                  : {N{1'b0}};

  always @(posedge ap_clk) begin
    if (!ap_rst_n) rr_ptr <= {SEL_W{1'b0}};
    else if (ar_accept)
      rr_ptr <= (grant_idx_q == (N[SEL_W-1:0] - 1'b1)) ? {SEL_W{1'b0}}
                                                       : grant_idx_q + 1'b1;
  end

  assign m_axi_gmem_ARID    = {{(ID_W-SEL_W){1'b0}}, ar_id_out};
  assign m_axi_gmem_ARSIZE  = LINE_LOG2[2:0];

  wire         r_fire = m_axi_gmem_RVALID && m_axi_gmem_RREADY;
  wire [SEL_W-1:0] r_sel = m_axi_gmem_RID[SEL_W-1:0];
  assign m_axi_gmem_RREADY = 1'b1;      // a credit reserved the slot at AR time

  // Count requests, not cycles: several streams can serve one in the same
  // cycle, and only the cached streams are meaningful here.
  reg [31:0] hit_cnt, miss_cnt;
  integer c;
  reg [31:0] hit_n, miss_n;
  always @* begin
    hit_n = 32'd0; miss_n = 32'd0;
    for (c = 0; c < N; c = c + 1) if (CACHE_EN[c]) begin
      if (hit_go[c])  hit_n  = hit_n  + 32'd1;
      if (miss_go[c]) miss_n = miss_n + 32'd1;
    end
  end
  assign dbg_cache_hits   = hit_cnt;
  assign dbg_cache_misses = miss_cnt;
  always @(posedge ap_clk) begin
    if (!ap_rst_n) begin hit_cnt <= 0; miss_cnt <= 0; end
    else begin
      hit_cnt  <= hit_cnt  + hit_n;
      miss_cnt <= miss_cnt + miss_n;
    end
  end

  generate
    for (g = 0; g < N; g = g + 1) begin : gen_stream
      localparam integer ELW = ELEM_W_VEC[8*g +: 8];

      wire [TAG_W-1:0]  req_tag  = s_addr[g][ADDR_W-1:LINE_LOG2];
      wire [LANE_W-1:0] req_lane = s_addr[g][LANE_W-1:0];

      // ---- the private-per-context cache --------------------------------
      wire              c_hit;
      wire [BUS_W-1:0]  c_data;
      wire              fill_en;
      wire [CTX_W-1:0]  fill_ctx;
      wire [TAG_W-1:0]  fill_tag;
      wire [BUS_W-1:0]  fill_data;
      wire [CTX_W-1:0]  fill_ctx_q;   // straight off the miss FIFO
      wire [TAG_W-1:0]  fill_tag_q;

      if (CACHE_EN[g]) begin : gen_cache
        applyFn_overlap_wrapper_ctx_cache #(
          .NUM_CTX(NUM_CTX), .CTX_W(CTX_W), .LINE_W(BUS_W), .TAG_W(TAG_W)
        ) u_cache (
          .clk(ap_clk), .rst_n(ap_rst_n),
          .lu_ctx(s_ctx[g]), .lu_tag(req_tag),
          .lu_hit(c_hit), .lu_data(c_data),
          .fill_en(fill_en), .fill_ctx(fill_ctx),
          .fill_tag(fill_tag), .fill_data(fill_data)
        );
      end else begin : gen_nocache
        assign c_hit  = 1'b0;
        assign c_data = {BUS_W{1'b0}};
      end

      // ---- stage 1 -> 2 staging register --------------------------------
      // The cache lookup and the issue decision used to resolve in one cycle:
      // tags[] LUTRAM read -> TAG_W-bit compare -> c_hit -> the cross-stream AR
      // arbiter -> the CQ write enable. That was 13 logic levels and the block's
      // critical path (-0.234 ns at 300 MHz out of context).
      //
      // Splitting it at c_hit puts the tag compare in cycle 1 and the
      // arbitration in cycle 2, with a flop between. Throughput is unchanged --
      // the stage accepts a new request in the same cycle it hands one on, so a
      // stream still issues one request per cycle -- at the cost of one extra
      // cycle of per-request latency.
      //
      // The captured (rq_hit, rq_data) pair is self-consistent: both are read
      // combinationally out of the same cache entry in the same cycle, so the
      // data always belongs to the tag that was compared. A fill landing after
      // the capture cannot invalidate it; at worst it makes a request that was
      // sampled as a miss fetch a line that has since arrived, which costs a
      // redundant read and is otherwise harmless.
      //
      // Ordering within a context is still safe: the wrapper's merge loop is
      // strictly serial per context (it cannot issue its next read until the
      // previous reply is delivered), and a context is only retired after its
      // last reply, so an extra stage in front of issue cannot reorder anything.
      reg               rq_v;
      reg [TAG_W-1:0]   rq_tag;
      reg [LANE_W-1:0]  rq_lane;
      reg [CONT_W-1:0]  rq_cont;
      reg [CTX_W-1:0]   rq_ctx;
      reg               rq_hit;
      reg [BUS_W-1:0]   rq_data;

      assign s_rq_tag[g] = rq_tag;

      wire rq_go    = hit_go[g] || miss_go[g];     // stage 2 consumes this cycle
      wire rq_ready = !rq_v || rq_go;              // ... so stage 1 may refill
      wire s1_fire  = q_valid[g] && rq_ready;
      // Drives the input skid, not the port: rq_ready still depends on the
      // arbiter, but that path now ends at the skid's flop instead of leaving
      // the module and clocking a wide register slice in the upstream PE.
      assign q_ready[g] = rq_ready;

      always @(posedge ap_clk) begin
        if (!ap_rst_n)     rq_v <= 1'b0;
        else if (s1_fire)  rq_v <= 1'b1;
        else if (rq_go)    rq_v <= 1'b0;
      end

      always @(posedge ap_clk) if (s1_fire) begin
        rq_tag  <= req_tag;
        rq_lane <= req_lane;
        rq_cont <= s_cont[g];
        rq_ctx  <= s_ctx[g];
        rq_hit  <= c_hit;
        rq_data <= c_data;
      end

      // ---- completion queue (in-order, hits and misses share it) ---------
      // The payload is split by *writer*, not by slot: hits are written at
      // allocate time (address cq_wp), fills when the R beat lands (address
      // missq_idx). One array taking both writes has two write ports in one
      // process, which defeats RAM inference -- Vivado then builds CQ_DEPTH x
      // BUS_W flip-flops plus a CQ_DEPTH:1 read mux per stream, which is what
      // over-utilised the device (2.6 M FF / 4 M LUT across 8 PEs). Split, each
      // array has exactly one write port and infers as a RAM. A miss slot's
      // hit-array entry is simply never read, so no storage is wasted that the
      // single-array version did not already write and discard.
      //
      // The payload is the ELEMENT, not the line. Both arrays used to hold whole
      // BUS_W lines and the element was taken out on the read side
      //     shifted = head_data >> {head_lane, 3'b000}
      // which put a 32:1 byte barrel shifter after the CQ_DEPTH:1 head mux, on
      // the emit path -- the largest remaining violation family (367 of the 5000
      // worst paths were cq_rp ==> u_memreader_cached). Extracting at write time
      // instead removes the shifter from that path and shrinks both arrays by
      // BUS_W/ELW (256 -> 32 or 64 bits), which also shortens the write-address
      // decode behind them (the f_idx ==> cq_fill_data family, another 224).
      //
      // Each write port has the lane of its own request in a flop already
      // (rq_lane for the hit port, f_lane off the miss FIFO for the fill port),
      // so both shifters sit on a flop -> shift -> RAM-write-data path with a
      // full period available, and neither is in series with an address decode.
      reg               cq_done [0:CQ_DEPTH-1];
      reg               cq_is_hit  [0:CQ_DEPTH-1];  // which array holds the payload
      reg [ELW-1:0]     cq_hit_data  [0:CQ_DEPTH-1]; // written only at cq_wp
      reg [ELW-1:0]     cq_fill_data [0:CQ_DEPTH-1]; // written only at missq_idx
      reg [CONT_W-1:0]  cq_cont [0:CQ_DEPTH-1];
      reg [CQ_AW:0]     cq_wp, cq_rp;

      wire cq_empty = (cq_wp == cq_rp);
      assign cq_full[g] = (cq_wp[CQ_AW-1:0] == cq_rp[CQ_AW-1:0]) &&
                          (cq_wp[CQ_AW] != cq_rp[CQ_AW]);
      assign cq_head_done[g] = !cq_empty && cq_done[cq_rp[CQ_AW-1:0]];

      // Credits bound the AXI outstanding of this stream. cred_ok is registered
      // rather than combinational off `credits`: it fed want_ar -> the shared
      // arbiter -> ar_mine -> every other stream's credit counter, which showed
      // up as a 7-level cross-stream path (gen_stream[0].credits ->
      // gen_stream[4].credits/D). Registering the *next* value keeps it exact --
      // at the coming edge `credits` equals credits_next, so this is not a
      // conservative approximation, just a retimed one.
      wire ar_mine = ar_accept && (grant_idx_q == g[SEL_W-1:0]);
      wire r_mine  = r_fire    && (r_sel     == g[SEL_W-1:0]);

      reg [CW-1:0] credits;
      reg          cred_ok_r;
      wire [CW-1:0] credits_next = credits - (ar_mine ? 1'b1 : 1'b0)
                                           + (r_mine  ? 1'b1 : 1'b0);
      assign cred_ok[g] = cred_ok_r;

      // A staged request is served this cycle if there is a completion slot,
      // and either it hit, or it can win the AR channel with a credit in hand.
      // Everything here starts at a flop (rq_*), not at the cache.
      assign want_ar[g] = rq_v && !rq_hit && !cq_full[g] && cred_ok[g];
      assign hit_go[g]  = rq_v && rq_hit && !cq_full[g];
      assign miss_go[g] = ar_mine;

      // miss-ordering FIFO: slot index awaiting an R beat, in issue order.
      // It also carries the request's LANE, so the fill port can extract the
      // element at write time (see the completion queue comment above). The
      // wrapper's merge loop is serial per context, so the lane cannot be
      // recovered from anywhere else once the request has left stage 2.
      wire [CQ_AW-1:0]  missq_idx;
      wire [LANE_W-1:0] fill_lane_q;
      wire              missq_valid;
      applyFn_overlap_wrapper_mrc_fifo #(.WIDTH(CQ_AW+CTX_W+TAG_W+LANE_W), .DEPTH(OUTSTANDING)) u_missq (
        .clk(ap_clk), .rst_n(ap_rst_n),
        .in_data({rq_tag, rq_lane, rq_ctx, cq_wp[CQ_AW-1:0]}),
        .in_valid(ar_mine), .in_ready(),
        .out_data({fill_tag_q, fill_lane_q, fill_ctx_q, missq_idx}),
        .out_valid(missq_valid), .out_ready(r_mine)
      );

      // ---- fill stage ----------------------------------------------------
      // The R beat used to write cq_fill_data in the same cycle it arrived, so
      // the path ran RDATA / missq (LUTRAM async read) -> the CQ_DEPTH write
      // address decode -> a 256-bit distributed-RAM write port. That was the
      // second-largest family of violations (1109 of 5000 paths ended at
      // cq_fill_data). Registering the beat first splits it in two.
      //
      // The done bit moves with the data, so a slot is never marked complete
      // before its payload has landed. Only one R beat can arrive per cycle on
      // the shared channel, so this one-deep stage cannot overflow, and RREADY
      // stays tied high.
      reg                 f_v;
      reg [BUS_W-1:0]     f_data;
      reg [CQ_AW-1:0]     f_idx;
      reg                 f_cache_en;
      reg [CTX_W-1:0]     f_ctx;
      reg [TAG_W-1:0]     f_tag;
      reg [LANE_W-1:0]    f_lane;
      always @(posedge ap_clk) begin
        if (!ap_rst_n) begin
          f_v <= 1'b0; f_cache_en <= 1'b0;
        end else begin
          f_v        <= r_mine && missq_valid;
          f_cache_en <= r_mine;
        end
        f_data <= m_axi_gmem_RDATA;
        f_idx  <= missq_idx;
        f_ctx  <= fill_ctx_q;
        f_tag  <= fill_tag_q;
        f_lane <= fill_lane_q;
      end
      // f_data stays the full line: the cache stores lines, so only the CQ
      // payload is narrowed.
      // The cache fill rides the same stage. Landing a line a cycle later can
      // only turn a would-be hit into a redundant fetch, never a wrong result.
      assign fill_en   = f_cache_en;
      assign fill_ctx  = f_ctx;
      assign fill_tag  = f_tag;
      assign fill_data = f_data;

      // Pointers and the done bits: control only, no wide payload.
      // hit_go and ar_mine are mutually exclusive (want_ar requires !c_hit), so
      // a slot is allocated as exactly one of hit or miss.
      integer q;
      always @(posedge ap_clk) begin
        if (!ap_rst_n) begin
          cq_wp <= 0; cq_rp <= 0;
          for (q = 0; q < CQ_DEPTH; q = q + 1) cq_done[q] <= 1'b0;
        end else begin
          if (hit_go[g] || ar_mine) begin
            cq_done[cq_wp[CQ_AW-1:0]] <= hit_go[g];
            cq_wp <= cq_wp + 1'b1;
          end
          if (f_v) cq_done[f_idx] <= 1'b1;
          if (out_fire[g]) cq_rp <= cq_rp + 1'b1;
        end
      end

      // Element extraction, one per write port. Both operands are flops, so
      // these are the only combinational logic between a flop and the array's
      // write-data pins.
      wire [BUS_W-1:0] hit_shifted  = rq_data >> {rq_lane, 3'b000};
      wire [BUS_W-1:0] fill_shifted = f_data  >> {f_lane,  3'b000};

      // Write port A: allocate. Needs no reset -- a slot is only ever read
      // after cq_done marks it, and cq_done is only set by a write through here
      // or through port B below.
      always @(posedge ap_clk) begin
        if (hit_go[g] || ar_mine) begin
          cq_is_hit   [cq_wp[CQ_AW-1:0]] <= hit_go[g];
          cq_hit_data [cq_wp[CQ_AW-1:0]] <= hit_shifted[ELW-1:0];
          cq_cont     [cq_wp[CQ_AW-1:0]] <= rq_cont;
        end
      end

      // Write port B: miss fill, from the registered fill stage.
      always @(posedge ap_clk) begin
        if (f_v) cq_fill_data[f_idx] <= fill_shifted[ELW-1:0];
      end

      always @(posedge ap_clk) begin
        if (!ap_rst_n) begin
          credits   <= OUTSTANDING;
          cred_ok_r <= 1'b1;
        end else begin
          credits   <= credits_next;
          cred_ok_r <= (credits_next != {CW{1'b0}});
        end
      end

      // ---- emit ---------------------------------------------------------
      // The element is already extracted, so the emit path is just the two
      // narrow head muxes and the is_hit select -- no barrel shifter.
      wire [ELW-1:0] head_elem = cq_is_hit[cq_rp[CQ_AW-1:0]]
                                   ? cq_hit_data [cq_rp[CQ_AW-1:0]]
                                   : cq_fill_data[cq_rp[CQ_AW-1:0]];

      reg [ARG_W-1:0] pkt;
      always @* begin
        pkt = {ARG_W{1'b0}};
        pkt[PKT_ADDR_LSB +: CONT_W] = cq_cont[cq_rp[CQ_AW-1:0]];
        pkt[PKT_DATA_LSB +: ELW]    = head_elem;
      end

      // Output skid. argOut and argDataOut are one logical channel split in two
      // (same valid, and out_fire already required both readies), so a single
      // buffer carries the pair. This registers the emit valid -- which came
      // straight off cq_rp/cq_done through the CQ_DEPTH:1 head mux and the byte
      // barrel shifter -- and stops the downstream PE's TREADY from reaching
      // back into cq_rp.
      wire [63:0]      head_cont = cq_cont[cq_rp[CQ_AW-1:0]];
      wire             e_ready;
      wire [ARG_W+64-1:0] e_out;

      applyFn_overlap_wrapper_mrc_skid #(.WIDTH(ARG_W + 64)) u_out_skid (
        .clk(ap_clk), .rst_n(ap_rst_n),
        .i_data({pkt, head_cont}),
        .i_valid(cq_head_done[g]), .i_ready(e_ready),
        .o_data(e_out),
        .o_valid(argDataOut_TVALID[g]),
        .o_ready(argDataOut_TREADY[g] && argOut_TREADY[g])
      );
      assign argOut_TDATA[g*64 +: 64]           = e_out[63:0];
      assign argDataOut_TDATA[g*ARG_W +: ARG_W] = e_out[ARG_W+64-1:64];
      assign argOut_TVALID[g] = argDataOut_TVALID[g];
      assign out_fire[g] = cq_head_done[g] && e_ready;
    end
  endgenerate

  // ---- constant AXI fields -----------------------------------------------
  assign m_axi_gmem_ARLEN    = 8'd0;
  assign m_axi_gmem_ARBURST  = 2'b01;
  assign m_axi_gmem_ARLOCK   = 2'b00;
  assign m_axi_gmem_ARCACHE  = 4'b0011;
  assign m_axi_gmem_ARPROT   = 3'b000;
  assign m_axi_gmem_ARQOS    = 4'b0000;
  assign m_axi_gmem_ARREGION = 4'b0000;
  assign m_axi_gmem_ARUSER   = 1'b0;
  assign m_axi_gmem_AWVALID  = 1'b0;
  assign m_axi_gmem_AWADDR   = {ADDR_W{1'b0}};
  assign m_axi_gmem_AWID     = {ID_W{1'b0}};
  assign m_axi_gmem_AWLEN    = 8'd0;
  assign m_axi_gmem_AWSIZE   = 3'd0;
  assign m_axi_gmem_AWBURST  = 2'b01;
  assign m_axi_gmem_AWLOCK   = 2'b00;
  assign m_axi_gmem_AWCACHE  = 4'b0011;
  assign m_axi_gmem_AWPROT   = 3'b000;
  assign m_axi_gmem_AWQOS    = 4'b0000;
  assign m_axi_gmem_AWREGION = 4'b0000;
  assign m_axi_gmem_AWUSER   = 1'b0;
  assign m_axi_gmem_WVALID   = 1'b0;
  assign m_axi_gmem_WDATA    = {BUS_W{1'b0}};
  assign m_axi_gmem_WSTRB    = {(BUS_W/8){1'b0}};
  assign m_axi_gmem_WLAST    = 1'b0;
  assign m_axi_gmem_WID      = {ID_W{1'b0}};
  assign m_axi_gmem_WUSER    = 1'b0;
  assign m_axi_gmem_BREADY   = 1'b1;

endmodule
// ===========================================================================
// applyFn_overlap_wrapper_ctx_cache — one private line per resident context.
//
// Why not index by address
// ------------------------
// Collisions in this workload are not between addresses within one walk; they
// are between the ~46 concurrent merge loops, each walking an unrelated region.
// An address-indexed cache spends its associativity doing nothing but keeping
// those contexts apart: measured on the real trace, 64 entries/stream gives
// 48.7 % direct-mapped, 75.7 % 8-way, 80.9 % fully associative.
//
// Indexing by context instead makes conflicts impossible by construction. Each
// resident loop owns exactly one entry, evicts only itself, and does so exactly
// when it advances past the line — the moment that line is dead. Measured
// ceiling for that binding on the same trace: **88.2 %** of consecutive
// same-context requests hit the same line, a further 8.2 % hit the next one
// (so a next-line prefetch would reach ~96 %).
//
// Cost is one BRAM read and one comparator: no CAM, no way mux, no replacement
// policy, no priority encoder.
//
// Tags are kept full, so a context ID that is freed and reallocated needs no
// invalidation — the stale entry simply misses, because the new owner's line
// address cannot match. Only a truncated tag would require a valid-bit clear at
// allocation.
//
// Read-only data is assumed (neighbour lists are not written during the merge),
// so there is no coherence obligation.
// ===========================================================================

module applyFn_overlap_wrapper_ctx_cache #(
  parameter NUM_CTX = 64,                 // entries == number of resident contexts
  parameter CTX_W   = 6,                  // $clog2(NUM_CTX)
  parameter LINE_W  = 256,                // line width in bits
  parameter TAG_W   = 32                  // line-address tag
) (
  input                    clk,
  input                    rst_n,

  // ---- lookup: combinational, same cycle as the request ------------------
  input  [CTX_W-1:0]       lu_ctx,
  input  [TAG_W-1:0]       lu_tag,
  output                   lu_hit,
  output [LINE_W-1:0]      lu_data,

  // ---- fill ---------------------------------------------------------------
  input                    fill_en,
  input  [CTX_W-1:0]       fill_ctx,
  input  [TAG_W-1:0]       fill_tag,
  input  [LINE_W-1:0]      fill_data
);

  reg [TAG_W-1:0]  tags  [0:NUM_CTX-1];
  reg              valid [0:NUM_CTX-1];
  reg [LINE_W-1:0] data  [0:NUM_CTX-1];

  integer i;
  initial begin
    for (i = 0; i < NUM_CTX; i = i + 1) begin
      valid[i] = 1'b0;
      tags[i]  = {TAG_W{1'b0}};
      data[i]  = {LINE_W{1'b0}};
    end
  end

  assign lu_hit  = valid[lu_ctx] && (tags[lu_ctx] == lu_tag);
  assign lu_data = data[lu_ctx];

  always @(posedge clk) begin
    if (!rst_n) begin
      for (i = 0; i < NUM_CTX; i = i + 1) valid[i] <= 1'b0;
    end else if (fill_en) begin
      valid[fill_ctx] <= 1'b1;
      tags [fill_ctx] <= fill_tag;
    end
  end

  always @(posedge clk) if (fill_en) data[fill_ctx] <= fill_data;

endmodule

module applyFn_overlap_wrapper #(
  parameter STATE_DEPTH     = 128,
  parameter REPLY_DEPTH     = 64,
  parameter MEM_ADDR_WIDTH  = 64,
  parameter MEM_ID_WIDTH    = 1,
  parameter MEM_SHARED_ID_WIDTH    = 1,
  parameter MEM_SHARED_DATA_WIDTH  = 256,
  parameter MEM_SHARED_OUTSTANDING = 64,
  parameter CQ_DEPTH        = STATE_DEPTH,
  parameter MEM_DATA_WIDTH_applyFn = 32,
  parameter MEM_DATA_WIDTH_applyFn_reentry1_cont1 = 32,
  parameter MEM_DATA_WIDTH_applyFn_exit1 = 32
) (
  input                       ap_clk,
  input                       ap_rst_n,
  // Root task closure injected by the host / upstream scheduler.
  input  [511:0]  taskIn_TDATA,
  input                       taskIn_TVALID,
  output                      taskIn_TREADY,
  // Loop result out (exit task -> external continuation).
  output [63:0]               argOut_TDATA,
  output                      argOut_TVALID,
  input                       argOut_TREADY,
  output [255:0]              argDataOut_TDATA,
  output                      argDataOut_TVALID,
  input                       argDataOut_TREADY,
  // Shared AXI4 memory master for all 2 read site(s).
  output m_axi_gmem_shared_AWVALID,
  input  m_axi_gmem_shared_AWREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_shared_AWADDR,
  output [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_AWID,
  output [7:0] m_axi_gmem_shared_AWLEN,
  output [2:0] m_axi_gmem_shared_AWSIZE,
  output [1:0] m_axi_gmem_shared_AWBURST,
  output [1:0] m_axi_gmem_shared_AWLOCK,
  output [3:0] m_axi_gmem_shared_AWCACHE,
  output [2:0] m_axi_gmem_shared_AWPROT,
  output [3:0] m_axi_gmem_shared_AWQOS,
  output [3:0] m_axi_gmem_shared_AWREGION,
  output m_axi_gmem_shared_AWUSER,
  output m_axi_gmem_shared_WVALID,
  input  m_axi_gmem_shared_WREADY,
  output [MEM_SHARED_DATA_WIDTH-1:0] m_axi_gmem_shared_WDATA,
  output [(MEM_SHARED_DATA_WIDTH/8)-1:0] m_axi_gmem_shared_WSTRB,
  output m_axi_gmem_shared_WLAST,
  output [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_WID,
  output m_axi_gmem_shared_WUSER,
  output m_axi_gmem_shared_ARVALID,
  input  m_axi_gmem_shared_ARREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_shared_ARADDR,
  output [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_ARID,
  output [7:0] m_axi_gmem_shared_ARLEN,
  output [2:0] m_axi_gmem_shared_ARSIZE,
  output [1:0] m_axi_gmem_shared_ARBURST,
  output [1:0] m_axi_gmem_shared_ARLOCK,
  output [3:0] m_axi_gmem_shared_ARCACHE,
  output [2:0] m_axi_gmem_shared_ARPROT,
  output [3:0] m_axi_gmem_shared_ARQOS,
  output [3:0] m_axi_gmem_shared_ARREGION,
  output m_axi_gmem_shared_ARUSER,
  input  m_axi_gmem_shared_RVALID,
  output m_axi_gmem_shared_RREADY,
  input  [MEM_SHARED_DATA_WIDTH-1:0] m_axi_gmem_shared_RDATA,
  input  m_axi_gmem_shared_RLAST,
  input  [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_RID,
  input  m_axi_gmem_shared_RUSER,
  input  [1:0] m_axi_gmem_shared_RRESP,
  input  m_axi_gmem_shared_BVALID,
  output m_axi_gmem_shared_BREADY,
  input  [1:0] m_axi_gmem_shared_BRESP,
  input  [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_BID,
  input  m_axi_gmem_shared_BUSER,
  // AXI4 memory master for PE 'applyFn'.
  output m_axi_gmem_applyFn_AWVALID,
  input  m_axi_gmem_applyFn_AWREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_applyFn_AWADDR,
  output [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_AWID,
  output [7:0] m_axi_gmem_applyFn_AWLEN,
  output [2:0] m_axi_gmem_applyFn_AWSIZE,
  output [1:0] m_axi_gmem_applyFn_AWBURST,
  output [1:0] m_axi_gmem_applyFn_AWLOCK,
  output [3:0] m_axi_gmem_applyFn_AWCACHE,
  output [2:0] m_axi_gmem_applyFn_AWPROT,
  output [3:0] m_axi_gmem_applyFn_AWQOS,
  output [3:0] m_axi_gmem_applyFn_AWREGION,
  output m_axi_gmem_applyFn_AWUSER,
  output m_axi_gmem_applyFn_WVALID,
  input  m_axi_gmem_applyFn_WREADY,
  output [MEM_DATA_WIDTH_applyFn-1:0] m_axi_gmem_applyFn_WDATA,
  output [(MEM_DATA_WIDTH_applyFn/8)-1:0] m_axi_gmem_applyFn_WSTRB,
  output m_axi_gmem_applyFn_WLAST,
  output [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_WID,
  output m_axi_gmem_applyFn_WUSER,
  output m_axi_gmem_applyFn_ARVALID,
  input  m_axi_gmem_applyFn_ARREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_applyFn_ARADDR,
  output [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_ARID,
  output [7:0] m_axi_gmem_applyFn_ARLEN,
  output [2:0] m_axi_gmem_applyFn_ARSIZE,
  output [1:0] m_axi_gmem_applyFn_ARBURST,
  output [1:0] m_axi_gmem_applyFn_ARLOCK,
  output [3:0] m_axi_gmem_applyFn_ARCACHE,
  output [2:0] m_axi_gmem_applyFn_ARPROT,
  output [3:0] m_axi_gmem_applyFn_ARQOS,
  output [3:0] m_axi_gmem_applyFn_ARREGION,
  output m_axi_gmem_applyFn_ARUSER,
  input  m_axi_gmem_applyFn_RVALID,
  output m_axi_gmem_applyFn_RREADY,
  input  [MEM_DATA_WIDTH_applyFn-1:0] m_axi_gmem_applyFn_RDATA,
  input  m_axi_gmem_applyFn_RLAST,
  input  [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_RID,
  input  m_axi_gmem_applyFn_RUSER,
  input  [1:0] m_axi_gmem_applyFn_RRESP,
  input  m_axi_gmem_applyFn_BVALID,
  output m_axi_gmem_applyFn_BREADY,
  input  [1:0] m_axi_gmem_applyFn_BRESP,
  input  [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_BID,
  input  m_axi_gmem_applyFn_BUSER,
  // AXI4 memory master for PE 'applyFn_reentry1_cont1'.
  output m_axi_gmem_applyFn_reentry1_cont1_AWVALID,
  input  m_axi_gmem_applyFn_reentry1_cont1_AWREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_applyFn_reentry1_cont1_AWADDR,
  output [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_reentry1_cont1_AWID,
  output [7:0] m_axi_gmem_applyFn_reentry1_cont1_AWLEN,
  output [2:0] m_axi_gmem_applyFn_reentry1_cont1_AWSIZE,
  output [1:0] m_axi_gmem_applyFn_reentry1_cont1_AWBURST,
  output [1:0] m_axi_gmem_applyFn_reentry1_cont1_AWLOCK,
  output [3:0] m_axi_gmem_applyFn_reentry1_cont1_AWCACHE,
  output [2:0] m_axi_gmem_applyFn_reentry1_cont1_AWPROT,
  output [3:0] m_axi_gmem_applyFn_reentry1_cont1_AWQOS,
  output [3:0] m_axi_gmem_applyFn_reentry1_cont1_AWREGION,
  output m_axi_gmem_applyFn_reentry1_cont1_AWUSER,
  output m_axi_gmem_applyFn_reentry1_cont1_WVALID,
  input  m_axi_gmem_applyFn_reentry1_cont1_WREADY,
  output [MEM_DATA_WIDTH_applyFn_reentry1_cont1-1:0] m_axi_gmem_applyFn_reentry1_cont1_WDATA,
  output [(MEM_DATA_WIDTH_applyFn_reentry1_cont1/8)-1:0] m_axi_gmem_applyFn_reentry1_cont1_WSTRB,
  output m_axi_gmem_applyFn_reentry1_cont1_WLAST,
  output [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_reentry1_cont1_WID,
  output m_axi_gmem_applyFn_reentry1_cont1_WUSER,
  output m_axi_gmem_applyFn_reentry1_cont1_ARVALID,
  input  m_axi_gmem_applyFn_reentry1_cont1_ARREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_applyFn_reentry1_cont1_ARADDR,
  output [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_reentry1_cont1_ARID,
  output [7:0] m_axi_gmem_applyFn_reentry1_cont1_ARLEN,
  output [2:0] m_axi_gmem_applyFn_reentry1_cont1_ARSIZE,
  output [1:0] m_axi_gmem_applyFn_reentry1_cont1_ARBURST,
  output [1:0] m_axi_gmem_applyFn_reentry1_cont1_ARLOCK,
  output [3:0] m_axi_gmem_applyFn_reentry1_cont1_ARCACHE,
  output [2:0] m_axi_gmem_applyFn_reentry1_cont1_ARPROT,
  output [3:0] m_axi_gmem_applyFn_reentry1_cont1_ARQOS,
  output [3:0] m_axi_gmem_applyFn_reentry1_cont1_ARREGION,
  output m_axi_gmem_applyFn_reentry1_cont1_ARUSER,
  input  m_axi_gmem_applyFn_reentry1_cont1_RVALID,
  output m_axi_gmem_applyFn_reentry1_cont1_RREADY,
  input  [MEM_DATA_WIDTH_applyFn_reentry1_cont1-1:0] m_axi_gmem_applyFn_reentry1_cont1_RDATA,
  input  m_axi_gmem_applyFn_reentry1_cont1_RLAST,
  input  [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_reentry1_cont1_RID,
  input  m_axi_gmem_applyFn_reentry1_cont1_RUSER,
  input  [1:0] m_axi_gmem_applyFn_reentry1_cont1_RRESP,
  input  m_axi_gmem_applyFn_reentry1_cont1_BVALID,
  output m_axi_gmem_applyFn_reentry1_cont1_BREADY,
  input  [1:0] m_axi_gmem_applyFn_reentry1_cont1_BRESP,
  input  [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_reentry1_cont1_BID,
  input  m_axi_gmem_applyFn_reentry1_cont1_BUSER,
  // AXI4 memory master for PE 'applyFn_exit1'.
  output m_axi_gmem_applyFn_exit1_AWVALID,
  input  m_axi_gmem_applyFn_exit1_AWREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_applyFn_exit1_AWADDR,
  output [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_exit1_AWID,
  output [7:0] m_axi_gmem_applyFn_exit1_AWLEN,
  output [2:0] m_axi_gmem_applyFn_exit1_AWSIZE,
  output [1:0] m_axi_gmem_applyFn_exit1_AWBURST,
  output [1:0] m_axi_gmem_applyFn_exit1_AWLOCK,
  output [3:0] m_axi_gmem_applyFn_exit1_AWCACHE,
  output [2:0] m_axi_gmem_applyFn_exit1_AWPROT,
  output [3:0] m_axi_gmem_applyFn_exit1_AWQOS,
  output [3:0] m_axi_gmem_applyFn_exit1_AWREGION,
  output m_axi_gmem_applyFn_exit1_AWUSER,
  output m_axi_gmem_applyFn_exit1_WVALID,
  input  m_axi_gmem_applyFn_exit1_WREADY,
  output [MEM_DATA_WIDTH_applyFn_exit1-1:0] m_axi_gmem_applyFn_exit1_WDATA,
  output [(MEM_DATA_WIDTH_applyFn_exit1/8)-1:0] m_axi_gmem_applyFn_exit1_WSTRB,
  output m_axi_gmem_applyFn_exit1_WLAST,
  output [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_exit1_WID,
  output m_axi_gmem_applyFn_exit1_WUSER,
  output m_axi_gmem_applyFn_exit1_ARVALID,
  input  m_axi_gmem_applyFn_exit1_ARREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_applyFn_exit1_ARADDR,
  output [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_exit1_ARID,
  output [7:0] m_axi_gmem_applyFn_exit1_ARLEN,
  output [2:0] m_axi_gmem_applyFn_exit1_ARSIZE,
  output [1:0] m_axi_gmem_applyFn_exit1_ARBURST,
  output [1:0] m_axi_gmem_applyFn_exit1_ARLOCK,
  output [3:0] m_axi_gmem_applyFn_exit1_ARCACHE,
  output [2:0] m_axi_gmem_applyFn_exit1_ARPROT,
  output [3:0] m_axi_gmem_applyFn_exit1_ARQOS,
  output [3:0] m_axi_gmem_applyFn_exit1_ARREGION,
  output m_axi_gmem_applyFn_exit1_ARUSER,
  input  m_axi_gmem_applyFn_exit1_RVALID,
  output m_axi_gmem_applyFn_exit1_RREADY,
  input  [MEM_DATA_WIDTH_applyFn_exit1-1:0] m_axi_gmem_applyFn_exit1_RDATA,
  input  m_axi_gmem_applyFn_exit1_RLAST,
  input  [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_exit1_RID,
  input  m_axi_gmem_applyFn_exit1_RUSER,
  input  [1:0] m_axi_gmem_applyFn_exit1_RRESP,
  input  m_axi_gmem_applyFn_exit1_BVALID,
  output m_axi_gmem_applyFn_exit1_BREADY,
  input  [1:0] m_axi_gmem_applyFn_exit1_BRESP,
  input  [MEM_ID_WIDTH-1:0] m_axi_gmem_applyFn_exit1_BID,
  input  m_axi_gmem_applyFn_exit1_BUSER
);

  // Context-ID space: one private cache line per resident loop.
  // NUM_CTX/CTX_W follow STATE_DEPTH: contexts = MAX_INFLIGHT
  // rounded up to a power of two. Undersizing collapses the hit
  // rate (measured 71.5% at 64 entries vs 2.5% at 32).
  localparam NUM_CTX = STATE_DEPTH;
  localparam CTX_W   = $clog2(STATE_DEPTH);

  wire [1023:0] re_in_TDATA;
  wire re_in_TVALID;
  wire re_in_TREADY;
  wire [1023:0] root_out_TDATA;
  wire root_out_TVALID;
  wire root_out_TREADY;
  wire [1023:0] cont_loop_TDATA;
  wire cont_loop_TVALID;
  wire cont_loop_TREADY;
  wire [1023:0] cont_loop_q_TDATA;
  wire cont_loop_q_TVALID;
  wire cont_loop_q_TREADY;
  wire [255:0] re_mem_TDATA;
  wire re_mem_TVALID;
  wire re_mem_TREADY;
  wire [511:0] re_exit_TDATA;
  wire re_exit_TVALID;
  wire re_exit_TREADY;
  wire [1023:0] re_state_TDATA;
  wire re_state_TVALID;
  wire re_state_TREADY;
  wire [1023:0] state_q_TDATA;
  wire state_q_TVALID;
  wire state_q_TREADY;
  wire [255:0] mem_data_TDATA;
  wire mem_data_TVALID;
  wire mem_data_TREADY;
  wire [255:0] mem_data_q_TDATA;
  wire mem_data_q_TVALID;
  wire mem_data_q_TREADY;
  wire [63:0] mem_argOut_TDATA;  wire mem_argOut_TVALID;  wire mem_argOut_TREADY;
  wire [1023:0] cont_in_TDATA;
  wire cont_in_TVALID;
  wire cont_in_TREADY;
  // Round 1: issued by applyFn_reentry1_cont0.
  wire [1023:0] iss_state_1_TDATA;
  wire iss_state_1_TVALID;
  wire iss_state_1_TREADY;
  wire [1023:0] state_q_1_TDATA;
  wire state_q_1_TVALID;
  wire state_q_1_TREADY;
  wire [1023:0] cont_in_1_TDATA;
  wire cont_in_1_TVALID;
  wire cont_in_1_TREADY;
  wire [255:0] iss_mem_1_TDATA;
  wire iss_mem_1_TVALID;
  wire iss_mem_1_TREADY;
  wire [255:0] mem_data_1_TDATA;
  wire mem_data_1_TVALID;
  wire mem_data_1_TREADY;
  wire [255:0] mem_data_1_q_TDATA;
  wire mem_data_1_q_TVALID;
  wire mem_data_1_q_TREADY;
  wire [63:0] mem_argOut_1_TDATA;  wire mem_argOut_1_TVALID;  wire mem_argOut_1_TREADY;
  wire [63:0] exit_applyFn_reentry1_cont0_argOut_TDATA; wire exit_applyFn_reentry1_cont0_argOut_TVALID; wire exit_applyFn_reentry1_cont0_argOut_TREADY;
  wire [255:0] exit_applyFn_reentry1_cont0_argData_TDATA; wire exit_applyFn_reentry1_cont0_argData_TVALID; wire exit_applyFn_reentry1_cont0_argData_TREADY;
  wire [63:0] exit_spawnerFunction_reentry0_cont0_argOut_TDATA; wire exit_spawnerFunction_reentry0_cont0_argOut_TVALID; wire exit_spawnerFunction_reentry0_cont0_argOut_TREADY;
  wire [255:0] exit_spawnerFunction_reentry0_cont0_argData_TDATA; wire exit_spawnerFunction_reentry0_cont0_argData_TVALID; wire exit_spawnerFunction_reentry0_cont0_argData_TREADY;

  // ── Inbound skid: registers the scheduler -> PE task stream ─────────────
  wire [511:0] task_in_q_TDATA;
  wire         task_in_q_TVALID;
  wire         task_in_q_TREADY;
  applyFn_overlap_wrapper_mrc_skid #(.WIDTH(512)) u_task_in_skid (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .i_data(taskIn_TDATA), .i_valid(taskIn_TVALID), .i_ready(taskIn_TREADY),
    .o_data(task_in_q_TDATA), .o_valid(task_in_q_TVALID), .o_ready(task_in_q_TREADY)
  );

  // ── Root PE (loop initializer) ───────────────────────────────────────────
  applyFn u_root (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(task_in_q_TDATA), .taskIn_TVALID(task_in_q_TVALID), .taskIn_TREADY(task_in_q_TREADY),
    .taskGlobalOut_applyFn_reentry1_TDATA(root_out_TDATA),
    .taskGlobalOut_applyFn_reentry1_TVALID(root_out_TVALID),
    .taskGlobalOut_applyFn_reentry1_TREADY(root_out_TREADY),
    .m_axi_gmem_AWVALID(m_axi_gmem_applyFn_AWVALID),
    .m_axi_gmem_AWREADY(m_axi_gmem_applyFn_AWREADY),
    .m_axi_gmem_AWADDR(m_axi_gmem_applyFn_AWADDR),
    .m_axi_gmem_AWID(m_axi_gmem_applyFn_AWID),
    .m_axi_gmem_AWLEN(m_axi_gmem_applyFn_AWLEN),
    .m_axi_gmem_AWSIZE(m_axi_gmem_applyFn_AWSIZE),
    .m_axi_gmem_AWBURST(m_axi_gmem_applyFn_AWBURST),
    .m_axi_gmem_AWLOCK(m_axi_gmem_applyFn_AWLOCK),
    .m_axi_gmem_AWCACHE(m_axi_gmem_applyFn_AWCACHE),
    .m_axi_gmem_AWPROT(m_axi_gmem_applyFn_AWPROT),
    .m_axi_gmem_AWQOS(m_axi_gmem_applyFn_AWQOS),
    .m_axi_gmem_AWREGION(m_axi_gmem_applyFn_AWREGION),
    .m_axi_gmem_AWUSER(m_axi_gmem_applyFn_AWUSER),
    .m_axi_gmem_WVALID(m_axi_gmem_applyFn_WVALID),
    .m_axi_gmem_WREADY(m_axi_gmem_applyFn_WREADY),
    .m_axi_gmem_WDATA(m_axi_gmem_applyFn_WDATA),
    .m_axi_gmem_WSTRB(m_axi_gmem_applyFn_WSTRB),
    .m_axi_gmem_WLAST(m_axi_gmem_applyFn_WLAST),
    .m_axi_gmem_WID(m_axi_gmem_applyFn_WID),
    .m_axi_gmem_WUSER(m_axi_gmem_applyFn_WUSER),
    .m_axi_gmem_ARVALID(m_axi_gmem_applyFn_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_applyFn_ARREADY),
    .m_axi_gmem_ARADDR(m_axi_gmem_applyFn_ARADDR),
    .m_axi_gmem_ARID(m_axi_gmem_applyFn_ARID),
    .m_axi_gmem_ARLEN(m_axi_gmem_applyFn_ARLEN),
    .m_axi_gmem_ARSIZE(m_axi_gmem_applyFn_ARSIZE),
    .m_axi_gmem_ARBURST(m_axi_gmem_applyFn_ARBURST),
    .m_axi_gmem_ARLOCK(m_axi_gmem_applyFn_ARLOCK),
    .m_axi_gmem_ARCACHE(m_axi_gmem_applyFn_ARCACHE),
    .m_axi_gmem_ARPROT(m_axi_gmem_applyFn_ARPROT),
    .m_axi_gmem_ARQOS(m_axi_gmem_applyFn_ARQOS),
    .m_axi_gmem_ARREGION(m_axi_gmem_applyFn_ARREGION),
    .m_axi_gmem_ARUSER(m_axi_gmem_applyFn_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_applyFn_RVALID),
    .m_axi_gmem_RREADY(m_axi_gmem_applyFn_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_applyFn_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_applyFn_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_applyFn_RID),
    .m_axi_gmem_RUSER(m_axi_gmem_applyFn_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_applyFn_RRESP),
    .m_axi_gmem_BVALID(m_axi_gmem_applyFn_BVALID),
    .m_axi_gmem_BREADY(m_axi_gmem_applyFn_BREADY),
    .m_axi_gmem_BRESP(m_axi_gmem_applyFn_BRESP),
    .m_axi_gmem_BID(m_axi_gmem_applyFn_BID),
    .m_axi_gmem_BUSER(m_axi_gmem_applyFn_BUSER),
    .s_axi_control_AWVALID(1'b0),
    .s_axi_control_AWADDR(1'b0),
    .s_axi_control_WVALID(1'b0),
    .s_axi_control_WDATA(1'b0),
    .s_axi_control_WSTRB(1'b0),
    .s_axi_control_ARVALID(1'b0),
    .s_axi_control_ARADDR(1'b0),
    .s_axi_control_RREADY(1'b0),
    .s_axi_control_BREADY(1'b0)
  );

  // ── Context-ID plumbing: declarations (logic follows the rounds) ─────────
  wire [1024+CTX_W-1:0] re_in_wide;
  wire [1024+CTX_W-1:0] cont_loop_q_wide;
  wire [CTX_W-1:0] ctx_in       = re_in_wide[1024 +: CTX_W];
  wire [CTX_W-1:0] ctx_loopback = cont_loop_q_wide[1024 +: CTX_W];
  wire [CTX_W-1:0] ctx_retire;                // ID of the loop that is exiting
  wire [CTX_W-1:0] ctxB_head;
  wire [1024+CTX_W-1:0] state_q_wide;
  wire [CTX_W-1:0] ctx_state = state_q_wide[1024 +: CTX_W];
  wire [CTX_W-1:0] ctxS_head;
  wire [CTX_W-1:0] re_mem_ctx_head;
  wire [1024+CTX_W-1:0] state_q_1_wide;
  wire [CTX_W-1:0] ctx_state_1 = state_q_1_wide[1024 +: CTX_W];
  wire [CTX_W-1:0] ctxS_1_head;
  wire [CTX_W-1:0] iss_mem_1_ctx_head;
  assign re_in_TDATA = re_in_wide[1023:0];
  assign cont_loop_q_TDATA = cont_loop_q_wide[1023:0];
  assign state_q_TDATA = state_q_wide[1023:0];
  assign state_q_1_TDATA = state_q_1_wide[1023:0];

  // ── Loopback FIFO (breaks the reentry->...->continuation->reentry cycle) ──
  applyFn_overlap_wrapper_fifo #(.WIDTH(1024+CTX_W), .DEPTH(STATE_DEPTH)) u_loop_fifo (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data({ctxB_head, cont_loop_TDATA}), .in_valid(cont_loop_TVALID), .in_ready(cont_loop_TREADY),
    .out_data(cont_loop_q_wide), .out_valid(cont_loop_q_TVALID), .out_ready(cont_loop_q_TREADY)
  );

  // ── Admission control: keep in-flight tasks < buffer depth ───────────────
  localparam MAX_INFLIGHT = STATE_DEPTH - 8;
  localparam IW = $clog2(STATE_DEPTH+1);
  reg  [IW-1:0] inflight;
  // Free queue of context IDs; the old in-flight bound still applies.
  //
  // The array has exactly ONE write port, in its own process, so it
  // infers as distributed RAM. It used to be broadside-initialised to
  // the identity permutation in the reset branch, which is a second
  // write source: Vivado then dissolved it into NUM_CTX*CTX_W flops read
  // through a NUM_CTX:1 mux, and the MUXF7/MUXF8 tree that produced was
  // a failing path into the context RAM's write port.
  //
  // The identity is instead served straight from the read pointer for the
  // first pass over the queue -- the same values the initialisation would
  // have stored -- and the RAM is read only once every slot has been
  // written back by a retiring loop. That is safe, and safe across a
  // re-reset, because the queue never holds more than NUM_CTX IDs: slot k
  // is always read before it is written, and reaching rp == NUM_CTX resets
  // wp to NUM_CTX too, so a RAM read can only be *consumed* (credit_ok
  // requires !empty, i.e. wp > rp) after a retire of this run wrote it.
  reg  [CTX_W-1:0] ctxq [0:NUM_CTX-1];
  reg  [IW-1:0] ctxq_wp, ctxq_rp;
  reg              ctxq_init;
  reg              ctxq_primed;
  wire             ctxq_empty = (ctxq_wp == ctxq_rp);
  wire [CTX_W-1:0] ctx_alloc  = ctxq_primed
                                 ? ctxq[ctxq_rp[IW-1:0] % NUM_CTX]
                                 : ctxq_rp[CTX_W-1:0];
  wire credit_ok = ctxq_init && !ctxq_empty
                      && (inflight < MAX_INFLIGHT[IW-1:0]);
  wire arb_a_ready;
  wire admit_fire = root_out_TVALID && credit_ok && arb_a_ready;
  wire exit_fire  = re_exit_TVALID && re_exit_TREADY;
  assign root_out_TREADY = arb_a_ready && credit_ok;
  always @(posedge ap_clk)
    if (exit_fire) ctxq[ctxq_wp[IW-1:0] % NUM_CTX] <= ctx_retire;
  always @(posedge ap_clk) begin
    if (!ap_rst_n) begin
      inflight <= 0; ctxq_wp <= 0; ctxq_rp <= 0; ctxq_init <= 1'b0;
      ctxq_primed <= 1'b0;
    end else begin
      if (!ctxq_init) begin
        // every ID starts free
        ctxq_wp <= NUM_CTX[IW-1:0];
        ctxq_init <= 1'b1;
      end else begin
        if (admit_fire) begin
          ctxq_rp <= ctxq_rp + 1'b1;
          // from here on every slot has been written back
          if (ctxq_rp == (NUM_CTX[IW-1:0] - 1'b1)) ctxq_primed <= 1'b1;
        end
        if (exit_fire) ctxq_wp <= ctxq_wp + 1'b1;
      end
      inflight <= inflight + (admit_fire ? 1'b1 : 1'b0)
                                 - (exit_fire ? 1'b1 : 1'b0);
    end
  end

  // ── reentry.taskIn arbiter: initial spawn + continuation loopback ─────────
  applyFn_overlap_wrapper_arb2 #(.WIDTH(1024+CTX_W)) u_re_arb (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .a_data({ctx_alloc, root_out_TDATA}),
    .a_valid(root_out_TVALID && credit_ok), .a_ready(arb_a_ready),
    .b_data({ctx_loopback, cont_loop_q_TDATA}),
    .b_valid(cont_loop_q_TVALID), .b_ready(cont_loop_q_TREADY),
    .o_data(re_in_wide), .o_valid(re_in_TVALID), .o_ready(re_in_TREADY)
  );

  // ── Reentry PE (condition + issue reads + push state) ────────────────────
  applyFn_reentry1 u_reentry (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(re_in_TDATA), .taskIn_TVALID(re_in_TVALID), .taskIn_TREADY(re_in_TREADY),
    .taskGlobalOut_memrd0_depends_applyFn_reentry1_cont0_TDATA(re_mem_TDATA),
    .taskGlobalOut_memrd0_depends_applyFn_reentry1_cont0_TVALID(re_mem_TVALID),
    .taskGlobalOut_memrd0_depends_applyFn_reentry1_cont0_TREADY(re_mem_TREADY),
    .taskGlobalOut_applyFn_exit1_TDATA(re_exit_TDATA),
    .taskGlobalOut_applyFn_exit1_TVALID(re_exit_TVALID),
    .taskGlobalOut_applyFn_exit1_TREADY(re_exit_TREADY),
    .contStateOut_applyFn_reentry1_cont0_TDATA(re_state_TDATA),
    .contStateOut_applyFn_reentry1_cont0_TVALID(re_state_TVALID),
    .contStateOut_applyFn_reentry1_cont0_TREADY(re_state_TREADY)
  );

  // ── Continuation-state FIFO (holds loop-carried state per iteration) ──────
  applyFn_overlap_wrapper_fifo #(.WIDTH(1024+CTX_W), .DEPTH(STATE_DEPTH)) u_state_fifo (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data({ctxS_head, re_state_TDATA}), .in_valid(re_state_TVALID), .in_ready(re_state_TREADY),
    .out_data(state_q_wide), .out_valid(state_q_TVALID), .out_ready(state_q_TREADY)
  );

  // ── Read site for reply field 'v': stream re_mem on the shared reader ──
  assign mem_argOut_TREADY = 1'b1; // reply address unused in streaming mode
  applyFn_overlap_wrapper_fifo #(.WIDTH(256), .DEPTH(REPLY_DEPTH)) u_memreader_rq (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(mem_data_TDATA), .in_valid(mem_data_TVALID), .in_ready(mem_data_TREADY),
    .out_data(mem_data_q_TDATA), .out_valid(mem_data_q_TVALID), .out_ready(mem_data_q_TREADY)
  );

  // ── Merge unit: join 1 parallel reply channel(s) + STATE_FIFO head ──────
  // Each site has its own in-order channel, so the k-th reply of an
  // iteration is the head of channel k. All 1 are consumed in ONE cycle
  // and drive continuation field(s) 'v'.
  reg  [1023:0] outbuf;    // stable joined closure
  reg  outbuf_v;
  wire [31:0] reply_data_0 = mem_data_q_TDATA[95:64];
  reg  [1023:0] joined;
  always @* begin
    joined = state_q_TDATA;
    joined[671:640] = reply_data_0; // v
  end
  // Output register is free to load when empty or draining this cycle.
  wire out_ready = !outbuf_v || cont_in_TREADY;
  wire all_replies = mem_data_q_TVALID;
  wire gather    = all_replies && state_q_TVALID && out_ready;
  assign mem_data_q_TREADY = gather;
  assign state_q_TREADY  = gather;
  assign cont_in_TVALID  = outbuf_v;
  assign cont_in_TDATA   = outbuf;
  always @(posedge ap_clk) begin
    if (!ap_rst_n) begin
      outbuf_v <= 1'b0;
    end else begin
      if (cont_in_TVALID && cont_in_TREADY) outbuf_v <= 1'b0;
      if (gather) begin outbuf <= joined; outbuf_v <= 1'b1; end
    end
  end

  // ── Continuation PE (issues round 1) ───────────────────
  applyFn_reentry1_cont0 u_cont (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(cont_in_TDATA), .taskIn_TVALID(cont_in_TVALID), .taskIn_TREADY(cont_in_TREADY),
    .taskGlobalOut_memrd1_depends_applyFn_reentry1_cont1_TDATA(iss_mem_1_TDATA),
    .taskGlobalOut_memrd1_depends_applyFn_reentry1_cont1_TVALID(iss_mem_1_TVALID),
    .taskGlobalOut_memrd1_depends_applyFn_reentry1_cont1_TREADY(iss_mem_1_TREADY),
    .contStateOut_applyFn_reentry1_cont1_TDATA(iss_state_1_TDATA),
    .contStateOut_applyFn_reentry1_cont1_TVALID(iss_state_1_TVALID),
    .contStateOut_applyFn_reentry1_cont1_TREADY(iss_state_1_TREADY)
  );

  // ── Continuation-state FIFO (holds loop-carried state per iteration) ──────
  applyFn_overlap_wrapper_fifo #(.WIDTH(1024+CTX_W), .DEPTH(STATE_DEPTH)) u_state_fifo_1 (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data({ctxS_1_head, iss_state_1_TDATA}), .in_valid(iss_state_1_TVALID), .in_ready(iss_state_1_TREADY),
    .out_data(state_q_1_wide), .out_valid(state_q_1_TVALID), .out_ready(state_q_1_TREADY)
  );

  // ── Read site for reply field 'v_size': stream iss_mem_1 on the shared reader ──
  assign mem_argOut_1_TREADY = 1'b1; // reply address unused in streaming mode
  applyFn_overlap_wrapper_fifo #(.WIDTH(256), .DEPTH(REPLY_DEPTH)) u_memreader_1_rq (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(mem_data_1_TDATA), .in_valid(mem_data_1_TVALID), .in_ready(mem_data_1_TREADY),
    .out_data(mem_data_1_q_TDATA), .out_valid(mem_data_1_q_TVALID), .out_ready(mem_data_1_q_TREADY)
  );

  // ── Merge unit: join 1 parallel reply channel(s) + STATE_FIFO head ──────
  // Each site has its own in-order channel, so the k-th reply of an
  // iteration is the head of channel k. All 1 are consumed in ONE cycle
  // and drive continuation field(s) 'v_size'.
  reg  [1023:0] outbuf_1;    // stable joined closure
  reg  outbuf_v_1;
  wire [63:0] reply_data_1_0 = mem_data_1_q_TDATA[127:64];
  reg  [1023:0] joined_1;
  always @* begin
    joined_1 = state_q_1_TDATA;
    joined_1[735:672] = reply_data_1_0; // v_size
  end
  // Output register is free to load when empty or draining this cycle.
  wire out_ready_1 = !outbuf_v_1 || cont_in_1_TREADY;
  wire all_replies_1 = mem_data_1_q_TVALID;
  wire gather_1    = all_replies_1 && state_q_1_TVALID && out_ready_1;
  assign mem_data_1_q_TREADY = gather_1;
  assign state_q_1_TREADY  = gather_1;
  assign cont_in_1_TVALID  = outbuf_v_1;
  assign cont_in_1_TDATA   = outbuf_1;
  always @(posedge ap_clk) begin
    if (!ap_rst_n) begin
      outbuf_v_1 <= 1'b0;
    end else begin
      if (cont_in_1_TVALID && cont_in_1_TREADY) outbuf_v_1 <= 1'b0;
      if (gather_1) begin outbuf_1 <= joined_1; outbuf_v_1 <= 1'b1; end
    end
  end

  // ── Continuation PE (loop body; loops back to reentry) ───────────────────
  applyFn_reentry1_cont1 u_cont_1 (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(cont_in_1_TDATA), .taskIn_TVALID(cont_in_1_TVALID), .taskIn_TREADY(cont_in_1_TREADY),
    .taskGlobalOut_applyFn_reentry1_TDATA(cont_loop_TDATA),
    .taskGlobalOut_applyFn_reentry1_TVALID(cont_loop_TVALID),
    .taskGlobalOut_applyFn_reentry1_TREADY(cont_loop_TREADY),
    .m_axi_gmem_AWVALID(m_axi_gmem_applyFn_reentry1_cont1_AWVALID),
    .m_axi_gmem_AWREADY(m_axi_gmem_applyFn_reentry1_cont1_AWREADY),
    .m_axi_gmem_AWADDR(m_axi_gmem_applyFn_reentry1_cont1_AWADDR),
    .m_axi_gmem_AWID(m_axi_gmem_applyFn_reentry1_cont1_AWID),
    .m_axi_gmem_AWLEN(m_axi_gmem_applyFn_reentry1_cont1_AWLEN),
    .m_axi_gmem_AWSIZE(m_axi_gmem_applyFn_reentry1_cont1_AWSIZE),
    .m_axi_gmem_AWBURST(m_axi_gmem_applyFn_reentry1_cont1_AWBURST),
    .m_axi_gmem_AWLOCK(m_axi_gmem_applyFn_reentry1_cont1_AWLOCK),
    .m_axi_gmem_AWCACHE(m_axi_gmem_applyFn_reentry1_cont1_AWCACHE),
    .m_axi_gmem_AWPROT(m_axi_gmem_applyFn_reentry1_cont1_AWPROT),
    .m_axi_gmem_AWQOS(m_axi_gmem_applyFn_reentry1_cont1_AWQOS),
    .m_axi_gmem_AWREGION(m_axi_gmem_applyFn_reentry1_cont1_AWREGION),
    .m_axi_gmem_AWUSER(m_axi_gmem_applyFn_reentry1_cont1_AWUSER),
    .m_axi_gmem_WVALID(m_axi_gmem_applyFn_reentry1_cont1_WVALID),
    .m_axi_gmem_WREADY(m_axi_gmem_applyFn_reentry1_cont1_WREADY),
    .m_axi_gmem_WDATA(m_axi_gmem_applyFn_reentry1_cont1_WDATA),
    .m_axi_gmem_WSTRB(m_axi_gmem_applyFn_reentry1_cont1_WSTRB),
    .m_axi_gmem_WLAST(m_axi_gmem_applyFn_reentry1_cont1_WLAST),
    .m_axi_gmem_WID(m_axi_gmem_applyFn_reentry1_cont1_WID),
    .m_axi_gmem_WUSER(m_axi_gmem_applyFn_reentry1_cont1_WUSER),
    .m_axi_gmem_ARVALID(m_axi_gmem_applyFn_reentry1_cont1_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_applyFn_reentry1_cont1_ARREADY),
    .m_axi_gmem_ARADDR(m_axi_gmem_applyFn_reentry1_cont1_ARADDR),
    .m_axi_gmem_ARID(m_axi_gmem_applyFn_reentry1_cont1_ARID),
    .m_axi_gmem_ARLEN(m_axi_gmem_applyFn_reentry1_cont1_ARLEN),
    .m_axi_gmem_ARSIZE(m_axi_gmem_applyFn_reentry1_cont1_ARSIZE),
    .m_axi_gmem_ARBURST(m_axi_gmem_applyFn_reentry1_cont1_ARBURST),
    .m_axi_gmem_ARLOCK(m_axi_gmem_applyFn_reentry1_cont1_ARLOCK),
    .m_axi_gmem_ARCACHE(m_axi_gmem_applyFn_reentry1_cont1_ARCACHE),
    .m_axi_gmem_ARPROT(m_axi_gmem_applyFn_reentry1_cont1_ARPROT),
    .m_axi_gmem_ARQOS(m_axi_gmem_applyFn_reentry1_cont1_ARQOS),
    .m_axi_gmem_ARREGION(m_axi_gmem_applyFn_reentry1_cont1_ARREGION),
    .m_axi_gmem_ARUSER(m_axi_gmem_applyFn_reentry1_cont1_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_applyFn_reentry1_cont1_RVALID),
    .m_axi_gmem_RREADY(m_axi_gmem_applyFn_reentry1_cont1_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_applyFn_reentry1_cont1_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_applyFn_reentry1_cont1_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_applyFn_reentry1_cont1_RID),
    .m_axi_gmem_RUSER(m_axi_gmem_applyFn_reentry1_cont1_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_applyFn_reentry1_cont1_RRESP),
    .m_axi_gmem_BVALID(m_axi_gmem_applyFn_reentry1_cont1_BVALID),
    .m_axi_gmem_BREADY(m_axi_gmem_applyFn_reentry1_cont1_BREADY),
    .m_axi_gmem_BRESP(m_axi_gmem_applyFn_reentry1_cont1_BRESP),
    .m_axi_gmem_BID(m_axi_gmem_applyFn_reentry1_cont1_BID),
    .m_axi_gmem_BUSER(m_axi_gmem_applyFn_reentry1_cont1_BUSER),
    .s_axi_control_AWVALID(1'b0),
    .s_axi_control_AWADDR(1'b0),
    .s_axi_control_WVALID(1'b0),
    .s_axi_control_WDATA(1'b0),
    .s_axi_control_WSTRB(1'b0),
    .s_axi_control_ARVALID(1'b0),
    .s_axi_control_ARADDR(1'b0),
    .s_axi_control_RREADY(1'b0),
    .s_axi_control_BREADY(1'b0)
  );

  // ── Context-ID plumbing: logic (declarations precede the ring) ──────────
  wire re_in_fire = re_in_TVALID && re_in_TREADY;
  wire cont_loop_fire = cont_loop_TVALID && cont_loop_TREADY;
  wire re_state_fire = re_state_TVALID && re_state_TREADY;
  wire re_mem_fire = re_mem_TVALID && re_mem_TREADY;
  wire iss_state_1_fire = iss_state_1_TVALID && iss_state_1_TREADY;
  wire iss_mem_1_fire = iss_mem_1_TVALID && iss_mem_1_TREADY;
  assign ctx_retire = ctxS_head;

  applyFn_overlap_wrapper_fifo #(.WIDTH(CTX_W), .DEPTH(STATE_DEPTH)) u_ctxS (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(ctx_in), .in_valid(re_in_fire), .in_ready(),
    .out_data(ctxS_head), .out_valid(),
    .out_ready(re_state_fire || exit_fire));
  applyFn_overlap_wrapper_fifo #(.WIDTH(CTX_W), .DEPTH(STATE_DEPTH)) u_ctx_re_mem (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(ctx_in), .in_valid(re_in_fire), .in_ready(),
    .out_data(re_mem_ctx_head), .out_valid(),
    .out_ready(re_mem_fire || exit_fire));
  applyFn_overlap_wrapper_fifo #(.WIDTH(CTX_W), .DEPTH(STATE_DEPTH)) u_ctxS_1 (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(ctx_state), .in_valid(gather), .in_ready(),
    .out_data(ctxS_1_head), .out_valid(),
    .out_ready(iss_state_1_fire));
  applyFn_overlap_wrapper_fifo #(.WIDTH(CTX_W), .DEPTH(STATE_DEPTH)) u_ctx_iss_mem_1 (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(ctx_state), .in_valid(gather), .in_ready(),
    .out_data(iss_mem_1_ctx_head), .out_valid(),
    .out_ready(iss_mem_1_fire));
  applyFn_overlap_wrapper_fifo #(.WIDTH(CTX_W), .DEPTH(STATE_DEPTH)) u_ctxB (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(ctx_state_1), .in_valid(gather_1), .in_ready(),
    .out_data(ctxB_head), .out_valid(),
    .out_ready(cont_loop_fire));

  // ────────────────────────────────────────────────────────────────────────
  // All 2 read site(s) on one master; ARID = stream index, per-stream
  // credits equal the per-stream reply depth so RREADY stays high and no
  // site can head-of-line block another. Each cached site holds one private
  // line per resident context; every request, hit or miss, takes a slot in
  // that stream's in-order completion queue, so a hit can never overtake an
  // older miss (the merge unit pairs the k-th reply with the k-th state
  // entry — reordering here silently corrupts results).
  // ────────────────────────────────────────────────────────────────────────
  applyFn_overlap_wrapper_memreader_cached #(
    .N(2), .TASK_W(256), .ARG_W(256),
    .ADDR_W(MEM_ADDR_WIDTH), .BUS_W(MEM_SHARED_DATA_WIDTH),
    .ID_W(MEM_SHARED_ID_WIDTH),
    .NUM_CTX(NUM_CTX), .CTX_W(CTX_W),
    .ELEM_LOG2_VEC({8'd3, 8'd2}),
    .ELEM_W_VEC({8'd64, 8'd32}),
    .IDX_W_VEC({8'd61, 8'd62}),
    .CACHE_EN(2'b11),
    .CONT_LSB(0), .BASE_LSB(64), .IDX_LSB(128),
    .PKT_ADDR_LSB(0), .PKT_DATA_LSB(64),
    .OUTSTANDING(MEM_SHARED_OUTSTANDING), .CQ_DEPTH(CQ_DEPTH)
  ) u_memreader_cached (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),

    .taskIn_TDATA({iss_mem_1_TDATA, re_mem_TDATA}),
    .taskIn_TVALID({iss_mem_1_TVALID, re_mem_TVALID}),
    .taskIn_TREADY({iss_mem_1_TREADY, re_mem_TREADY}),
    .taskIn_CTX({iss_mem_1_ctx_head, re_mem_ctx_head}),

    .argOut_TDATA({mem_argOut_1_TDATA, mem_argOut_TDATA}),
    .argOut_TVALID({mem_argOut_1_TVALID, mem_argOut_TVALID}),
    .argOut_TREADY({mem_argOut_1_TREADY, mem_argOut_TREADY}),

    .argDataOut_TDATA({mem_data_1_TDATA, mem_data_TDATA}),
    .argDataOut_TVALID({mem_data_1_TVALID, mem_data_TVALID}),
    .argDataOut_TREADY({mem_data_1_TREADY, mem_data_TREADY}),

    .m_axi_gmem_AWVALID(m_axi_gmem_shared_AWVALID),
    .m_axi_gmem_AWREADY(m_axi_gmem_shared_AWREADY),
    .m_axi_gmem_AWADDR(m_axi_gmem_shared_AWADDR),
    .m_axi_gmem_AWID(m_axi_gmem_shared_AWID),
    .m_axi_gmem_AWLEN(m_axi_gmem_shared_AWLEN),
    .m_axi_gmem_AWSIZE(m_axi_gmem_shared_AWSIZE),
    .m_axi_gmem_AWBURST(m_axi_gmem_shared_AWBURST),
    .m_axi_gmem_AWLOCK(m_axi_gmem_shared_AWLOCK),
    .m_axi_gmem_AWCACHE(m_axi_gmem_shared_AWCACHE),
    .m_axi_gmem_AWPROT(m_axi_gmem_shared_AWPROT),
    .m_axi_gmem_AWQOS(m_axi_gmem_shared_AWQOS),
    .m_axi_gmem_AWREGION(m_axi_gmem_shared_AWREGION),
    .m_axi_gmem_AWUSER(m_axi_gmem_shared_AWUSER),
    .m_axi_gmem_WVALID(m_axi_gmem_shared_WVALID),
    .m_axi_gmem_WREADY(m_axi_gmem_shared_WREADY),
    .m_axi_gmem_WDATA(m_axi_gmem_shared_WDATA),
    .m_axi_gmem_WSTRB(m_axi_gmem_shared_WSTRB),
    .m_axi_gmem_WLAST(m_axi_gmem_shared_WLAST),
    .m_axi_gmem_WID(m_axi_gmem_shared_WID),
    .m_axi_gmem_WUSER(m_axi_gmem_shared_WUSER),
    .m_axi_gmem_ARVALID(m_axi_gmem_shared_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_shared_ARREADY),
    .m_axi_gmem_ARADDR(m_axi_gmem_shared_ARADDR),
    .m_axi_gmem_ARID(m_axi_gmem_shared_ARID),
    .m_axi_gmem_ARLEN(m_axi_gmem_shared_ARLEN),
    .m_axi_gmem_ARSIZE(m_axi_gmem_shared_ARSIZE),
    .m_axi_gmem_ARBURST(m_axi_gmem_shared_ARBURST),
    .m_axi_gmem_ARLOCK(m_axi_gmem_shared_ARLOCK),
    .m_axi_gmem_ARCACHE(m_axi_gmem_shared_ARCACHE),
    .m_axi_gmem_ARPROT(m_axi_gmem_shared_ARPROT),
    .m_axi_gmem_ARQOS(m_axi_gmem_shared_ARQOS),
    .m_axi_gmem_ARREGION(m_axi_gmem_shared_ARREGION),
    .m_axi_gmem_ARUSER(m_axi_gmem_shared_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_shared_RVALID),
    .m_axi_gmem_RREADY(m_axi_gmem_shared_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_shared_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_shared_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_shared_RID),
    .m_axi_gmem_RUSER(m_axi_gmem_shared_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_shared_RRESP),
    .m_axi_gmem_BVALID(m_axi_gmem_shared_BVALID),
    .m_axi_gmem_BREADY(m_axi_gmem_shared_BREADY),
    .m_axi_gmem_BRESP(m_axi_gmem_shared_BRESP),
    .m_axi_gmem_BID(m_axi_gmem_shared_BID),
    .m_axi_gmem_BUSER(m_axi_gmem_shared_BUSER),
    .dbg_cache_hits(), .dbg_cache_misses()
  );

  // ── Exit PE (loop termination) ───────────────────────────────────────────
  applyFn_exit1 u_exit (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(re_exit_TDATA), .taskIn_TVALID(re_exit_TVALID), .taskIn_TREADY(re_exit_TREADY),
    .argOut_applyFn_reentry1_cont0_TDATA(exit_applyFn_reentry1_cont0_argOut_TDATA), .argOut_applyFn_reentry1_cont0_TVALID(exit_applyFn_reentry1_cont0_argOut_TVALID), .argOut_applyFn_reentry1_cont0_TREADY(exit_applyFn_reentry1_cont0_argOut_TREADY),
    .argDataOut_applyFn_reentry1_cont0_TDATA(exit_applyFn_reentry1_cont0_argData_TDATA), .argDataOut_applyFn_reentry1_cont0_TVALID(exit_applyFn_reentry1_cont0_argData_TVALID), .argDataOut_applyFn_reentry1_cont0_TREADY(exit_applyFn_reentry1_cont0_argData_TREADY),
    .argOut_spawnerFunction_reentry0_cont0_TDATA(exit_spawnerFunction_reentry0_cont0_argOut_TDATA), .argOut_spawnerFunction_reentry0_cont0_TVALID(exit_spawnerFunction_reentry0_cont0_argOut_TVALID), .argOut_spawnerFunction_reentry0_cont0_TREADY(exit_spawnerFunction_reentry0_cont0_argOut_TREADY),
    .argDataOut_spawnerFunction_reentry0_cont0_TDATA(exit_spawnerFunction_reentry0_cont0_argData_TDATA), .argDataOut_spawnerFunction_reentry0_cont0_TVALID(exit_spawnerFunction_reentry0_cont0_argData_TVALID), .argDataOut_spawnerFunction_reentry0_cont0_TREADY(exit_spawnerFunction_reentry0_cont0_argData_TREADY),
    .m_axi_gmem_AWVALID(m_axi_gmem_applyFn_exit1_AWVALID),
    .m_axi_gmem_AWREADY(m_axi_gmem_applyFn_exit1_AWREADY),
    .m_axi_gmem_AWADDR(m_axi_gmem_applyFn_exit1_AWADDR),
    .m_axi_gmem_AWID(m_axi_gmem_applyFn_exit1_AWID),
    .m_axi_gmem_AWLEN(m_axi_gmem_applyFn_exit1_AWLEN),
    .m_axi_gmem_AWSIZE(m_axi_gmem_applyFn_exit1_AWSIZE),
    .m_axi_gmem_AWBURST(m_axi_gmem_applyFn_exit1_AWBURST),
    .m_axi_gmem_AWLOCK(m_axi_gmem_applyFn_exit1_AWLOCK),
    .m_axi_gmem_AWCACHE(m_axi_gmem_applyFn_exit1_AWCACHE),
    .m_axi_gmem_AWPROT(m_axi_gmem_applyFn_exit1_AWPROT),
    .m_axi_gmem_AWQOS(m_axi_gmem_applyFn_exit1_AWQOS),
    .m_axi_gmem_AWREGION(m_axi_gmem_applyFn_exit1_AWREGION),
    .m_axi_gmem_AWUSER(m_axi_gmem_applyFn_exit1_AWUSER),
    .m_axi_gmem_WVALID(m_axi_gmem_applyFn_exit1_WVALID),
    .m_axi_gmem_WREADY(m_axi_gmem_applyFn_exit1_WREADY),
    .m_axi_gmem_WDATA(m_axi_gmem_applyFn_exit1_WDATA),
    .m_axi_gmem_WSTRB(m_axi_gmem_applyFn_exit1_WSTRB),
    .m_axi_gmem_WLAST(m_axi_gmem_applyFn_exit1_WLAST),
    .m_axi_gmem_WID(m_axi_gmem_applyFn_exit1_WID),
    .m_axi_gmem_WUSER(m_axi_gmem_applyFn_exit1_WUSER),
    .m_axi_gmem_ARVALID(m_axi_gmem_applyFn_exit1_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_applyFn_exit1_ARREADY),
    .m_axi_gmem_ARADDR(m_axi_gmem_applyFn_exit1_ARADDR),
    .m_axi_gmem_ARID(m_axi_gmem_applyFn_exit1_ARID),
    .m_axi_gmem_ARLEN(m_axi_gmem_applyFn_exit1_ARLEN),
    .m_axi_gmem_ARSIZE(m_axi_gmem_applyFn_exit1_ARSIZE),
    .m_axi_gmem_ARBURST(m_axi_gmem_applyFn_exit1_ARBURST),
    .m_axi_gmem_ARLOCK(m_axi_gmem_applyFn_exit1_ARLOCK),
    .m_axi_gmem_ARCACHE(m_axi_gmem_applyFn_exit1_ARCACHE),
    .m_axi_gmem_ARPROT(m_axi_gmem_applyFn_exit1_ARPROT),
    .m_axi_gmem_ARQOS(m_axi_gmem_applyFn_exit1_ARQOS),
    .m_axi_gmem_ARREGION(m_axi_gmem_applyFn_exit1_ARREGION),
    .m_axi_gmem_ARUSER(m_axi_gmem_applyFn_exit1_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_applyFn_exit1_RVALID),
    .m_axi_gmem_RREADY(m_axi_gmem_applyFn_exit1_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_applyFn_exit1_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_applyFn_exit1_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_applyFn_exit1_RID),
    .m_axi_gmem_RUSER(m_axi_gmem_applyFn_exit1_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_applyFn_exit1_RRESP),
    .m_axi_gmem_BVALID(m_axi_gmem_applyFn_exit1_BVALID),
    .m_axi_gmem_BREADY(m_axi_gmem_applyFn_exit1_BREADY),
    .m_axi_gmem_BRESP(m_axi_gmem_applyFn_exit1_BRESP),
    .m_axi_gmem_BID(m_axi_gmem_applyFn_exit1_BID),
    .m_axi_gmem_BUSER(m_axi_gmem_applyFn_exit1_BUSER),
    .s_axi_control_AWVALID(1'b0),
    .s_axi_control_AWADDR(1'b0),
    .s_axi_control_WVALID(1'b0),
    .s_axi_control_WDATA(1'b0),
    .s_axi_control_WSTRB(1'b0),
    .s_axi_control_ARVALID(1'b0),
    .s_axi_control_ARADDR(1'b0),
    .s_axi_control_RREADY(1'b0),
    .s_axi_control_BREADY(1'b0)
  );

  // 'applyFn_reentry1_cont0' is internal to the loop (fed by the merge unit); sink the exit's path.
  assign exit_applyFn_reentry1_cont0_argOut_TREADY = 1'b1;
  assign exit_applyFn_reentry1_cont0_argData_TREADY = 1'b1;
  // 'spawnerFunction_reentry0_cont0' is outside the collapsed loop: expose the result.
  // ── Outbound skids: register the PE -> notifier result streams ─────────
  // argOut and argData are independent channels with independent
  // valids (the PE raises them cycles apart), so each is buffered
  // on its own; merging them drops one of the two.
  wire [63:0] exit_spawnerFunction_reentry0_cont0_out_q;
  wire exit_spawnerFunction_reentry0_cont0_out_q_valid;
  wire exit_spawnerFunction_reentry0_cont0_out_q_ready;
  applyFn_overlap_wrapper_mrc_skid #(.WIDTH(64)) u_exit_spawnerFunction_reentry0_cont0_out_skid (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .i_data(exit_spawnerFunction_reentry0_cont0_argOut_TDATA),
    .i_valid(exit_spawnerFunction_reentry0_cont0_argOut_TVALID), .i_ready(exit_spawnerFunction_reentry0_cont0_out_q_ready),
    .o_data(exit_spawnerFunction_reentry0_cont0_out_q), .o_valid(exit_spawnerFunction_reentry0_cont0_out_q_valid),
    .o_ready(argOut_TREADY)
  );
  assign argOut_TDATA  = exit_spawnerFunction_reentry0_cont0_out_q;
  assign argOut_TVALID = exit_spawnerFunction_reentry0_cont0_out_q_valid;
  assign exit_spawnerFunction_reentry0_cont0_argOut_TREADY = exit_spawnerFunction_reentry0_cont0_out_q_ready;
  wire [255:0] exit_spawnerFunction_reentry0_cont0_argdata_q;
  wire exit_spawnerFunction_reentry0_cont0_argdata_q_valid;
  wire exit_spawnerFunction_reentry0_cont0_argdata_q_ready;
  applyFn_overlap_wrapper_mrc_skid #(.WIDTH(256)) u_exit_spawnerFunction_reentry0_cont0_argdata_skid (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .i_data(exit_spawnerFunction_reentry0_cont0_argData_TDATA),
    .i_valid(exit_spawnerFunction_reentry0_cont0_argData_TVALID), .i_ready(exit_spawnerFunction_reentry0_cont0_argdata_q_ready),
    .o_data(exit_spawnerFunction_reentry0_cont0_argdata_q), .o_valid(exit_spawnerFunction_reentry0_cont0_argdata_q_valid),
    .o_ready(argDataOut_TREADY)
  );
  assign argDataOut_TDATA  = exit_spawnerFunction_reentry0_cont0_argdata_q;
  assign argDataOut_TVALID = exit_spawnerFunction_reentry0_cont0_argdata_q_valid;
  assign exit_spawnerFunction_reentry0_cont0_argData_TREADY = exit_spawnerFunction_reentry0_cont0_argdata_q_ready;

endmodule
