// ===========================================================================
// Generated by bombyx-cc — #pragma BOMBYX OVERLAP Verilog wrapper
// Application : randomWalk_overlap
//
// In-order streaming continuation delivery. The reentry PE pushes each
// iteration's continuation state onto STATE_FIFO and issues 2 memory
// read(s); the single in-order memReader reply channel is gathered 2 at a
// time and merged with the head of STATE_FIFO to drive the continuation PE.
//
// The loop body has 2 dependence levels of loads, so the chain is
// applyFn_reentry0 -> applyFn_reentry0_cont0 -> applyFn_reentry0_cont1, each stage issuing its own round of reads.
// Every round is an independent in-order reply channel with its own
// memReader, STATE_FIFO and merge unit; no arbitration or reply tagging is
// needed, and rounds whose element widths differ are served naturally.
//
// PE AXI-Stream ports follow the Vitis HLS convention: for an `axis` port
// `p`, the RTL exposes p_TDATA / p_TVALID / p_TREADY, plus ap_clk / ap_rst_n.
//
// External interface (everything not internal to the collapsed tasks):
//   * taskIn_*  — root task closure in (== root PE's taskIn)
//   * argOut_*  — loop completion out (== exit PE's argOut)
//   * m_axi_gmem_shared_* — ONE AXI4 memory master serving every read site
//     (ARID = site index), via the shared reader below
//   * m_axi_gmem_<pe>_* — one AXI4 memory master per remaining
//     memory-accessing PE (inline loads/stores), passed straight through
//     (Vitis default bundle name `gmem`). The per-PE s_axi_control offset
//     slave is tied idle (offset 0).
// ===========================================================================

module applyFn_overlap_wrapper_fifo #(
  parameter WIDTH = 32,
  parameter DEPTH = 512
) (
  input                  clk,
  input                  rst_n,
  input  [WIDTH-1:0]     in_data,
  input                  in_valid,
  output                 in_ready,
  output [WIDTH-1:0]     out_data,
  output                 out_valid,
  input                  out_ready
);
  localparam AW = $clog2(DEPTH); // DEPTH must be a power of two
  (* ram_style = "block" *)
  reg [WIDTH-1:0] mem [0:DEPTH-1];
  reg [AW:0] wptr, rptr;
  wire ram_empty = (wptr == rptr);
  reg  ready_r;
  assign in_ready = ready_r;
  wire push = in_valid && in_ready;

  // Output register: holds the head so the RAM's registered read is hidden.
  reg [WIDTH-1:0] outreg;
  reg             outreg_v;
  // Refill whenever the array has data and the output register is free.
  // Gating on !ram_empty also guarantees the read address never equals a
  // write address in the same cycle, so there is no read/write collision.
  wire pop = !ram_empty && (!outreg_v || out_ready);
  assign out_valid = outreg_v;
  assign out_data  = outreg;

  // Occupancy of the storage array at the end of this cycle; see the
  // registered-in_ready note above.
  wire [AW:0] occ_next = (wptr + {{AW{1'b0}}, push}) -
                         (rptr + {{AW{1'b0}}, pop});

  // Storage: no reset, so this infers a block RAM cleanly.
  always @(posedge clk) begin
    if (push) mem[wptr[AW-1:0]] <= in_data;
    if (pop)  outreg <= mem[rptr[AW-1:0]];
  end

  always @(posedge clk) begin
    if (!rst_n) begin
      wptr <= 0; rptr <= 0; outreg_v <= 1'b0; ready_r <= 1'b0;
    end else begin
      if (push) wptr <= wptr + 1'b1;
      if (pop)  rptr <= rptr + 1'b1;
      if (pop)            outreg_v <= 1'b1;
      else if (out_ready) outreg_v <= 1'b0;
      ready_r <= !(occ_next[AW] | (&occ_next[AW-1:0]));
    end
  end
endmodule

module applyFn_overlap_wrapper_arb2 #(parameter WIDTH = 32) (
  input               clk,
  input               rst_n,
  input  [WIDTH-1:0]  a_data,  input a_valid,  output a_ready,
  input  [WIDTH-1:0]  b_data,  input b_valid,  output b_ready,
  output [WIDTH-1:0]  o_data,  output o_valid, input  o_ready
);
  reg sel; // 0: prefer a, 1: prefer b
  wire pick_a = a_valid && (!b_valid || sel == 1'b0);
  assign o_valid = a_valid || b_valid;
  assign o_data  = pick_a ? a_data : b_data;
  assign a_ready = pick_a && o_ready;
  assign b_ready = !pick_a && o_valid && o_ready;
  always @(posedge clk) if (!rst_n) sel <= 0;
    else if (o_valid && o_ready) sel <= pick_a ? 1'b1 : 1'b0;
endmodule

// ===========================================================================
// applyFn_overlap_wrapper_mrc_skid -- generic one-beat skid buffer.
//
// Used by the OVERLAP wrapper top for its inbound task stream and its
// outbound result streams, INDEPENDENTLY of which shared-reader flavour the
// wrapper instantiates. It therefore lives in its own file and is emitted
// unconditionally; it used to sit inside bombyx_mem_reader_cached.v, which
// meant any design whose readers were all uncached (no ctx cache) emitted
// instantiations of a module that was never defined, and failed elaboration.
// ===========================================================================
// ===========================================================================
// applyFn_overlap_wrapper_mrc_skid — two-entry skid buffer, registered in BOTH directions.
//
// i_ready is a flop output (~skid_v), not a function of o_ready, and o_valid is
// a flop. So neither the forward valid/data path nor the backward ready path
// carries combinational logic through the buffer.
//
// This is what breaks the handshake chains that dominated timing: the memory
// reader's taskIn_TREADY used to be
//
//     taskIn_TREADY[g] = rq_ready = !rq_v || hit_go[g] || ar_mine
//
// i.e. one stream's ready depended combinationally on every stream's CQ
// pointers and credit counters (via the shared AR arbiter) and then drove a
// 1024-bit register slice's clock enable in the upstream HLS PE -- measured at
// 12-13 logic levels and 4.4-4.8 ns, against a 3.333 ns budget.
//
// Costs one cycle of latency per interface; sustains one transfer per cycle,
// so no throughput is lost.
// ===========================================================================
module applyFn_overlap_wrapper_mrc_skid #(
  parameter WIDTH = 32
) (
  input                  clk,
  input                  rst_n,
  input  [WIDTH-1:0]     i_data,
  input                  i_valid,
  output                 i_ready,
  output [WIDTH-1:0]     o_data,
  output                 o_valid,
  input                  o_ready
);
  reg [WIDTH-1:0] data_r, skid_d;
  reg             valid_r, skid_v;

  assign i_ready = ~skid_v;   // flop output: no path back from o_ready
  assign o_valid = valid_r;   // flop output
  assign o_data  = data_r;

  wire i_fire = i_valid & i_ready;
  wire o_fire = valid_r & o_ready;

  always @(posedge clk) begin
    if (!rst_n) begin
      valid_r <= 1'b0;
      skid_v  <= 1'b0;
    end else if (skid_v) begin
      // holding an overflow beat; i_ready is low so nothing new arrives
      if (o_fire) begin
        data_r  <= skid_d;
        valid_r <= 1'b1;
        skid_v  <= 1'b0;
      end
    end else begin
      if (i_fire && valid_r && !o_fire) begin
        skid_d <= i_data;      // output busy and not draining -> skid
        skid_v <= 1'b1;
      end else if (i_fire) begin
        data_r  <= i_data;     // output free or draining this cycle
        valid_r <= 1'b1;
      end else if (o_fire) begin
        valid_r <= 1'b0;
      end
    end
  end
endmodule

// ===========================================================================
// applyFn_overlap_wrapper_memreader_shared — N memReader streams on ONE AXI master.
//
// Why this exists
// ---------------
// A `#pragma BOMBYX OVERLAP` wrapper currently exposes one m_axi master per
// collapsed read site (memrd0..4 here, plus the applyFn root port). Each master
// costs a SmartConnect slave port, an AXI ID namespace, and its own share of
// the interconnect. At 8 PEs that is 48 masters for the memReaders alone, which
// is what forces the 16 aggregating SmartConnects.
//
// This module serves all N read sites from a single master, using ARID to
// distinguish them. Downstream that is one slave port instead of N, so the
// interconnect shrinks by ~N x: smaller circuit, more PEs per device, and a
// shorter critical path through the aggregation tree.
//
// Ordering and why RREADY can stay tied high
// ------------------------------------------
// Each stream issues on its own AXI ID, so AXI requires that stream's responses
// to return in order even though the fabric may interleave across IDs — a plain
// FIFO per stream therefore recovers the continuation tag, with no reorder
// buffer and no reply tagging.
//
// Every stream's credit count equals its own reply-FIFO depth, so an accepted
// AR always has a landing slot *in the FIFO its reply will be routed to*. That
// holds no matter which stream's reply arrives next, so RREADY is unconditional
// and the shared R channel is never back-pressured. Without that property one
// slow stream would head-of-line block every other stream on the shared port,
// which is exactly the pathology this module exists to avoid.
//
// Mixed element widths
// --------------------
// The read sites do not agree on element width (32 and 64 bits here), so the
// shared bus is the widest and narrower streams issue narrow reads (ARSIZE <
// bus width). AXI returns a narrow read on the byte lanes selected by the
// address, so the low address bits are carried alongside the continuation tag
// and used to pick the element out of the bus word on the way out.
//
// Per-stream widths arrive as packed parameter vectors because Verilog-2001 has
// no array parameters: field i of each vector describes stream i.
// ===========================================================================

module applyFn_overlap_wrapper_msr_fifo #(
  parameter WIDTH = 64,
  parameter DEPTH = 64        // power of two
) (
  input                  clk,
  input                  rst_n,
  input  [WIDTH-1:0]     in_data,
  input                  in_valid,
  output                 in_ready,
  output [WIDTH-1:0]     out_data,
  output                 out_valid,
  input                  out_ready
);
  localparam AW = $clog2(DEPTH);
  (* ram_style = "block" *)
  reg [WIDTH-1:0] mem [0:DEPTH-1];
  reg [AW:0] wptr, rptr;
  wire empty = (wptr == rptr);
  wire full  = (wptr[AW-1:0] == rptr[AW-1:0]) && (wptr[AW] != rptr[AW]);
  assign in_ready = !full;
  wire push = in_valid && in_ready;

  reg [WIDTH-1:0] outreg;
  reg             outreg_v;
  wire pop = !empty && (!outreg_v || out_ready);
  assign out_valid = outreg_v;
  assign out_data  = outreg;

  always @(posedge clk) begin
    if (push) mem[wptr[AW-1:0]] <= in_data;
    if (pop)  outreg <= mem[rptr[AW-1:0]];
  end

  always @(posedge clk) begin
    if (!rst_n) begin
      wptr <= 0; rptr <= 0; outreg_v <= 1'b0;
    end else begin
      if (push) wptr <= wptr + 1'b1;
      if (pop)  rptr <= rptr + 1'b1;
      if (pop)            outreg_v <= 1'b1;
      else if (out_ready) outreg_v <= 1'b0;
    end
  end
endmodule


module applyFn_overlap_wrapper_memreader_shared #(
  parameter N               = 5,    // number of read-site streams
  parameter TASK_W          = 256,  // taskIn closure width (per stream)
  parameter ARG_W           = 256,  // argDataOut packet width (per stream)
  parameter ADDR_W          = 64,
  parameter BUS_W           = 64,   // shared m_axi data width == max element width
  parameter ID_W            = 3,    // must be >= $clog2(N)
  // Packed per-stream descriptors, 8 bits per field, stream i at [8*i +: 8].
  parameter [8*N-1:0] ELEM_LOG2_VEC = {8'd2, 8'd2, 8'd3, 8'd3, 8'd2},
  parameter [8*N-1:0] ELEM_W_VEC    = {8'd32, 8'd32, 8'd64, 8'd64, 8'd32},
  parameter [8*N-1:0] IDX_W_VEC     = {8'd62, 8'd62, 8'd61, 8'd61, 8'd62},
  // taskIn field offsets (identical across every generated memReader)
  parameter CONT_LSB        = 0,
  parameter CONT_W          = 64,
  parameter BASE_LSB        = 64,
  parameter IDX_LSB         = 128,
  // argDataOut field offsets
  parameter PKT_ADDR_LSB    = 0,    // echoes taskIn._cont
  parameter PKT_DATA_LSB    = 64,
  // Outstanding reads per stream == that stream's reply-buffer depth. Power of two.
  parameter OUTSTANDING     = 64,
  // 0: one AXI ID per stream, replies routed by RID -- lets the fabric return
  //    streams out of order relative to each other.
  // 1: every stream issues on ID 0. Responses on one ID are globally in order,
  //    so a single order FIFO recording the issuing stream routes them instead.
  //    Costs cross-stream head-of-line blocking, but presents the interconnect
  //    with a single-threaded master, which some SmartConnect configurations
  //    handle far better than a multi-ID one.
  parameter SINGLE_ID       = 0,
  // Depth of that order FIFO: must cover every stream's credits at once.
  parameter ORDER_DEPTH     = 512,
  // 0: every read is a full bus-width transfer (ARSIZE = log2(BUS_W/8)) at a
  //    bus-aligned address; a narrower stream takes its element out of the
  //    returned word by byte offset, which the reply path already does.
  // 1: narrower streams issue narrow reads (ARSIZE < bus width).
  //    Narrow transfers force SmartConnect down a much slower path, so 0 is the
  //    default and lets SUPPORTS_NARROW_BURST be declared 0 on the port.
  parameter NARROW_READS    = 0
) (
  input                       ap_clk,
  input                       ap_rst_n,

  // ---- N request streams, flattened (stream i occupies field i) -----------
  input  [N*TASK_W-1:0]       taskIn_TDATA,
  input  [N-1:0]              taskIn_TVALID,
  output [N-1:0]              taskIn_TREADY,

  output [N*64-1:0]           argOut_TDATA,
  output [N-1:0]              argOut_TVALID,
  input  [N-1:0]              argOut_TREADY,

  output [N*ARG_W-1:0]        argDataOut_TDATA,
  output [N-1:0]              argDataOut_TVALID,
  input  [N-1:0]              argDataOut_TREADY,

  // ---- one shared m_axi (read-only; write channel present but tied idle) --
  output                      m_axi_gmem_AWVALID,
  input                       m_axi_gmem_AWREADY,
  output [ADDR_W-1:0]         m_axi_gmem_AWADDR,
  output [ID_W-1:0]           m_axi_gmem_AWID,
  output [7:0]                m_axi_gmem_AWLEN,
  output [2:0]                m_axi_gmem_AWSIZE,
  output [1:0]                m_axi_gmem_AWBURST,
  output [1:0]                m_axi_gmem_AWLOCK,
  output [3:0]                m_axi_gmem_AWCACHE,
  output [2:0]                m_axi_gmem_AWPROT,
  output [3:0]                m_axi_gmem_AWQOS,
  output [3:0]                m_axi_gmem_AWREGION,
  output                      m_axi_gmem_AWUSER,
  output                      m_axi_gmem_WVALID,
  input                       m_axi_gmem_WREADY,
  output [BUS_W-1:0]          m_axi_gmem_WDATA,
  output [(BUS_W/8)-1:0]      m_axi_gmem_WSTRB,
  output                      m_axi_gmem_WLAST,
  output [ID_W-1:0]           m_axi_gmem_WID,
  output                      m_axi_gmem_WUSER,
  output                      m_axi_gmem_ARVALID,
  input                       m_axi_gmem_ARREADY,
  output [ADDR_W-1:0]         m_axi_gmem_ARADDR,
  output [ID_W-1:0]           m_axi_gmem_ARID,
  output [7:0]                m_axi_gmem_ARLEN,
  output [2:0]                m_axi_gmem_ARSIZE,
  output [1:0]                m_axi_gmem_ARBURST,
  output [1:0]                m_axi_gmem_ARLOCK,
  output [3:0]                m_axi_gmem_ARCACHE,
  output [2:0]                m_axi_gmem_ARPROT,
  output [3:0]                m_axi_gmem_ARQOS,
  output [3:0]                m_axi_gmem_ARREGION,
  output                      m_axi_gmem_ARUSER,
  input                       m_axi_gmem_RVALID,
  output                      m_axi_gmem_RREADY,
  input  [BUS_W-1:0]          m_axi_gmem_RDATA,
  input                       m_axi_gmem_RLAST,
  input  [ID_W-1:0]           m_axi_gmem_RID,
  input                       m_axi_gmem_RUSER,
  input  [1:0]                m_axi_gmem_RRESP,
  input                       m_axi_gmem_BVALID,
  output                      m_axi_gmem_BREADY,
  input  [1:0]                m_axi_gmem_BRESP,
  input  [ID_W-1:0]           m_axi_gmem_BID,
  input                       m_axi_gmem_BUSER,

  // ---- observability -----------------------------------------------------
  output [31:0]               dbg_ar_grants,
  output [31:0]               dbg_no_credit_stalls
);

  localparam CW       = $clog2(OUTSTANDING+1);
  localparam SEL_W    = (N > 1) ? $clog2(N) : 1;
  localparam LANE_W   = (BUS_W > 8) ? $clog2(BUS_W/8) : 1; // byte-offset bits kept
  localparam BUS_LOG2 = $clog2(BUS_W/8);                   // ARSIZE for a full beat

  // ---- per-stream request decode -----------------------------------------
  wire [ADDR_W-1:0] s_addr   [0:N-1];
  wire [CONT_W-1:0] s_cont   [0:N-1];
  wire [2:0]        s_arsize [0:N-1];
  wire [N-1:0]      s_want;              // has a task AND a credit
  reg  [CW-1:0]     credits  [0:N-1];

  genvar g;
  generate
    for (g = 0; g < N; g = g + 1) begin : gen_req
      localparam integer EL2 = ELEM_LOG2_VEC[8*g +: 8];
      localparam integer IXW = IDX_W_VEC[8*g +: 8];

      wire [TASK_W-1:0] t = taskIn_TDATA[g*TASK_W +: TASK_W];
      wire [ADDR_W-1:0] base = t[BASE_LSB +: ADDR_W];
      wire [IXW-1:0]    idx  = t[IDX_LSB  +: IXW];

      // Byte address: the HLS reader divides by the element size because its
      // m_axi adapter is indexed in user-data words; driving AXI directly we
      // want bytes.
      assign s_addr[g]   = base + ({{(ADDR_W-IXW){1'b0}}, idx} << EL2);
      assign s_cont[g]   = t[CONT_LSB +: CONT_W];
      assign s_arsize[g] = EL2[2:0];
      assign s_want[g]   = taskIn_TVALID[g] && (credits[g] != {CW{1'b0}});
    end
  endgenerate

  // ---- round-robin arbiter over streams that can issue --------------------
  // Rotating priority keeps one hot stream from starving the others on the
  // shared port; that fairness is the whole point of sharing rather than
  // letting a single stream monopolise the master.
  reg  [SEL_W-1:0] rr_ptr;
  reg  [SEL_W-1:0] grant_idx;
  reg              grant_val;

  integer k;
  // One bit wider than an index: rr_ptr + k reaches 2N-2 before the wrap, which
  // would alias back into range if it were truncated to SEL_W bits.
  reg [SEL_W:0] cand;
  always @* begin
    grant_val = 1'b0;
    grant_idx = {SEL_W{1'b0}};
    // Descending, so the lowest k that wants to issue wins: that is rr_ptr
    // first, then rr_ptr+1, ... i.e. rotating priority.
    for (k = N-1; k >= 0; k = k - 1) begin
      cand = {1'b0, rr_ptr} + k[SEL_W:0];
      if (cand >= N[SEL_W:0]) cand = cand - N[SEL_W:0];
      if (s_want[cand[SEL_W-1:0]]) begin
        grant_val = 1'b1;
        grant_idx = cand[SEL_W-1:0];
      end
    end
  end

  wire ar_fire = m_axi_gmem_ARVALID && m_axi_gmem_ARREADY;

  always @(posedge ap_clk) begin
    if (!ap_rst_n) rr_ptr <= {SEL_W{1'b0}};
    else if (ar_fire) begin
      if (grant_idx == (N[SEL_W-1:0] - 1'b1)) rr_ptr <= {SEL_W{1'b0}};
      else                                    rr_ptr <= grant_idx + 1'b1;
    end
  end

  // Full-width mode aligns the address down to the bus word; the byte offset it
  // discards is exactly the `lane` already carried in the continuation FIFO, so
  // the element is still recovered on the way out.
  wire [ADDR_W-1:0] ar_addr_aligned =
      s_addr[grant_idx] & ~((({{(ADDR_W-1){1'b0}}, 1'b1}) << BUS_LOG2) - 1'b1);

  assign m_axi_gmem_ARVALID = grant_val;
  assign m_axi_gmem_ARADDR  = NARROW_READS ? s_addr[grant_idx] : ar_addr_aligned;
  assign m_axi_gmem_ARID    = SINGLE_ID ? {ID_W{1'b0}}
                                        : {{(ID_W-SEL_W){1'b0}}, grant_idx};
  assign m_axi_gmem_ARSIZE  = NARROW_READS ? s_arsize[grant_idx]
                                           : BUS_LOG2[2:0];

  generate
    for (g = 0; g < N; g = g + 1) begin : gen_ready
      assign taskIn_TREADY[g] =
          m_axi_gmem_ARREADY && grant_val && (grant_idx == g[SEL_W-1:0]);
    end
  endgenerate

  // ---- reply routing ------------------------------------------------------
  wire         r_fire  = m_axi_gmem_RVALID && m_axi_gmem_RREADY;
  assign m_axi_gmem_RREADY = 1'b1;   // a credit guaranteed the slot at AR time

  // In SINGLE_ID mode every request rides ID 0, so RID carries no routing
  // information; the order FIFO does instead. One ID means responses arrive in
  // issue order globally, so its head always names the stream the current beat
  // belongs to.
  wire [SEL_W-1:0] order_sel;
  wire             order_valid;
  generate
    if (SINGLE_ID) begin : gen_order_fifo
      applyFn_overlap_wrapper_msr_fifo #(.WIDTH(SEL_W), .DEPTH(ORDER_DEPTH)) u_order_q (
        .clk(ap_clk), .rst_n(ap_rst_n),
        .in_data(grant_idx), .in_valid(ar_fire), .in_ready(),
        .out_data(order_sel), .out_valid(order_valid), .out_ready(r_fire)
      );
    end else begin : gen_no_order_fifo
      assign order_sel   = {SEL_W{1'b0}};
      assign order_valid = 1'b0;
    end
  endgenerate

  wire [SEL_W-1:0] r_sel = SINGLE_ID ? order_sel : m_axi_gmem_RID[SEL_W-1:0];

  wire [N-1:0] out_fire;
  wire [N-1:0] data_q_ready_w;

  generate
    for (g = 0; g < N; g = g + 1) begin : gen_stream
      localparam integer EL2  = ELEM_LOG2_VEC[8*g +: 8];
      localparam integer ELW  = ELEM_W_VEC[8*g +: 8];

      wire fire_i = ar_fire && (grant_idx == g[SEL_W-1:0]);

      // Continuation tag + the address bits needed to pick a narrow read out of
      // the bus word. Pushed at AR, popped when the element is emitted; one ID
      // per stream keeps this strictly in order.
      wire [CONT_W+LANE_W-1:0] cont_q_data;
      wire                     cont_q_valid, cont_q_ready;
      applyFn_overlap_wrapper_msr_fifo #(.WIDTH(CONT_W+LANE_W), .DEPTH(OUTSTANDING)) u_cont_q (
        .clk(ap_clk), .rst_n(ap_rst_n),
        .in_data({s_addr[g][LANE_W-1:0], s_cont[g]}),
        .in_valid(fire_i), .in_ready(cont_q_ready),
        .out_data(cont_q_data), .out_valid(cont_q_valid), .out_ready(out_fire[g])
      );

      wire [BUS_W-1:0] data_q_data;
      wire             data_q_valid, data_q_ready;
      applyFn_overlap_wrapper_msr_fifo #(.WIDTH(BUS_W), .DEPTH(OUTSTANDING)) u_data_q (
        .clk(ap_clk), .rst_n(ap_rst_n),
        .in_data(m_axi_gmem_RDATA),
        .in_valid(r_fire && (r_sel == g[SEL_W-1:0])), .in_ready(data_q_ready),
        .out_data(data_q_data), .out_valid(data_q_valid), .out_ready(out_fire[g])
      );
      assign data_q_ready_w[g] = data_q_ready;

      // Narrow reads land on the byte lanes the address selects, so shift the
      // bus word down by the stored byte offset before taking the element.
      wire [LANE_W-1:0] lane = cont_q_data[CONT_W +: LANE_W];
      wire [BUS_W-1:0]  shifted = data_q_data >> {lane, 3'b000};
      wire [ELW-1:0]    elem = shifted[ELW-1:0];

      reg [ARG_W-1:0] pkt;
      always @* begin
        pkt = {ARG_W{1'b0}};
        pkt[PKT_ADDR_LSB +: CONT_W] = cont_q_data[CONT_W-1:0];
        pkt[PKT_DATA_LSB +: ELW]    = elem;
      end

      assign argDataOut_TDATA[g*ARG_W +: ARG_W] = pkt;
      assign argDataOut_TVALID[g] = data_q_valid && cont_q_valid;
      assign argOut_TDATA[g*64 +: 64] = cont_q_data[CONT_W-1:0];
      assign argOut_TVALID[g] = data_q_valid && cont_q_valid;

      assign out_fire[g] = argDataOut_TVALID[g] && argDataOut_TREADY[g]
                                               && argOut_TREADY[g];

      always @(posedge ap_clk) begin
        if (!ap_rst_n) credits[g] <= OUTSTANDING;
        else credits[g] <= credits[g] - (fire_i ? 1'b1 : 1'b0)
                                      + (out_fire[g] ? 1'b1 : 1'b0);
      end
    end
  endgenerate

  // ---- observability ------------------------------------------------------
  reg [31:0] ar_grants, no_credit_stalls;
  always @(posedge ap_clk) begin
    if (!ap_rst_n) begin
      ar_grants <= 32'd0; no_credit_stalls <= 32'd0;
    end else begin
      if (ar_fire) ar_grants <= ar_grants + 32'd1;
      // A stream had work but no credit and nothing else could issue either.
      if (!grant_val && (|taskIn_TVALID)) no_credit_stalls <= no_credit_stalls + 32'd1;
    end
  end
  assign dbg_ar_grants        = ar_grants;
  assign dbg_no_credit_stalls = no_credit_stalls;

  // ---- constant AXI fields ------------------------------------------------
  assign m_axi_gmem_ARLEN    = 8'd0;              // one beat per task
  assign m_axi_gmem_ARBURST  = 2'b01;             // INCR
  assign m_axi_gmem_ARLOCK   = 2'b00;
  assign m_axi_gmem_ARCACHE  = 4'b0011;
  assign m_axi_gmem_ARPROT   = 3'b000;
  assign m_axi_gmem_ARQOS    = 4'b0000;
  assign m_axi_gmem_ARREGION = 4'b0000;
  assign m_axi_gmem_ARUSER   = 1'b0;

  assign m_axi_gmem_AWVALID  = 1'b0;
  assign m_axi_gmem_AWADDR   = {ADDR_W{1'b0}};
  assign m_axi_gmem_AWID     = {ID_W{1'b0}};
  assign m_axi_gmem_AWLEN    = 8'd0;
  assign m_axi_gmem_AWSIZE   = 3'd0;
  assign m_axi_gmem_AWBURST  = 2'b01;
  assign m_axi_gmem_AWLOCK   = 2'b00;
  assign m_axi_gmem_AWCACHE  = 4'b0011;
  assign m_axi_gmem_AWPROT   = 3'b000;
  assign m_axi_gmem_AWQOS    = 4'b0000;
  assign m_axi_gmem_AWREGION = 4'b0000;
  assign m_axi_gmem_AWUSER   = 1'b0;
  assign m_axi_gmem_WVALID   = 1'b0;
  assign m_axi_gmem_WDATA    = {BUS_W{1'b0}};
  assign m_axi_gmem_WSTRB    = {(BUS_W/8){1'b0}};
  assign m_axi_gmem_WLAST    = 1'b0;
  assign m_axi_gmem_WID      = {ID_W{1'b0}};
  assign m_axi_gmem_WUSER    = 1'b0;
  assign m_axi_gmem_BREADY   = 1'b1;

  // synthesis translate_off
  always @(posedge ap_clk) if (ap_rst_n) begin
    if (r_fire && !data_q_ready_w[r_sel])
      $display("%t applyFn_overlap_wrapper_memreader_shared: reply FIFO overflow on stream %0d (credit bug)",
               $time, r_sel);
    if (r_fire && (r_sel >= N))
      $display("%t applyFn_overlap_wrapper_memreader_shared: reply with out-of-range RID %0d", $time, r_sel);
    // In SINGLE_ID mode routing comes from the order FIFO, so a beat arriving
    // before its head is registered would be misrouted. Read latency is many
    // cycles so this cannot happen in practice -- but it must not pass silently.
    if (SINGLE_ID && r_fire && !order_valid)
      $display("%t applyFn_overlap_wrapper_memreader_shared: R beat with empty order FIFO", $time);
    if (m_axi_gmem_RVALID && m_axi_gmem_RRESP != 2'b00)
      $display("%t applyFn_overlap_wrapper_memreader_shared: RRESP=%b", $time, m_axi_gmem_RRESP);
  end
  // synthesis translate_on

endmodule

module applyFn_overlap_wrapper #(
  parameter STATE_DEPTH     = 64,
  parameter REPLY_DEPTH     = 16,
  parameter EXIT_DEPTH      = 16,
  parameter MEM_ADDR_WIDTH  = 64,
  parameter MEM_ID_WIDTH    = 1,
  parameter MEM_SHARED_ID_WIDTH    = 2,
  parameter MEM_SHARED_DATA_WIDTH  = 64,
  parameter MEM_SHARED_OUTSTANDING = 32,
  parameter MEM_DATA_WIDTH_applyFn = 32,
  parameter MEM_ID_WIDTH_applyFn = 1,
  parameter MEM_DATA_WIDTH_applyFn_reentry0_cont0 = 32,
  parameter MEM_ID_WIDTH_applyFn_reentry0_cont0 = 1,
  parameter MEM_DATA_WIDTH_applyFn_reentry0_cont1 = 32,
  parameter MEM_ID_WIDTH_applyFn_reentry0_cont1 = 1
) (
  input                       ap_clk,
  input                       ap_rst_n,
  // Root task closure injected by the host / upstream scheduler.
  input  [511:0]  taskIn_TDATA,
  input                       taskIn_TVALID,
  output                      taskIn_TREADY,
  // Loop result out (exit task -> external continuation).
  output [63:0]               argOut_TDATA,
  output                      argOut_TVALID,
  input                       argOut_TREADY,
  // Shared AXI4 memory master for all 3 read site(s).
  output m_axi_gmem_shared_AWVALID,
  input  m_axi_gmem_shared_AWREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_shared_AWADDR,
  output [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_AWID,
  output [7:0] m_axi_gmem_shared_AWLEN,
  output [2:0] m_axi_gmem_shared_AWSIZE,
  output [1:0] m_axi_gmem_shared_AWBURST,
  output [1:0] m_axi_gmem_shared_AWLOCK,
  output [3:0] m_axi_gmem_shared_AWCACHE,
  output [2:0] m_axi_gmem_shared_AWPROT,
  output [3:0] m_axi_gmem_shared_AWQOS,
  output [3:0] m_axi_gmem_shared_AWREGION,
  output m_axi_gmem_shared_AWUSER,
  output m_axi_gmem_shared_WVALID,
  input  m_axi_gmem_shared_WREADY,
  output [MEM_SHARED_DATA_WIDTH-1:0] m_axi_gmem_shared_WDATA,
  output [(MEM_SHARED_DATA_WIDTH/8)-1:0] m_axi_gmem_shared_WSTRB,
  output m_axi_gmem_shared_WLAST,
  output [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_WID,
  output m_axi_gmem_shared_WUSER,
  output m_axi_gmem_shared_ARVALID,
  input  m_axi_gmem_shared_ARREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_shared_ARADDR,
  output [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_ARID,
  output [7:0] m_axi_gmem_shared_ARLEN,
  output [2:0] m_axi_gmem_shared_ARSIZE,
  output [1:0] m_axi_gmem_shared_ARBURST,
  output [1:0] m_axi_gmem_shared_ARLOCK,
  output [3:0] m_axi_gmem_shared_ARCACHE,
  output [2:0] m_axi_gmem_shared_ARPROT,
  output [3:0] m_axi_gmem_shared_ARQOS,
  output [3:0] m_axi_gmem_shared_ARREGION,
  output m_axi_gmem_shared_ARUSER,
  input  m_axi_gmem_shared_RVALID,
  output m_axi_gmem_shared_RREADY,
  input  [MEM_SHARED_DATA_WIDTH-1:0] m_axi_gmem_shared_RDATA,
  input  m_axi_gmem_shared_RLAST,
  input  [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_RID,
  input  m_axi_gmem_shared_RUSER,
  input  [1:0] m_axi_gmem_shared_RRESP,
  input  m_axi_gmem_shared_BVALID,
  output m_axi_gmem_shared_BREADY,
  input  [1:0] m_axi_gmem_shared_BRESP,
  input  [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_BID,
  input  m_axi_gmem_shared_BUSER,
  // AXI4 memory master for PE 'applyFn'.
  output m_axi_gmem_applyFn_AWVALID,
  input  m_axi_gmem_applyFn_AWREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_applyFn_AWADDR,
  output [MEM_ID_WIDTH_applyFn-1:0] m_axi_gmem_applyFn_AWID,
  output [7:0] m_axi_gmem_applyFn_AWLEN,
  output [2:0] m_axi_gmem_applyFn_AWSIZE,
  output [1:0] m_axi_gmem_applyFn_AWBURST,
  output [1:0] m_axi_gmem_applyFn_AWLOCK,
  output [3:0] m_axi_gmem_applyFn_AWCACHE,
  output [2:0] m_axi_gmem_applyFn_AWPROT,
  output [3:0] m_axi_gmem_applyFn_AWQOS,
  output [3:0] m_axi_gmem_applyFn_AWREGION,
  output m_axi_gmem_applyFn_AWUSER,
  output m_axi_gmem_applyFn_WVALID,
  input  m_axi_gmem_applyFn_WREADY,
  output [MEM_DATA_WIDTH_applyFn-1:0] m_axi_gmem_applyFn_WDATA,
  output [(MEM_DATA_WIDTH_applyFn/8)-1:0] m_axi_gmem_applyFn_WSTRB,
  output m_axi_gmem_applyFn_WLAST,
  output [MEM_ID_WIDTH_applyFn-1:0] m_axi_gmem_applyFn_WID,
  output m_axi_gmem_applyFn_WUSER,
  output m_axi_gmem_applyFn_ARVALID,
  input  m_axi_gmem_applyFn_ARREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_applyFn_ARADDR,
  output [MEM_ID_WIDTH_applyFn-1:0] m_axi_gmem_applyFn_ARID,
  output [7:0] m_axi_gmem_applyFn_ARLEN,
  output [2:0] m_axi_gmem_applyFn_ARSIZE,
  output [1:0] m_axi_gmem_applyFn_ARBURST,
  output [1:0] m_axi_gmem_applyFn_ARLOCK,
  output [3:0] m_axi_gmem_applyFn_ARCACHE,
  output [2:0] m_axi_gmem_applyFn_ARPROT,
  output [3:0] m_axi_gmem_applyFn_ARQOS,
  output [3:0] m_axi_gmem_applyFn_ARREGION,
  output m_axi_gmem_applyFn_ARUSER,
  input  m_axi_gmem_applyFn_RVALID,
  output m_axi_gmem_applyFn_RREADY,
  input  [MEM_DATA_WIDTH_applyFn-1:0] m_axi_gmem_applyFn_RDATA,
  input  m_axi_gmem_applyFn_RLAST,
  input  [MEM_ID_WIDTH_applyFn-1:0] m_axi_gmem_applyFn_RID,
  input  m_axi_gmem_applyFn_RUSER,
  input  [1:0] m_axi_gmem_applyFn_RRESP,
  input  m_axi_gmem_applyFn_BVALID,
  output m_axi_gmem_applyFn_BREADY,
  input  [1:0] m_axi_gmem_applyFn_BRESP,
  input  [MEM_ID_WIDTH_applyFn-1:0] m_axi_gmem_applyFn_BID,
  input  m_axi_gmem_applyFn_BUSER,
  // AXI4 memory master for PE 'applyFn_reentry0_cont0'.
  output m_axi_gmem_applyFn_reentry0_cont0_AWVALID,
  input  m_axi_gmem_applyFn_reentry0_cont0_AWREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_applyFn_reentry0_cont0_AWADDR,
  output [MEM_ID_WIDTH_applyFn_reentry0_cont0-1:0] m_axi_gmem_applyFn_reentry0_cont0_AWID,
  output [7:0] m_axi_gmem_applyFn_reentry0_cont0_AWLEN,
  output [2:0] m_axi_gmem_applyFn_reentry0_cont0_AWSIZE,
  output [1:0] m_axi_gmem_applyFn_reentry0_cont0_AWBURST,
  output [1:0] m_axi_gmem_applyFn_reentry0_cont0_AWLOCK,
  output [3:0] m_axi_gmem_applyFn_reentry0_cont0_AWCACHE,
  output [2:0] m_axi_gmem_applyFn_reentry0_cont0_AWPROT,
  output [3:0] m_axi_gmem_applyFn_reentry0_cont0_AWQOS,
  output [3:0] m_axi_gmem_applyFn_reentry0_cont0_AWREGION,
  output m_axi_gmem_applyFn_reentry0_cont0_AWUSER,
  output m_axi_gmem_applyFn_reentry0_cont0_WVALID,
  input  m_axi_gmem_applyFn_reentry0_cont0_WREADY,
  output [MEM_DATA_WIDTH_applyFn_reentry0_cont0-1:0] m_axi_gmem_applyFn_reentry0_cont0_WDATA,
  output [(MEM_DATA_WIDTH_applyFn_reentry0_cont0/8)-1:0] m_axi_gmem_applyFn_reentry0_cont0_WSTRB,
  output m_axi_gmem_applyFn_reentry0_cont0_WLAST,
  output [MEM_ID_WIDTH_applyFn_reentry0_cont0-1:0] m_axi_gmem_applyFn_reentry0_cont0_WID,
  output m_axi_gmem_applyFn_reentry0_cont0_WUSER,
  output m_axi_gmem_applyFn_reentry0_cont0_ARVALID,
  input  m_axi_gmem_applyFn_reentry0_cont0_ARREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_applyFn_reentry0_cont0_ARADDR,
  output [MEM_ID_WIDTH_applyFn_reentry0_cont0-1:0] m_axi_gmem_applyFn_reentry0_cont0_ARID,
  output [7:0] m_axi_gmem_applyFn_reentry0_cont0_ARLEN,
  output [2:0] m_axi_gmem_applyFn_reentry0_cont0_ARSIZE,
  output [1:0] m_axi_gmem_applyFn_reentry0_cont0_ARBURST,
  output [1:0] m_axi_gmem_applyFn_reentry0_cont0_ARLOCK,
  output [3:0] m_axi_gmem_applyFn_reentry0_cont0_ARCACHE,
  output [2:0] m_axi_gmem_applyFn_reentry0_cont0_ARPROT,
  output [3:0] m_axi_gmem_applyFn_reentry0_cont0_ARQOS,
  output [3:0] m_axi_gmem_applyFn_reentry0_cont0_ARREGION,
  output m_axi_gmem_applyFn_reentry0_cont0_ARUSER,
  input  m_axi_gmem_applyFn_reentry0_cont0_RVALID,
  output m_axi_gmem_applyFn_reentry0_cont0_RREADY,
  input  [MEM_DATA_WIDTH_applyFn_reentry0_cont0-1:0] m_axi_gmem_applyFn_reentry0_cont0_RDATA,
  input  m_axi_gmem_applyFn_reentry0_cont0_RLAST,
  input  [MEM_ID_WIDTH_applyFn_reentry0_cont0-1:0] m_axi_gmem_applyFn_reentry0_cont0_RID,
  input  m_axi_gmem_applyFn_reentry0_cont0_RUSER,
  input  [1:0] m_axi_gmem_applyFn_reentry0_cont0_RRESP,
  input  m_axi_gmem_applyFn_reentry0_cont0_BVALID,
  output m_axi_gmem_applyFn_reentry0_cont0_BREADY,
  input  [1:0] m_axi_gmem_applyFn_reentry0_cont0_BRESP,
  input  [MEM_ID_WIDTH_applyFn_reentry0_cont0-1:0] m_axi_gmem_applyFn_reentry0_cont0_BID,
  input  m_axi_gmem_applyFn_reentry0_cont0_BUSER,
  // AXI4 memory master for PE 'applyFn_reentry0_cont1'.
  output m_axi_gmem_applyFn_reentry0_cont1_AWVALID,
  input  m_axi_gmem_applyFn_reentry0_cont1_AWREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_applyFn_reentry0_cont1_AWADDR,
  output [MEM_ID_WIDTH_applyFn_reentry0_cont1-1:0] m_axi_gmem_applyFn_reentry0_cont1_AWID,
  output [7:0] m_axi_gmem_applyFn_reentry0_cont1_AWLEN,
  output [2:0] m_axi_gmem_applyFn_reentry0_cont1_AWSIZE,
  output [1:0] m_axi_gmem_applyFn_reentry0_cont1_AWBURST,
  output [1:0] m_axi_gmem_applyFn_reentry0_cont1_AWLOCK,
  output [3:0] m_axi_gmem_applyFn_reentry0_cont1_AWCACHE,
  output [2:0] m_axi_gmem_applyFn_reentry0_cont1_AWPROT,
  output [3:0] m_axi_gmem_applyFn_reentry0_cont1_AWQOS,
  output [3:0] m_axi_gmem_applyFn_reentry0_cont1_AWREGION,
  output m_axi_gmem_applyFn_reentry0_cont1_AWUSER,
  output m_axi_gmem_applyFn_reentry0_cont1_WVALID,
  input  m_axi_gmem_applyFn_reentry0_cont1_WREADY,
  output [MEM_DATA_WIDTH_applyFn_reentry0_cont1-1:0] m_axi_gmem_applyFn_reentry0_cont1_WDATA,
  output [(MEM_DATA_WIDTH_applyFn_reentry0_cont1/8)-1:0] m_axi_gmem_applyFn_reentry0_cont1_WSTRB,
  output m_axi_gmem_applyFn_reentry0_cont1_WLAST,
  output [MEM_ID_WIDTH_applyFn_reentry0_cont1-1:0] m_axi_gmem_applyFn_reentry0_cont1_WID,
  output m_axi_gmem_applyFn_reentry0_cont1_WUSER,
  output m_axi_gmem_applyFn_reentry0_cont1_ARVALID,
  input  m_axi_gmem_applyFn_reentry0_cont1_ARREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_applyFn_reentry0_cont1_ARADDR,
  output [MEM_ID_WIDTH_applyFn_reentry0_cont1-1:0] m_axi_gmem_applyFn_reentry0_cont1_ARID,
  output [7:0] m_axi_gmem_applyFn_reentry0_cont1_ARLEN,
  output [2:0] m_axi_gmem_applyFn_reentry0_cont1_ARSIZE,
  output [1:0] m_axi_gmem_applyFn_reentry0_cont1_ARBURST,
  output [1:0] m_axi_gmem_applyFn_reentry0_cont1_ARLOCK,
  output [3:0] m_axi_gmem_applyFn_reentry0_cont1_ARCACHE,
  output [2:0] m_axi_gmem_applyFn_reentry0_cont1_ARPROT,
  output [3:0] m_axi_gmem_applyFn_reentry0_cont1_ARQOS,
  output [3:0] m_axi_gmem_applyFn_reentry0_cont1_ARREGION,
  output m_axi_gmem_applyFn_reentry0_cont1_ARUSER,
  input  m_axi_gmem_applyFn_reentry0_cont1_RVALID,
  output m_axi_gmem_applyFn_reentry0_cont1_RREADY,
  input  [MEM_DATA_WIDTH_applyFn_reentry0_cont1-1:0] m_axi_gmem_applyFn_reentry0_cont1_RDATA,
  input  m_axi_gmem_applyFn_reentry0_cont1_RLAST,
  input  [MEM_ID_WIDTH_applyFn_reentry0_cont1-1:0] m_axi_gmem_applyFn_reentry0_cont1_RID,
  input  m_axi_gmem_applyFn_reentry0_cont1_RUSER,
  input  [1:0] m_axi_gmem_applyFn_reentry0_cont1_RRESP,
  input  m_axi_gmem_applyFn_reentry0_cont1_BVALID,
  output m_axi_gmem_applyFn_reentry0_cont1_BREADY,
  input  [1:0] m_axi_gmem_applyFn_reentry0_cont1_BRESP,
  input  [MEM_ID_WIDTH_applyFn_reentry0_cont1-1:0] m_axi_gmem_applyFn_reentry0_cont1_BID,
  input  m_axi_gmem_applyFn_reentry0_cont1_BUSER
);

  wire [1023:0] re_in_TDATA;
  wire re_in_TVALID;
  wire re_in_TREADY;
  wire [1023:0] root_out_TDATA;
  wire root_out_TVALID;
  wire root_out_TREADY;
  wire [1023:0] cont_loop_TDATA;
  wire cont_loop_TVALID;
  wire cont_loop_TREADY;
  wire [1023:0] cont_loop_q_TDATA;
  wire cont_loop_q_TVALID;
  wire cont_loop_q_TREADY;
  wire [1023:0] relay_0_TDATA;
  wire relay_0_TVALID;
  wire relay_0_TREADY;
  wire [255:0] re_mem_TDATA;
  wire re_mem_TVALID;
  wire re_mem_TREADY;
  wire [255:0] re_mem_s1_TDATA;
  wire re_mem_s1_TVALID;
  wire re_mem_s1_TREADY;
  wire [63:0] re_exit_TDATA;
  wire re_exit_TVALID;
  wire re_exit_TREADY;
  wire [1023:0] re_state_TDATA;
  wire re_state_TVALID;
  wire re_state_TREADY;
  wire [1023:0] state_q_TDATA;
  wire state_q_TVALID;
  wire state_q_TREADY;
  wire [255:0] mem_data_TDATA;
  wire mem_data_TVALID;
  wire mem_data_TREADY;
  wire [255:0] mem_data_q_TDATA;
  wire mem_data_q_TVALID;
  wire mem_data_q_TREADY;
  wire [63:0] mem_argOut_TDATA;  wire mem_argOut_TVALID;  wire mem_argOut_TREADY;
  wire [255:0] mem_data_s1_TDATA;
  wire mem_data_s1_TVALID;
  wire mem_data_s1_TREADY;
  wire [255:0] mem_data_s1_q_TDATA;
  wire mem_data_s1_q_TVALID;
  wire mem_data_s1_q_TREADY;
  wire [63:0] mem_argOut_s1_TDATA;  wire mem_argOut_s1_TVALID;  wire mem_argOut_s1_TREADY;
  wire [1023:0] cont_in_TDATA;
  wire cont_in_TVALID;
  wire cont_in_TREADY;
  // Round 1: issued by applyFn_reentry0_cont0.
  wire [1023:0] iss_state_1_TDATA;
  wire iss_state_1_TVALID;
  wire iss_state_1_TREADY;
  wire [1023:0] state_q_1_TDATA;
  wire state_q_1_TVALID;
  wire state_q_1_TREADY;
  wire [1023:0] cont_in_1_TDATA;
  wire cont_in_1_TVALID;
  wire cont_in_1_TREADY;
  wire [255:0] iss_mem_1_TDATA;
  wire iss_mem_1_TVALID;
  wire iss_mem_1_TREADY;
  wire [255:0] mem_data_1_TDATA;
  wire mem_data_1_TVALID;
  wire mem_data_1_TREADY;
  wire [255:0] mem_data_1_q_TDATA;
  wire mem_data_1_q_TVALID;
  wire mem_data_1_q_TREADY;
  wire [63:0] mem_argOut_1_TDATA;  wire mem_argOut_1_TVALID;  wire mem_argOut_1_TREADY;
  wire [63:0] exit_applyFn_reentry0_cont0_argOut_TDATA; wire exit_applyFn_reentry0_cont0_argOut_TVALID; wire exit_applyFn_reentry0_cont0_argOut_TREADY;
  wire [63:0] exit_applyFn_reentry0_cont1_argOut_TDATA; wire exit_applyFn_reentry0_cont1_argOut_TVALID; wire exit_applyFn_reentry0_cont1_argOut_TREADY;
  wire [63:0] exit_oneWalkPerNode_cont0_argOut_TDATA; wire exit_oneWalkPerNode_cont0_argOut_TVALID; wire exit_oneWalkPerNode_cont0_argOut_TREADY;

  // ── Inbound skid: registers the scheduler -> PE task stream ─────────────
  wire [511:0] task_in_q_TDATA;
  wire         task_in_q_TVALID;
  wire         task_in_q_TREADY;
  applyFn_overlap_wrapper_mrc_skid #(.WIDTH(512)) u_task_in_skid (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .i_data(taskIn_TDATA), .i_valid(taskIn_TVALID), .i_ready(taskIn_TREADY),
    .o_data(task_in_q_TDATA), .o_valid(task_in_q_TVALID), .o_ready(task_in_q_TREADY)
  );

  // ── Root PE (loop initializer) ───────────────────────────────────────────
  applyFn u_root (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(task_in_q_TDATA), .taskIn_TVALID(task_in_q_TVALID), .taskIn_TREADY(task_in_q_TREADY),
    .taskGlobalOut_applyFn_reentry0_TDATA(root_out_TDATA),
    .taskGlobalOut_applyFn_reentry0_TVALID(root_out_TVALID),
    .taskGlobalOut_applyFn_reentry0_TREADY(root_out_TREADY),
    .m_axi_gmem_AWVALID(m_axi_gmem_applyFn_AWVALID),
    .m_axi_gmem_AWREADY(m_axi_gmem_applyFn_AWREADY),
    .m_axi_gmem_AWADDR(m_axi_gmem_applyFn_AWADDR),
    .m_axi_gmem_AWID(m_axi_gmem_applyFn_AWID),
    .m_axi_gmem_AWLEN(m_axi_gmem_applyFn_AWLEN),
    .m_axi_gmem_AWSIZE(m_axi_gmem_applyFn_AWSIZE),
    .m_axi_gmem_AWBURST(m_axi_gmem_applyFn_AWBURST),
    .m_axi_gmem_AWLOCK(m_axi_gmem_applyFn_AWLOCK),
    .m_axi_gmem_AWCACHE(m_axi_gmem_applyFn_AWCACHE),
    .m_axi_gmem_AWPROT(m_axi_gmem_applyFn_AWPROT),
    .m_axi_gmem_AWQOS(m_axi_gmem_applyFn_AWQOS),
    .m_axi_gmem_AWREGION(m_axi_gmem_applyFn_AWREGION),
    .m_axi_gmem_AWUSER(m_axi_gmem_applyFn_AWUSER),
    .m_axi_gmem_WVALID(m_axi_gmem_applyFn_WVALID),
    .m_axi_gmem_WREADY(m_axi_gmem_applyFn_WREADY),
    .m_axi_gmem_WDATA(m_axi_gmem_applyFn_WDATA),
    .m_axi_gmem_WSTRB(m_axi_gmem_applyFn_WSTRB),
    .m_axi_gmem_WLAST(m_axi_gmem_applyFn_WLAST),
    .m_axi_gmem_WID(m_axi_gmem_applyFn_WID),
    .m_axi_gmem_WUSER(m_axi_gmem_applyFn_WUSER),
    .m_axi_gmem_ARVALID(m_axi_gmem_applyFn_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_applyFn_ARREADY),
    .m_axi_gmem_ARADDR(m_axi_gmem_applyFn_ARADDR),
    .m_axi_gmem_ARID(m_axi_gmem_applyFn_ARID),
    .m_axi_gmem_ARLEN(m_axi_gmem_applyFn_ARLEN),
    .m_axi_gmem_ARSIZE(m_axi_gmem_applyFn_ARSIZE),
    .m_axi_gmem_ARBURST(m_axi_gmem_applyFn_ARBURST),
    .m_axi_gmem_ARLOCK(m_axi_gmem_applyFn_ARLOCK),
    .m_axi_gmem_ARCACHE(m_axi_gmem_applyFn_ARCACHE),
    .m_axi_gmem_ARPROT(m_axi_gmem_applyFn_ARPROT),
    .m_axi_gmem_ARQOS(m_axi_gmem_applyFn_ARQOS),
    .m_axi_gmem_ARREGION(m_axi_gmem_applyFn_ARREGION),
    .m_axi_gmem_ARUSER(m_axi_gmem_applyFn_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_applyFn_RVALID),
    .m_axi_gmem_RREADY(m_axi_gmem_applyFn_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_applyFn_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_applyFn_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_applyFn_RID),
    .m_axi_gmem_RUSER(m_axi_gmem_applyFn_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_applyFn_RRESP),
    .m_axi_gmem_BVALID(m_axi_gmem_applyFn_BVALID),
    .m_axi_gmem_BREADY(m_axi_gmem_applyFn_BREADY),
    .m_axi_gmem_BRESP(m_axi_gmem_applyFn_BRESP),
    .m_axi_gmem_BID(m_axi_gmem_applyFn_BID),
    .m_axi_gmem_BUSER(m_axi_gmem_applyFn_BUSER),
    .s_axi_control_AWVALID(1'b0),
    .s_axi_control_AWADDR(1'b0),
    .s_axi_control_WVALID(1'b0),
    .s_axi_control_WDATA(1'b0),
    .s_axi_control_WSTRB(1'b0),
    .s_axi_control_ARVALID(1'b0),
    .s_axi_control_ARADDR(1'b0),
    .s_axi_control_RREADY(1'b0),
    .s_axi_control_BREADY(1'b0)
  );

  // ── Loopback FIFO (breaks the reentry->...->continuation->reentry cycle) ──
  applyFn_overlap_wrapper_fifo #(.WIDTH(1024), .DEPTH(STATE_DEPTH)) u_loop_fifo (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(cont_loop_TDATA), .in_valid(cont_loop_TVALID), .in_ready(cont_loop_TREADY),
    .out_data(cont_loop_q_TDATA), .out_valid(cont_loop_q_TVALID), .out_ready(cont_loop_q_TREADY)
  );

  // ── Admission control: keep in-flight tasks < buffer depth ───────────────
  localparam MAX_INFLIGHT = STATE_DEPTH - 8;
  localparam IW = $clog2(STATE_DEPTH+1);
  reg  [IW-1:0] inflight;
  wire credit_ok = (inflight < MAX_INFLIGHT[IW-1:0]);
  wire arb_a_ready;
  wire admit_fire = root_out_TVALID && credit_ok && arb_a_ready;
  wire exit_fire  = re_exit_TVALID && re_exit_TREADY;
  assign root_out_TREADY = arb_a_ready && credit_ok;
  always @(posedge ap_clk) begin
    if (!ap_rst_n) inflight <= 0;
    else inflight <= inflight + (admit_fire ? 1'b1 : 1'b0) - (exit_fire ? 1'b1 : 1'b0);
  end

  // ── reentry.taskIn arbiter: initial spawn + continuation loopback ─────────
  applyFn_overlap_wrapper_arb2 #(.WIDTH(1024)) u_re_arb (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .a_data(root_out_TDATA), .a_valid(root_out_TVALID && credit_ok), .a_ready(arb_a_ready),
    .b_data(cont_loop_q_TDATA), .b_valid(cont_loop_q_TVALID), .b_ready(cont_loop_q_TREADY),
    .o_data(re_in_TDATA), .o_valid(re_in_TVALID), .o_ready(re_in_TREADY)
  );

  // ── Reentry PE (condition + issue reads + push state) ────────────────────
  applyFn_reentry0 u_reentry (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(re_in_TDATA), .taskIn_TVALID(re_in_TVALID), .taskIn_TREADY(re_in_TREADY),
    .taskGlobalOut_memrd0_depends_applyFn_reentry0_cont0_TDATA(re_mem_TDATA),
    .taskGlobalOut_memrd0_depends_applyFn_reentry0_cont0_TVALID(re_mem_TVALID),
    .taskGlobalOut_memrd0_depends_applyFn_reentry0_cont0_TREADY(re_mem_TREADY),
    .taskGlobalOut_memrd1_depends_applyFn_reentry0_cont0_TDATA(re_mem_s1_TDATA),
    .taskGlobalOut_memrd1_depends_applyFn_reentry0_cont0_TVALID(re_mem_s1_TVALID),
    .taskGlobalOut_memrd1_depends_applyFn_reentry0_cont0_TREADY(re_mem_s1_TREADY),
    .taskGlobalOut_applyFn_exit0_TDATA(re_exit_TDATA),
    .taskGlobalOut_applyFn_exit0_TVALID(re_exit_TVALID),
    .taskGlobalOut_applyFn_exit0_TREADY(re_exit_TREADY),
    .contStateOut_applyFn_reentry0_cont0_TDATA(re_state_TDATA),
    .contStateOut_applyFn_reentry0_cont0_TVALID(re_state_TVALID),
    .contStateOut_applyFn_reentry0_cont0_TREADY(re_state_TREADY)
  );

  // ── Continuation-state FIFO (holds loop-carried state per iteration) ──────
  applyFn_overlap_wrapper_fifo #(.WIDTH(1024), .DEPTH(STATE_DEPTH)) u_state_fifo (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(re_state_TDATA), .in_valid(re_state_TVALID), .in_ready(re_state_TREADY),
    .out_data(state_q_TDATA), .out_valid(state_q_TVALID), .out_ready(state_q_TREADY)
  );

  // ── Read site for reply field '__bombyx_memrd0': stream re_mem on the shared reader ──
  assign mem_argOut_TREADY = 1'b1; // reply address unused in streaming mode
  applyFn_overlap_wrapper_fifo #(.WIDTH(256), .DEPTH(REPLY_DEPTH)) u_memreader_rq (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(mem_data_TDATA), .in_valid(mem_data_TVALID), .in_ready(mem_data_TREADY),
    .out_data(mem_data_q_TDATA), .out_valid(mem_data_q_TVALID), .out_ready(mem_data_q_TREADY)
  );

  // ── Read site for reply field 'degree': stream re_mem_s1 on the shared reader ──
  assign mem_argOut_s1_TREADY = 1'b1; // reply address unused in streaming mode
  applyFn_overlap_wrapper_fifo #(.WIDTH(256), .DEPTH(REPLY_DEPTH)) u_memreader_s1_rq (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(mem_data_s1_TDATA), .in_valid(mem_data_s1_TVALID), .in_ready(mem_data_s1_TREADY),
    .out_data(mem_data_s1_q_TDATA), .out_valid(mem_data_s1_q_TVALID), .out_ready(mem_data_s1_q_TREADY)
  );

  // ── Merge unit: join 2 parallel reply channel(s) + STATE_FIFO head ──────
  // Each site has its own in-order channel, so the k-th reply of an
  // iteration is the head of channel k. All 2 are consumed in ONE cycle
  // and drive continuation field(s) '__bombyx_memrd0' ... 'degree'.
  reg  [1023:0] outbuf;    // stable joined closure
  reg  outbuf_v;
  wire [63:0] reply_data_0 = mem_data_q_TDATA[127:64];
  wire [63:0] reply_data_1 = mem_data_s1_q_TDATA[127:64];
  reg  [1023:0] joined;
  always @* begin
    joined = state_q_TDATA;
    joined[703:640] = reply_data_0; // __bombyx_memrd0
    joined[607:576] = reply_data_1; // degree
  end
  // Output register is free to load when empty or draining this cycle.
  wire out_ready = !outbuf_v || cont_in_TREADY;
  wire all_replies = mem_data_q_TVALID && mem_data_s1_q_TVALID;
  wire gather    = all_replies && state_q_TVALID && out_ready;
  assign mem_data_q_TREADY = gather;
  assign mem_data_s1_q_TREADY = gather;
  assign state_q_TREADY  = gather;
  assign cont_in_TVALID  = outbuf_v;
  assign cont_in_TDATA   = outbuf;
  always @(posedge ap_clk) begin
    if (!ap_rst_n) begin
      outbuf_v <= 1'b0;
    end else begin
      if (cont_in_TVALID && cont_in_TREADY) outbuf_v <= 1'b0;
      if (gather) begin outbuf <= joined; outbuf_v <= 1'b1; end
    end
  end

  // ── Continuation PE (issues round 1) ───────────────────
  applyFn_reentry0_cont0 u_cont (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(cont_in_TDATA), .taskIn_TVALID(cont_in_TVALID), .taskIn_TREADY(cont_in_TREADY),
    .taskGlobalOut_memrd2_depends_applyFn_reentry0_cont1_TDATA(iss_mem_1_TDATA),
    .taskGlobalOut_memrd2_depends_applyFn_reentry0_cont1_TVALID(iss_mem_1_TVALID),
    .taskGlobalOut_memrd2_depends_applyFn_reentry0_cont1_TREADY(iss_mem_1_TREADY),
    .contStateOut_applyFn_reentry0_cont1_TDATA(iss_state_1_TDATA),
    .contStateOut_applyFn_reentry0_cont1_TVALID(iss_state_1_TVALID),
    .contStateOut_applyFn_reentry0_cont1_TREADY(iss_state_1_TREADY),
    .m_axi_gmem_AWVALID(m_axi_gmem_applyFn_reentry0_cont0_AWVALID),
    .m_axi_gmem_AWREADY(m_axi_gmem_applyFn_reentry0_cont0_AWREADY),
    .m_axi_gmem_AWADDR(m_axi_gmem_applyFn_reentry0_cont0_AWADDR),
    .m_axi_gmem_AWID(m_axi_gmem_applyFn_reentry0_cont0_AWID),
    .m_axi_gmem_AWLEN(m_axi_gmem_applyFn_reentry0_cont0_AWLEN),
    .m_axi_gmem_AWSIZE(m_axi_gmem_applyFn_reentry0_cont0_AWSIZE),
    .m_axi_gmem_AWBURST(m_axi_gmem_applyFn_reentry0_cont0_AWBURST),
    .m_axi_gmem_AWLOCK(m_axi_gmem_applyFn_reentry0_cont0_AWLOCK),
    .m_axi_gmem_AWCACHE(m_axi_gmem_applyFn_reentry0_cont0_AWCACHE),
    .m_axi_gmem_AWPROT(m_axi_gmem_applyFn_reentry0_cont0_AWPROT),
    .m_axi_gmem_AWQOS(m_axi_gmem_applyFn_reentry0_cont0_AWQOS),
    .m_axi_gmem_AWREGION(m_axi_gmem_applyFn_reentry0_cont0_AWREGION),
    .m_axi_gmem_AWUSER(m_axi_gmem_applyFn_reentry0_cont0_AWUSER),
    .m_axi_gmem_WVALID(m_axi_gmem_applyFn_reentry0_cont0_WVALID),
    .m_axi_gmem_WREADY(m_axi_gmem_applyFn_reentry0_cont0_WREADY),
    .m_axi_gmem_WDATA(m_axi_gmem_applyFn_reentry0_cont0_WDATA),
    .m_axi_gmem_WSTRB(m_axi_gmem_applyFn_reentry0_cont0_WSTRB),
    .m_axi_gmem_WLAST(m_axi_gmem_applyFn_reentry0_cont0_WLAST),
    .m_axi_gmem_WID(m_axi_gmem_applyFn_reentry0_cont0_WID),
    .m_axi_gmem_WUSER(m_axi_gmem_applyFn_reentry0_cont0_WUSER),
    .m_axi_gmem_ARVALID(m_axi_gmem_applyFn_reentry0_cont0_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_applyFn_reentry0_cont0_ARREADY),
    .m_axi_gmem_ARADDR(m_axi_gmem_applyFn_reentry0_cont0_ARADDR),
    .m_axi_gmem_ARID(m_axi_gmem_applyFn_reentry0_cont0_ARID),
    .m_axi_gmem_ARLEN(m_axi_gmem_applyFn_reentry0_cont0_ARLEN),
    .m_axi_gmem_ARSIZE(m_axi_gmem_applyFn_reentry0_cont0_ARSIZE),
    .m_axi_gmem_ARBURST(m_axi_gmem_applyFn_reentry0_cont0_ARBURST),
    .m_axi_gmem_ARLOCK(m_axi_gmem_applyFn_reentry0_cont0_ARLOCK),
    .m_axi_gmem_ARCACHE(m_axi_gmem_applyFn_reentry0_cont0_ARCACHE),
    .m_axi_gmem_ARPROT(m_axi_gmem_applyFn_reentry0_cont0_ARPROT),
    .m_axi_gmem_ARQOS(m_axi_gmem_applyFn_reentry0_cont0_ARQOS),
    .m_axi_gmem_ARREGION(m_axi_gmem_applyFn_reentry0_cont0_ARREGION),
    .m_axi_gmem_ARUSER(m_axi_gmem_applyFn_reentry0_cont0_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_applyFn_reentry0_cont0_RVALID),
    .m_axi_gmem_RREADY(m_axi_gmem_applyFn_reentry0_cont0_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_applyFn_reentry0_cont0_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_applyFn_reentry0_cont0_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_applyFn_reentry0_cont0_RID),
    .m_axi_gmem_RUSER(m_axi_gmem_applyFn_reentry0_cont0_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_applyFn_reentry0_cont0_RRESP),
    .m_axi_gmem_BVALID(m_axi_gmem_applyFn_reentry0_cont0_BVALID),
    .m_axi_gmem_BREADY(m_axi_gmem_applyFn_reentry0_cont0_BREADY),
    .m_axi_gmem_BRESP(m_axi_gmem_applyFn_reentry0_cont0_BRESP),
    .m_axi_gmem_BID(m_axi_gmem_applyFn_reentry0_cont0_BID),
    .m_axi_gmem_BUSER(m_axi_gmem_applyFn_reentry0_cont0_BUSER),
    .s_axi_control_AWVALID(1'b0),
    .s_axi_control_AWADDR(1'b0),
    .s_axi_control_WVALID(1'b0),
    .s_axi_control_WDATA(1'b0),
    .s_axi_control_WSTRB(1'b0),
    .s_axi_control_ARVALID(1'b0),
    .s_axi_control_ARADDR(1'b0),
    .s_axi_control_RREADY(1'b0),
    .s_axi_control_BREADY(1'b0)
  );

  // ── Continuation-state FIFO (holds loop-carried state per iteration) ──────
  applyFn_overlap_wrapper_fifo #(.WIDTH(1024), .DEPTH(STATE_DEPTH)) u_state_fifo_1 (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(iss_state_1_TDATA), .in_valid(iss_state_1_TVALID), .in_ready(iss_state_1_TREADY),
    .out_data(state_q_1_TDATA), .out_valid(state_q_1_TVALID), .out_ready(state_q_1_TREADY)
  );

  // ── Read site for reply field 'current': stream iss_mem_1 on the shared reader ──
  assign mem_argOut_1_TREADY = 1'b1; // reply address unused in streaming mode
  applyFn_overlap_wrapper_fifo #(.WIDTH(256), .DEPTH(REPLY_DEPTH)) u_memreader_1_rq (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(mem_data_1_TDATA), .in_valid(mem_data_1_TVALID), .in_ready(mem_data_1_TREADY),
    .out_data(mem_data_1_q_TDATA), .out_valid(mem_data_1_q_TVALID), .out_ready(mem_data_1_q_TREADY)
  );

  // ── Merge unit: join 1 parallel reply channel(s) + STATE_FIFO head ──────
  // Each site has its own in-order channel, so the k-th reply of an
  // iteration is the head of channel k. All 1 are consumed in ONE cycle
  // and drive continuation field(s) 'current'.
  reg  [1023:0] outbuf_1;    // stable joined closure
  reg  outbuf_v_1;
  wire [31:0] reply_data_1_0 = mem_data_1_q_TDATA[95:64];
  reg  [1023:0] joined_1;
  always @* begin
    joined_1 = state_q_1_TDATA;
    joined_1[511:480] = reply_data_1_0; // current
  end
  // Output register is free to load when empty or draining this cycle.
  wire out_ready_1 = !outbuf_v_1 || cont_in_1_TREADY;
  wire all_replies_1 = mem_data_1_q_TVALID;
  wire gather_1    = all_replies_1 && state_q_1_TVALID && out_ready_1;
  assign mem_data_1_q_TREADY = gather_1;
  assign state_q_1_TREADY  = gather_1;
  assign cont_in_1_TVALID  = outbuf_v_1;
  assign cont_in_1_TDATA   = outbuf_1;
  always @(posedge ap_clk) begin
    if (!ap_rst_n) begin
      outbuf_v_1 <= 1'b0;
    end else begin
      if (cont_in_1_TVALID && cont_in_1_TREADY) outbuf_v_1 <= 1'b0;
      if (gather_1) begin outbuf_1 <= joined_1; outbuf_v_1 <= 1'b1; end
    end
  end

  // ── Continuation PE (loop body; hands off to 'applyFn_reentry0_afterif0') ───────────────────
  applyFn_reentry0_cont1 u_cont_1 (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(cont_in_1_TDATA), .taskIn_TVALID(cont_in_1_TVALID), .taskIn_TREADY(cont_in_1_TREADY),
    .taskGlobalOut_applyFn_reentry0_afterif0_TDATA(relay_0_TDATA),
    .taskGlobalOut_applyFn_reentry0_afterif0_TVALID(relay_0_TVALID),
    .taskGlobalOut_applyFn_reentry0_afterif0_TREADY(relay_0_TREADY),
    .m_axi_gmem_AWVALID(m_axi_gmem_applyFn_reentry0_cont1_AWVALID),
    .m_axi_gmem_AWREADY(m_axi_gmem_applyFn_reentry0_cont1_AWREADY),
    .m_axi_gmem_AWADDR(m_axi_gmem_applyFn_reentry0_cont1_AWADDR),
    .m_axi_gmem_AWID(m_axi_gmem_applyFn_reentry0_cont1_AWID),
    .m_axi_gmem_AWLEN(m_axi_gmem_applyFn_reentry0_cont1_AWLEN),
    .m_axi_gmem_AWSIZE(m_axi_gmem_applyFn_reentry0_cont1_AWSIZE),
    .m_axi_gmem_AWBURST(m_axi_gmem_applyFn_reentry0_cont1_AWBURST),
    .m_axi_gmem_AWLOCK(m_axi_gmem_applyFn_reentry0_cont1_AWLOCK),
    .m_axi_gmem_AWCACHE(m_axi_gmem_applyFn_reentry0_cont1_AWCACHE),
    .m_axi_gmem_AWPROT(m_axi_gmem_applyFn_reentry0_cont1_AWPROT),
    .m_axi_gmem_AWQOS(m_axi_gmem_applyFn_reentry0_cont1_AWQOS),
    .m_axi_gmem_AWREGION(m_axi_gmem_applyFn_reentry0_cont1_AWREGION),
    .m_axi_gmem_AWUSER(m_axi_gmem_applyFn_reentry0_cont1_AWUSER),
    .m_axi_gmem_WVALID(m_axi_gmem_applyFn_reentry0_cont1_WVALID),
    .m_axi_gmem_WREADY(m_axi_gmem_applyFn_reentry0_cont1_WREADY),
    .m_axi_gmem_WDATA(m_axi_gmem_applyFn_reentry0_cont1_WDATA),
    .m_axi_gmem_WSTRB(m_axi_gmem_applyFn_reentry0_cont1_WSTRB),
    .m_axi_gmem_WLAST(m_axi_gmem_applyFn_reentry0_cont1_WLAST),
    .m_axi_gmem_WID(m_axi_gmem_applyFn_reentry0_cont1_WID),
    .m_axi_gmem_WUSER(m_axi_gmem_applyFn_reentry0_cont1_WUSER),
    .m_axi_gmem_ARVALID(m_axi_gmem_applyFn_reentry0_cont1_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_applyFn_reentry0_cont1_ARREADY),
    .m_axi_gmem_ARADDR(m_axi_gmem_applyFn_reentry0_cont1_ARADDR),
    .m_axi_gmem_ARID(m_axi_gmem_applyFn_reentry0_cont1_ARID),
    .m_axi_gmem_ARLEN(m_axi_gmem_applyFn_reentry0_cont1_ARLEN),
    .m_axi_gmem_ARSIZE(m_axi_gmem_applyFn_reentry0_cont1_ARSIZE),
    .m_axi_gmem_ARBURST(m_axi_gmem_applyFn_reentry0_cont1_ARBURST),
    .m_axi_gmem_ARLOCK(m_axi_gmem_applyFn_reentry0_cont1_ARLOCK),
    .m_axi_gmem_ARCACHE(m_axi_gmem_applyFn_reentry0_cont1_ARCACHE),
    .m_axi_gmem_ARPROT(m_axi_gmem_applyFn_reentry0_cont1_ARPROT),
    .m_axi_gmem_ARQOS(m_axi_gmem_applyFn_reentry0_cont1_ARQOS),
    .m_axi_gmem_ARREGION(m_axi_gmem_applyFn_reentry0_cont1_ARREGION),
    .m_axi_gmem_ARUSER(m_axi_gmem_applyFn_reentry0_cont1_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_applyFn_reentry0_cont1_RVALID),
    .m_axi_gmem_RREADY(m_axi_gmem_applyFn_reentry0_cont1_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_applyFn_reentry0_cont1_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_applyFn_reentry0_cont1_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_applyFn_reentry0_cont1_RID),
    .m_axi_gmem_RUSER(m_axi_gmem_applyFn_reentry0_cont1_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_applyFn_reentry0_cont1_RRESP),
    .m_axi_gmem_BVALID(m_axi_gmem_applyFn_reentry0_cont1_BVALID),
    .m_axi_gmem_BREADY(m_axi_gmem_applyFn_reentry0_cont1_BREADY),
    .m_axi_gmem_BRESP(m_axi_gmem_applyFn_reentry0_cont1_BRESP),
    .m_axi_gmem_BID(m_axi_gmem_applyFn_reentry0_cont1_BID),
    .m_axi_gmem_BUSER(m_axi_gmem_applyFn_reentry0_cont1_BUSER),
    .s_axi_control_AWVALID(1'b0),
    .s_axi_control_AWADDR(1'b0),
    .s_axi_control_WVALID(1'b0),
    .s_axi_control_WDATA(1'b0),
    .s_axi_control_WSTRB(1'b0),
    .s_axi_control_ARVALID(1'b0),
    .s_axi_control_ARADDR(1'b0),
    .s_axi_control_RREADY(1'b0),
    .s_axi_control_BREADY(1'b0)
  );

  // ── Relay PE 'applyFn_reentry0_afterif0' -> 'applyFn_reentry0' ──
  applyFn_reentry0_afterif0 u_relay_0 (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(relay_0_TDATA), .taskIn_TVALID(relay_0_TVALID), .taskIn_TREADY(relay_0_TREADY),
    .taskGlobalOut_applyFn_reentry0_TDATA(cont_loop_TDATA),
    .taskGlobalOut_applyFn_reentry0_TVALID(cont_loop_TVALID),
    .taskGlobalOut_applyFn_reentry0_TREADY(cont_loop_TREADY)
  );

  // ────────────────────────────────────────────────────────────────────────
  // All 3 read site(s) on one master; ARID = stream index, per-stream
  // credits equal the per-stream reply depth so RREADY stays high and no
  // site can head-of-line block another.
  // ────────────────────────────────────────────────────────────────────────
  applyFn_overlap_wrapper_memreader_shared #(
    .N(3), .TASK_W(256), .ARG_W(256),
    .ADDR_W(MEM_ADDR_WIDTH), .BUS_W(MEM_SHARED_DATA_WIDTH),
    .ID_W(MEM_SHARED_ID_WIDTH),
    .ELEM_LOG2_VEC({8'd2, 8'd3, 8'd3}),
    .ELEM_W_VEC({8'd32, 8'd64, 8'd64}),
    .IDX_W_VEC({8'd62, 8'd61, 8'd61}),
    .CONT_LSB(0), .BASE_LSB(64), .IDX_LSB(128),
    .PKT_ADDR_LSB(0), .PKT_DATA_LSB(64),
    .OUTSTANDING(MEM_SHARED_OUTSTANDING)
  ) u_memreader_shared (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),

    .taskIn_TDATA({iss_mem_1_TDATA, re_mem_s1_TDATA, re_mem_TDATA}),
    .taskIn_TVALID({iss_mem_1_TVALID, re_mem_s1_TVALID, re_mem_TVALID}),
    .taskIn_TREADY({iss_mem_1_TREADY, re_mem_s1_TREADY, re_mem_TREADY}),

    .argOut_TDATA({mem_argOut_1_TDATA, mem_argOut_s1_TDATA, mem_argOut_TDATA}),
    .argOut_TVALID({mem_argOut_1_TVALID, mem_argOut_s1_TVALID, mem_argOut_TVALID}),
    .argOut_TREADY({mem_argOut_1_TREADY, mem_argOut_s1_TREADY, mem_argOut_TREADY}),

    .argDataOut_TDATA({mem_data_1_TDATA, mem_data_s1_TDATA, mem_data_TDATA}),
    .argDataOut_TVALID({mem_data_1_TVALID, mem_data_s1_TVALID, mem_data_TVALID}),
    .argDataOut_TREADY({mem_data_1_TREADY, mem_data_s1_TREADY, mem_data_TREADY}),

    .m_axi_gmem_AWVALID(m_axi_gmem_shared_AWVALID),
    .m_axi_gmem_AWREADY(m_axi_gmem_shared_AWREADY),
    .m_axi_gmem_AWADDR(m_axi_gmem_shared_AWADDR),
    .m_axi_gmem_AWID(m_axi_gmem_shared_AWID),
    .m_axi_gmem_AWLEN(m_axi_gmem_shared_AWLEN),
    .m_axi_gmem_AWSIZE(m_axi_gmem_shared_AWSIZE),
    .m_axi_gmem_AWBURST(m_axi_gmem_shared_AWBURST),
    .m_axi_gmem_AWLOCK(m_axi_gmem_shared_AWLOCK),
    .m_axi_gmem_AWCACHE(m_axi_gmem_shared_AWCACHE),
    .m_axi_gmem_AWPROT(m_axi_gmem_shared_AWPROT),
    .m_axi_gmem_AWQOS(m_axi_gmem_shared_AWQOS),
    .m_axi_gmem_AWREGION(m_axi_gmem_shared_AWREGION),
    .m_axi_gmem_AWUSER(m_axi_gmem_shared_AWUSER),
    .m_axi_gmem_WVALID(m_axi_gmem_shared_WVALID),
    .m_axi_gmem_WREADY(m_axi_gmem_shared_WREADY),
    .m_axi_gmem_WDATA(m_axi_gmem_shared_WDATA),
    .m_axi_gmem_WSTRB(m_axi_gmem_shared_WSTRB),
    .m_axi_gmem_WLAST(m_axi_gmem_shared_WLAST),
    .m_axi_gmem_WID(m_axi_gmem_shared_WID),
    .m_axi_gmem_WUSER(m_axi_gmem_shared_WUSER),
    .m_axi_gmem_ARVALID(m_axi_gmem_shared_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_shared_ARREADY),
    .m_axi_gmem_ARADDR(m_axi_gmem_shared_ARADDR),
    .m_axi_gmem_ARID(m_axi_gmem_shared_ARID),
    .m_axi_gmem_ARLEN(m_axi_gmem_shared_ARLEN),
    .m_axi_gmem_ARSIZE(m_axi_gmem_shared_ARSIZE),
    .m_axi_gmem_ARBURST(m_axi_gmem_shared_ARBURST),
    .m_axi_gmem_ARLOCK(m_axi_gmem_shared_ARLOCK),
    .m_axi_gmem_ARCACHE(m_axi_gmem_shared_ARCACHE),
    .m_axi_gmem_ARPROT(m_axi_gmem_shared_ARPROT),
    .m_axi_gmem_ARQOS(m_axi_gmem_shared_ARQOS),
    .m_axi_gmem_ARREGION(m_axi_gmem_shared_ARREGION),
    .m_axi_gmem_ARUSER(m_axi_gmem_shared_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_shared_RVALID),
    .m_axi_gmem_RREADY(m_axi_gmem_shared_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_shared_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_shared_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_shared_RID),
    .m_axi_gmem_RUSER(m_axi_gmem_shared_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_shared_RRESP),
    .m_axi_gmem_BVALID(m_axi_gmem_shared_BVALID),
    .m_axi_gmem_BREADY(m_axi_gmem_shared_BREADY),
    .m_axi_gmem_BRESP(m_axi_gmem_shared_BRESP),
    .m_axi_gmem_BID(m_axi_gmem_shared_BID),
    .m_axi_gmem_BUSER(m_axi_gmem_shared_BUSER),
    .dbg_ar_grants(), .dbg_no_credit_stalls()
  );

  // ── Exit queue: decouples the merge ring from the exit PE ───────────────
  wire [63:0] re_exit_q_TDATA;
  wire re_exit_q_TVALID;
  wire re_exit_q_TREADY;
  applyFn_overlap_wrapper_fifo #(.WIDTH(64), .DEPTH(EXIT_DEPTH)) u_re_exit_fifo (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(re_exit_TDATA), .in_valid(re_exit_TVALID), .in_ready(re_exit_TREADY),
    .out_data(re_exit_q_TDATA), .out_valid(re_exit_q_TVALID), .out_ready(re_exit_q_TREADY)
  );

  // ── Exit PE (loop termination) ───────────────────────────────────────────
  applyFn_exit0 u_exit (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(re_exit_q_TDATA), .taskIn_TVALID(re_exit_q_TVALID), .taskIn_TREADY(re_exit_q_TREADY),
    .argOut_applyFn_reentry0_cont0_TDATA(exit_applyFn_reentry0_cont0_argOut_TDATA), .argOut_applyFn_reentry0_cont0_TVALID(exit_applyFn_reentry0_cont0_argOut_TVALID), .argOut_applyFn_reentry0_cont0_TREADY(exit_applyFn_reentry0_cont0_argOut_TREADY),
    .argOut_applyFn_reentry0_cont1_TDATA(exit_applyFn_reentry0_cont1_argOut_TDATA), .argOut_applyFn_reentry0_cont1_TVALID(exit_applyFn_reentry0_cont1_argOut_TVALID), .argOut_applyFn_reentry0_cont1_TREADY(exit_applyFn_reentry0_cont1_argOut_TREADY),
    .argOut_oneWalkPerNode_cont0_TDATA(exit_oneWalkPerNode_cont0_argOut_TDATA), .argOut_oneWalkPerNode_cont0_TVALID(exit_oneWalkPerNode_cont0_argOut_TVALID), .argOut_oneWalkPerNode_cont0_TREADY(exit_oneWalkPerNode_cont0_argOut_TREADY)
  );

  // 'applyFn_reentry0_cont0' is internal to the loop (fed by the merge unit); sink the exit's path.
  assign exit_applyFn_reentry0_cont0_argOut_TREADY = 1'b1;
  // 'applyFn_reentry0_cont1' is internal to the loop (fed by the merge unit); sink the exit's path.
  assign exit_applyFn_reentry0_cont1_argOut_TREADY = 1'b1;
  // 'oneWalkPerNode_cont0' is outside the collapsed loop: expose the result.
  // ── Outbound skids: register the PE -> notifier result streams ─────────
  // argOut and argData are independent channels with independent
  // valids (the PE raises them cycles apart), so each is buffered
  // on its own; merging them drops one of the two.
  wire [63:0] exit_oneWalkPerNode_cont0_out_q;
  wire exit_oneWalkPerNode_cont0_out_q_valid;
  wire exit_oneWalkPerNode_cont0_out_q_ready;
  applyFn_overlap_wrapper_mrc_skid #(.WIDTH(64)) u_exit_oneWalkPerNode_cont0_out_skid (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .i_data(exit_oneWalkPerNode_cont0_argOut_TDATA),
    .i_valid(exit_oneWalkPerNode_cont0_argOut_TVALID), .i_ready(exit_oneWalkPerNode_cont0_out_q_ready),
    .o_data(exit_oneWalkPerNode_cont0_out_q), .o_valid(exit_oneWalkPerNode_cont0_out_q_valid),
    .o_ready(argOut_TREADY)
  );
  assign argOut_TDATA  = exit_oneWalkPerNode_cont0_out_q;
  assign argOut_TVALID = exit_oneWalkPerNode_cont0_out_q_valid;
  assign exit_oneWalkPerNode_cont0_argOut_TREADY = exit_oneWalkPerNode_cont0_out_q_ready;

endmodule
