// ===========================================================================
// Generated by bombyx-cc — #pragma BOMBYX OVERLAP Verilog wrapper
// Application : triangleDAEOptimal
//
// In-order streaming continuation delivery. The reentry PE pushes each
// iteration's continuation state onto STATE_FIFO and issues 2 memory
// read(s); the single in-order memReader reply channel is gathered 2 at a
// time and merged with the head of STATE_FIFO to drive the continuation PE.
//
// PE AXI-Stream ports follow the Vitis HLS convention: for an `axis` port
// `p`, the RTL exposes p_TDATA / p_TVALID / p_TREADY, plus ap_clk / ap_rst_n.
//
// External interface (everything not internal to the collapsed tasks):
//   * taskIn_*  — root task closure in (== root PE's taskIn)
//   * argOut_*  — loop completion out (== exit PE's argOut)
//   * m_axi_gmem_shared_* — ONE AXI4 memory master serving every read site
//     (ARID = site index), via the shared context-cached reader below
//   * m_axi_gmem_<pe>_* — one AXI4 memory master per remaining
//     memory-accessing PE (inline loads/stores), passed straight through
//     (Vitis default bundle name `gmem`). The per-PE s_axi_control offset
//     slave is tied idle (offset 0).
// ===========================================================================

module countIntersections_overlap_wrapper_fifo #(
  parameter WIDTH = 32,
  parameter DEPTH = 512
) (
  input                  clk,
  input                  rst_n,
  input  [WIDTH-1:0]     in_data,
  input                  in_valid,
  output                 in_ready,
  output [WIDTH-1:0]     out_data,
  output                 out_valid,
  input                  out_ready
);
  localparam AW = $clog2(DEPTH); // DEPTH must be a power of two
  (* ram_style = "block" *)
  reg [WIDTH-1:0] mem [0:DEPTH-1];
  reg [AW:0] wptr, rptr;
  wire ram_empty = (wptr == rptr);
  wire full      = (wptr[AW-1:0] == rptr[AW-1:0]) && (wptr[AW] != rptr[AW]);
  assign in_ready = !full;
  wire push = in_valid && in_ready;

  // Output register: holds the head so the RAM's registered read is hidden.
  reg [WIDTH-1:0] outreg;
  reg             outreg_v;
  // Refill whenever the array has data and the output register is free.
  // Gating on !ram_empty also guarantees the read address never equals a
  // write address in the same cycle, so there is no read/write collision.
  wire pop = !ram_empty && (!outreg_v || out_ready);
  assign out_valid = outreg_v;
  assign out_data  = outreg;

  // Storage: no reset, so this infers a block RAM cleanly.
  always @(posedge clk) begin
    if (push) mem[wptr[AW-1:0]] <= in_data;
    if (pop)  outreg <= mem[rptr[AW-1:0]];
  end

  always @(posedge clk) begin
    if (!rst_n) begin
      wptr <= 0; rptr <= 0; outreg_v <= 1'b0;
    end else begin
      if (push) wptr <= wptr + 1'b1;
      if (pop)  rptr <= rptr + 1'b1;
      if (pop)            outreg_v <= 1'b1;
      else if (out_ready) outreg_v <= 1'b0;
    end
  end
endmodule

module countIntersections_overlap_wrapper_arb2 #(parameter WIDTH = 32) (
  input               clk,
  input               rst_n,
  input  [WIDTH-1:0]  a_data,  input a_valid,  output a_ready,
  input  [WIDTH-1:0]  b_data,  input b_valid,  output b_ready,
  output [WIDTH-1:0]  o_data,  output o_valid, input  o_ready
);
  reg sel; // 0: prefer a, 1: prefer b
  wire pick_a = a_valid && (!b_valid || sel == 1'b0);
  assign o_valid = a_valid || b_valid;
  assign o_data  = pick_a ? a_data : b_data;
  assign a_ready = pick_a && o_ready;
  assign b_ready = !pick_a && o_valid && o_ready;
  always @(posedge clk) if (!rst_n) sel <= 0;
    else if (o_valid && o_ready) sel <= pick_a ? 1'b1 : 1'b0;
endmodule

// ===========================================================================
// countIntersections_overlap_wrapper_memreader_cached — shared-port mem reader with a per-context line cache.
//
// Same shared-master idea as bombyx_mem_reader_shared (N read sites, one AXI
// master, ARID selects the stream), plus a private cache line per resident
// context in front of each stream.
//
// The context is allocated by the wrapper's admission control (a free queue of
// IDs replacing the in-flight counter), held for the whole residency of a merge
// loop, and returned at exit. It therefore identifies the loop, is dense
// (0..NUM_CTX-1), and carries no task data. That makes cache conflicts
// impossible by construction: a loop owns one entry, evicts only itself, and
// only when it advances past the line.
//
// Ordering — the reason for the completion queue
// ----------------------------------------------
// The wrapper's merge unit pairs the k-th reply of a stream with the k-th entry
// of that stream's state FIFO. A cache hit that returned immediately while an
// older miss was still outstanding would reorder replies and silently corrupt
// results. So every request — hit or miss — takes a slot in a per-stream
// in-order completion queue; a hit fills its slot at once, a miss when its R
// beat lands, and only the head is ever emitted.
//
// Misses of one stream all ride that stream's own ARID, so they return in
// order; a FIFO of slot indices therefore routes each R beat to the right slot
// with no searching.
//
// The bus is one line wide (256 bits), so a fill is a single beat and matches
// the RAMA/HBM width. A 32-bit element is taken from the line by byte offset.
// ===========================================================================

module countIntersections_overlap_wrapper_mrc_fifo #(
  parameter WIDTH = 64,
  parameter DEPTH = 64
) (
  input                  clk,
  input                  rst_n,
  input  [WIDTH-1:0]     in_data,
  input                  in_valid,
  output                 in_ready,
  output [WIDTH-1:0]     out_data,
  output                 out_valid,
  input                  out_ready
);
  localparam AW = $clog2(DEPTH);
  reg [WIDTH-1:0] mem [0:DEPTH-1];
  reg [AW:0] wptr, rptr;
  wire empty = (wptr == rptr);
  wire full  = (wptr[AW-1:0] == rptr[AW-1:0]) && (wptr[AW] != rptr[AW]);
  assign in_ready  = !full;
  assign out_valid = !empty;
  assign out_data  = mem[rptr[AW-1:0]];
  always @(posedge clk) if (in_valid && in_ready) mem[wptr[AW-1:0]] <= in_data;
  always @(posedge clk) begin
    if (!rst_n) begin wptr <= 0; rptr <= 0; end
    else begin
      if (in_valid  && in_ready)  wptr <= wptr + 1'b1;
      if (out_valid && out_ready) rptr <= rptr + 1'b1;
    end
  end
endmodule


module countIntersections_overlap_wrapper_memreader_cached #(
  parameter N               = 5,
  parameter TASK_W          = 256,
  parameter ARG_W           = 256,
  parameter ADDR_W          = 64,
  parameter BUS_W           = 256,  // one line per beat
  parameter ID_W            = 3,
  parameter NUM_CTX         = 64,   // == wrapper's MAX_INFLIGHT_l1
  parameter CTX_W           = 6,
  parameter [8*N-1:0] ELEM_LOG2_VEC = {8'd2, 8'd2, 8'd3, 8'd3, 8'd2},
  parameter [8*N-1:0] ELEM_W_VEC    = {8'd32, 8'd32, 8'd64, 8'd64, 8'd32},
  parameter [8*N-1:0] IDX_W_VEC     = {8'd62, 8'd62, 8'd61, 8'd61, 8'd62},
  // per-stream cache enable: only the merge-loop sites are worth lines
  parameter [N-1:0]   CACHE_EN      = 5'b11000,
  parameter CONT_LSB        = 0,
  parameter CONT_W          = 64,
  parameter BASE_LSB        = 64,
  parameter IDX_LSB         = 128,
  parameter PKT_ADDR_LSB    = 0,
  parameter PKT_DATA_LSB    = 64,
  parameter OUTSTANDING     = 64,   // AXI credits per stream
  parameter CQ_DEPTH        = 128   // completion-queue slots per stream
) (
  input                       ap_clk,
  input                       ap_rst_n,

  input  [N*TASK_W-1:0]       taskIn_TDATA,
  input  [N-1:0]              taskIn_TVALID,
  output [N-1:0]              taskIn_TREADY,
  // context that owns each request, valid with taskIn
  input  [N*CTX_W-1:0]        taskIn_CTX,

  output [N*64-1:0]           argOut_TDATA,
  output [N-1:0]              argOut_TVALID,
  input  [N-1:0]              argOut_TREADY,

  output [N*ARG_W-1:0]        argDataOut_TDATA,
  output [N-1:0]              argDataOut_TVALID,
  input  [N-1:0]              argDataOut_TREADY,

  output                      m_axi_gmem_AWVALID,
  input                       m_axi_gmem_AWREADY,
  output [ADDR_W-1:0]         m_axi_gmem_AWADDR,
  output [ID_W-1:0]           m_axi_gmem_AWID,
  output [7:0]                m_axi_gmem_AWLEN,
  output [2:0]                m_axi_gmem_AWSIZE,
  output [1:0]                m_axi_gmem_AWBURST,
  output [1:0]                m_axi_gmem_AWLOCK,
  output [3:0]                m_axi_gmem_AWCACHE,
  output [2:0]                m_axi_gmem_AWPROT,
  output [3:0]                m_axi_gmem_AWQOS,
  output [3:0]                m_axi_gmem_AWREGION,
  output                      m_axi_gmem_AWUSER,
  output                      m_axi_gmem_WVALID,
  input                       m_axi_gmem_WREADY,
  output [BUS_W-1:0]          m_axi_gmem_WDATA,
  output [(BUS_W/8)-1:0]      m_axi_gmem_WSTRB,
  output                      m_axi_gmem_WLAST,
  output [ID_W-1:0]           m_axi_gmem_WID,
  output                      m_axi_gmem_WUSER,
  output                      m_axi_gmem_ARVALID,
  input                       m_axi_gmem_ARREADY,
  output [ADDR_W-1:0]         m_axi_gmem_ARADDR,
  output [ID_W-1:0]           m_axi_gmem_ARID,
  output [7:0]                m_axi_gmem_ARLEN,
  output [2:0]                m_axi_gmem_ARSIZE,
  output [1:0]                m_axi_gmem_ARBURST,
  output [1:0]                m_axi_gmem_ARLOCK,
  output [3:0]                m_axi_gmem_ARCACHE,
  output [2:0]                m_axi_gmem_ARPROT,
  output [3:0]                m_axi_gmem_ARQOS,
  output [3:0]                m_axi_gmem_ARREGION,
  output                      m_axi_gmem_ARUSER,
  input                       m_axi_gmem_RVALID,
  output                      m_axi_gmem_RREADY,
  input  [BUS_W-1:0]          m_axi_gmem_RDATA,
  input                       m_axi_gmem_RLAST,
  input  [ID_W-1:0]           m_axi_gmem_RID,
  input                       m_axi_gmem_RUSER,
  input  [1:0]                m_axi_gmem_RRESP,
  input                       m_axi_gmem_BVALID,
  output                      m_axi_gmem_BREADY,
  input  [1:0]                m_axi_gmem_BRESP,
  input  [ID_W-1:0]           m_axi_gmem_BID,
  input                       m_axi_gmem_BUSER,

  output [31:0]               dbg_cache_hits,
  output [31:0]               dbg_cache_misses
);

  localparam SEL_W    = (N > 1) ? $clog2(N) : 1;
  localparam LINE_LOG2 = $clog2(BUS_W/8);      // 5 for a 256-bit line
  localparam LANE_W   = LINE_LOG2;
  localparam TAG_W    = ADDR_W - LINE_LOG2;
  localparam CQ_AW    = $clog2(CQ_DEPTH);
  localparam CW       = $clog2(OUTSTANDING+1);

  // ---- per-stream request decode -----------------------------------------
  wire [ADDR_W-1:0] s_addr [0:N-1];
  wire [CONT_W-1:0] s_cont [0:N-1];
  wire [CTX_W-1:0]  s_ctx  [0:N-1];

  genvar g;
  generate
    for (g = 0; g < N; g = g + 1) begin : gen_dec
      localparam integer EL2 = ELEM_LOG2_VEC[8*g +: 8];
      localparam integer IXW = IDX_W_VEC[8*g +: 8];
      wire [TASK_W-1:0] t = taskIn_TDATA[g*TASK_W +: TASK_W];
      wire [ADDR_W-1:0] base = t[BASE_LSB +: ADDR_W];
      wire [IXW-1:0]    idx  = t[IDX_LSB  +: IXW];
      assign s_addr[g] = base + ({{(ADDR_W-IXW){1'b0}}, idx} << EL2);
      assign s_cont[g] = t[CONT_LSB +: CONT_W];
      assign s_ctx[g]  = taskIn_CTX[g*CTX_W +: CTX_W];
    end
  endgenerate

  // ---- per-stream state ---------------------------------------------------
  wire [N-1:0] cq_full, cq_head_done, out_fire, miss_go, hit_go;
  wire [N-1:0] cred_ok;
  wire [N-1:0] want_ar;                 // wants to issue a miss this cycle

  // arbitration among streams that need the AXI AR channel
  reg  [SEL_W-1:0] rr_ptr, grant_idx;
  reg              grant_val;
  integer k;
  reg [SEL_W:0] cand;
  always @* begin
    grant_val = 1'b0; grant_idx = {SEL_W{1'b0}};
    for (k = N-1; k >= 0; k = k - 1) begin
      cand = {1'b0, rr_ptr} + k[SEL_W:0];
      if (cand >= N[SEL_W:0]) cand = cand - N[SEL_W:0];
      if (want_ar[cand[SEL_W-1:0]]) begin
        grant_val = 1'b1; grant_idx = cand[SEL_W-1:0];
      end
    end
  end

  wire ar_fire = m_axi_gmem_ARVALID && m_axi_gmem_ARREADY;
  always @(posedge ap_clk) begin
    if (!ap_rst_n) rr_ptr <= {SEL_W{1'b0}};
    else if (ar_fire)
      rr_ptr <= (grant_idx == (N[SEL_W-1:0] - 1'b1)) ? {SEL_W{1'b0}}
                                                      : grant_idx + 1'b1;
  end

  wire [ADDR_W-1:0] ar_addr_line =
      s_addr[grant_idx] & ~((({{(ADDR_W-1){1'b0}}, 1'b1}) << LINE_LOG2) - 1'b1);

  assign m_axi_gmem_ARVALID = grant_val;
  assign m_axi_gmem_ARADDR  = ar_addr_line;
  assign m_axi_gmem_ARID    = {{(ID_W-SEL_W){1'b0}}, grant_idx};
  assign m_axi_gmem_ARSIZE  = LINE_LOG2[2:0];

  wire         r_fire = m_axi_gmem_RVALID && m_axi_gmem_RREADY;
  wire [SEL_W-1:0] r_sel = m_axi_gmem_RID[SEL_W-1:0];
  assign m_axi_gmem_RREADY = 1'b1;      // a credit reserved the slot at AR time

  // Count requests, not cycles: several streams can serve one in the same
  // cycle, and only the cached streams are meaningful here.
  reg [31:0] hit_cnt, miss_cnt;
  integer c;
  reg [31:0] hit_n, miss_n;
  always @* begin
    hit_n = 32'd0; miss_n = 32'd0;
    for (c = 0; c < N; c = c + 1) if (CACHE_EN[c]) begin
      if (hit_go[c])  hit_n  = hit_n  + 32'd1;
      if (miss_go[c]) miss_n = miss_n + 32'd1;
    end
  end
  assign dbg_cache_hits   = hit_cnt;
  assign dbg_cache_misses = miss_cnt;
  always @(posedge ap_clk) begin
    if (!ap_rst_n) begin hit_cnt <= 0; miss_cnt <= 0; end
    else begin
      hit_cnt  <= hit_cnt  + hit_n;
      miss_cnt <= miss_cnt + miss_n;
    end
  end

  generate
    for (g = 0; g < N; g = g + 1) begin : gen_stream
      localparam integer ELW = ELEM_W_VEC[8*g +: 8];

      wire [TAG_W-1:0]  req_tag  = s_addr[g][ADDR_W-1:LINE_LOG2];
      wire [LANE_W-1:0] req_lane = s_addr[g][LANE_W-1:0];

      // ---- the private-per-context cache --------------------------------
      wire              c_hit;
      wire [BUS_W-1:0]  c_data;
      wire              fill_en;
      wire [CTX_W-1:0]  fill_ctx;
      wire [TAG_W-1:0]  fill_tag;

      if (CACHE_EN[g]) begin : gen_cache
        countIntersections_overlap_wrapper_ctx_cache #(
          .NUM_CTX(NUM_CTX), .CTX_W(CTX_W), .LINE_W(BUS_W), .TAG_W(TAG_W)
        ) u_cache (
          .clk(ap_clk), .rst_n(ap_rst_n),
          .lu_ctx(s_ctx[g]), .lu_tag(req_tag),
          .lu_hit(c_hit), .lu_data(c_data),
          .fill_en(fill_en), .fill_ctx(fill_ctx),
          .fill_tag(fill_tag), .fill_data(m_axi_gmem_RDATA)
        );
      end else begin : gen_nocache
        assign c_hit  = 1'b0;
        assign c_data = {BUS_W{1'b0}};
      end

      // ---- completion queue (in-order, hits and misses share it) ---------
      reg               cq_done [0:CQ_DEPTH-1];
      reg [BUS_W-1:0]   cq_data [0:CQ_DEPTH-1];
      reg [LANE_W-1:0]  cq_lane [0:CQ_DEPTH-1];
      reg [CONT_W-1:0]  cq_cont [0:CQ_DEPTH-1];
      reg [CQ_AW:0]     cq_wp, cq_rp;

      wire cq_empty = (cq_wp == cq_rp);
      assign cq_full[g] = (cq_wp[CQ_AW-1:0] == cq_rp[CQ_AW-1:0]) &&
                          (cq_wp[CQ_AW] != cq_rp[CQ_AW]);
      assign cq_head_done[g] = !cq_empty && cq_done[cq_rp[CQ_AW-1:0]];

      // credits bound the AXI outstanding of this stream
      reg [CW-1:0] credits;
      assign cred_ok[g] = (credits != {CW{1'b0}});

      // A request is served this cycle if there is a completion slot, and
      // either it hits, or it can win the AR channel with a credit in hand.
      assign want_ar[g] = taskIn_TVALID[g] && !c_hit && !cq_full[g] && cred_ok[g];
      wire ar_mine = ar_fire && (grant_idx == g[SEL_W-1:0]);
      assign hit_go[g]  = taskIn_TVALID[g] && c_hit && !cq_full[g];
      assign miss_go[g] = ar_mine;
      assign taskIn_TREADY[g] = hit_go[g] | ar_mine;

      // miss-ordering FIFO: slot index awaiting an R beat, in issue order
      wire [CQ_AW-1:0] missq_idx;
      wire             missq_valid;
      wire r_mine = r_fire && (r_sel == g[SEL_W-1:0]);
      countIntersections_overlap_wrapper_mrc_fifo #(.WIDTH(CQ_AW+CTX_W+TAG_W), .DEPTH(OUTSTANDING)) u_missq (
        .clk(ap_clk), .rst_n(ap_rst_n),
        .in_data({req_tag, s_ctx[g], cq_wp[CQ_AW-1:0]}),
        .in_valid(ar_mine), .in_ready(),
        .out_data({fill_tag, fill_ctx, missq_idx}),
        .out_valid(missq_valid), .out_ready(r_mine)
      );
      assign fill_en = r_mine;

      integer q;
      always @(posedge ap_clk) begin
        if (!ap_rst_n) begin
          cq_wp <= 0; cq_rp <= 0;
          for (q = 0; q < CQ_DEPTH; q = q + 1) cq_done[q] <= 1'b0;
        end else begin
          if (hit_go[g] || ar_mine) begin
            cq_done[cq_wp[CQ_AW-1:0]] <= hit_go[g];
            cq_data[cq_wp[CQ_AW-1:0]] <= c_data;
            cq_lane[cq_wp[CQ_AW-1:0]] <= req_lane;
            cq_cont[cq_wp[CQ_AW-1:0]] <= s_cont[g];
            cq_wp <= cq_wp + 1'b1;
          end
          if (r_mine && missq_valid) begin
            cq_data[missq_idx] <= m_axi_gmem_RDATA;
            cq_done[missq_idx] <= 1'b1;
          end
          if (out_fire[g]) cq_rp <= cq_rp + 1'b1;
        end
      end

      always @(posedge ap_clk) begin
        if (!ap_rst_n) credits <= OUTSTANDING;
        else credits <= credits - (ar_mine ? 1'b1 : 1'b0) + (r_mine ? 1'b1 : 1'b0);
      end

      // ---- emit ---------------------------------------------------------
      wire [BUS_W-1:0] head_data = cq_data[cq_rp[CQ_AW-1:0]];
      wire [LANE_W-1:0] head_lane = cq_lane[cq_rp[CQ_AW-1:0]];
      wire [BUS_W-1:0] shifted = head_data >> {head_lane, 3'b000};

      reg [ARG_W-1:0] pkt;
      always @* begin
        pkt = {ARG_W{1'b0}};
        pkt[PKT_ADDR_LSB +: CONT_W] = cq_cont[cq_rp[CQ_AW-1:0]];
        pkt[PKT_DATA_LSB +: ELW]    = shifted[ELW-1:0];
      end

      assign argDataOut_TDATA[g*ARG_W +: ARG_W] = pkt;
      assign argDataOut_TVALID[g] = cq_head_done[g];
      assign argOut_TDATA[g*64 +: 64] = cq_cont[cq_rp[CQ_AW-1:0]];
      assign argOut_TVALID[g] = cq_head_done[g];
      assign out_fire[g] = cq_head_done[g] && argDataOut_TREADY[g] && argOut_TREADY[g];
    end
  endgenerate

  // ---- constant AXI fields -----------------------------------------------
  assign m_axi_gmem_ARLEN    = 8'd0;
  assign m_axi_gmem_ARBURST  = 2'b01;
  assign m_axi_gmem_ARLOCK   = 2'b00;
  assign m_axi_gmem_ARCACHE  = 4'b0011;
  assign m_axi_gmem_ARPROT   = 3'b000;
  assign m_axi_gmem_ARQOS    = 4'b0000;
  assign m_axi_gmem_ARREGION = 4'b0000;
  assign m_axi_gmem_ARUSER   = 1'b0;
  assign m_axi_gmem_AWVALID  = 1'b0;
  assign m_axi_gmem_AWADDR   = {ADDR_W{1'b0}};
  assign m_axi_gmem_AWID     = {ID_W{1'b0}};
  assign m_axi_gmem_AWLEN    = 8'd0;
  assign m_axi_gmem_AWSIZE   = 3'd0;
  assign m_axi_gmem_AWBURST  = 2'b01;
  assign m_axi_gmem_AWLOCK   = 2'b00;
  assign m_axi_gmem_AWCACHE  = 4'b0011;
  assign m_axi_gmem_AWPROT   = 3'b000;
  assign m_axi_gmem_AWQOS    = 4'b0000;
  assign m_axi_gmem_AWREGION = 4'b0000;
  assign m_axi_gmem_AWUSER   = 1'b0;
  assign m_axi_gmem_WVALID   = 1'b0;
  assign m_axi_gmem_WDATA    = {BUS_W{1'b0}};
  assign m_axi_gmem_WSTRB    = {(BUS_W/8){1'b0}};
  assign m_axi_gmem_WLAST    = 1'b0;
  assign m_axi_gmem_WID      = {ID_W{1'b0}};
  assign m_axi_gmem_WUSER    = 1'b0;
  assign m_axi_gmem_BREADY   = 1'b1;

endmodule
// ===========================================================================
// countIntersections_overlap_wrapper_ctx_cache — one private line per resident context.
//
// Why not index by address
// ------------------------
// Collisions in this workload are not between addresses within one walk; they
// are between the ~46 concurrent merge loops, each walking an unrelated region.
// An address-indexed cache spends its associativity doing nothing but keeping
// those contexts apart: measured on the real trace, 64 entries/stream gives
// 48.7 % direct-mapped, 75.7 % 8-way, 80.9 % fully associative.
//
// Indexing by context instead makes conflicts impossible by construction. Each
// resident loop owns exactly one entry, evicts only itself, and does so exactly
// when it advances past the line — the moment that line is dead. Measured
// ceiling for that binding on the same trace: **88.2 %** of consecutive
// same-context requests hit the same line, a further 8.2 % hit the next one
// (so a next-line prefetch would reach ~96 %).
//
// Cost is one BRAM read and one comparator: no CAM, no way mux, no replacement
// policy, no priority encoder.
//
// Tags are kept full, so a context ID that is freed and reallocated needs no
// invalidation — the stale entry simply misses, because the new owner's line
// address cannot match. Only a truncated tag would require a valid-bit clear at
// allocation.
//
// Read-only data is assumed (neighbour lists are not written during the merge),
// so there is no coherence obligation.
// ===========================================================================

module countIntersections_overlap_wrapper_ctx_cache #(
  parameter NUM_CTX = 64,                 // entries == number of resident contexts
  parameter CTX_W   = 6,                  // $clog2(NUM_CTX)
  parameter LINE_W  = 256,                // line width in bits
  parameter TAG_W   = 32                  // line-address tag
) (
  input                    clk,
  input                    rst_n,

  // ---- lookup: combinational, same cycle as the request ------------------
  input  [CTX_W-1:0]       lu_ctx,
  input  [TAG_W-1:0]       lu_tag,
  output                   lu_hit,
  output [LINE_W-1:0]      lu_data,

  // ---- fill ---------------------------------------------------------------
  input                    fill_en,
  input  [CTX_W-1:0]       fill_ctx,
  input  [TAG_W-1:0]       fill_tag,
  input  [LINE_W-1:0]      fill_data
);

  reg [TAG_W-1:0]  tags  [0:NUM_CTX-1];
  reg              valid [0:NUM_CTX-1];
  reg [LINE_W-1:0] data  [0:NUM_CTX-1];

  integer i;
  initial begin
    for (i = 0; i < NUM_CTX; i = i + 1) begin
      valid[i] = 1'b0;
      tags[i]  = {TAG_W{1'b0}};
      data[i]  = {LINE_W{1'b0}};
    end
  end

  assign lu_hit  = valid[lu_ctx] && (tags[lu_ctx] == lu_tag);
  assign lu_data = data[lu_ctx];

  always @(posedge clk) begin
    if (!rst_n) begin
      for (i = 0; i < NUM_CTX; i = i + 1) valid[i] <= 1'b0;
    end else if (fill_en) begin
      valid[fill_ctx] <= 1'b1;
      tags [fill_ctx] <= fill_tag;
    end
  end

  always @(posedge clk) if (fill_en) data[fill_ctx] <= fill_data;

endmodule

module countIntersections_overlap_wrapper #(
  parameter STATE_DEPTH     = 128,
  parameter REPLY_DEPTH     = 64,
  parameter MEM_ADDR_WIDTH  = 64,
  parameter MEM_ID_WIDTH    = 1,
  parameter MEM_SHARED_ID_WIDTH    = 1,
  parameter MEM_SHARED_DATA_WIDTH  = 256,
  parameter MEM_SHARED_OUTSTANDING = 64,
  parameter CQ_DEPTH        = 256
) (
  input                       ap_clk,
  input                       ap_rst_n,
  // Root task closure injected by the host / upstream scheduler.
  input  [255:0]  taskIn_TDATA,
  input                       taskIn_TVALID,
  output                      taskIn_TREADY,
  // Loop result out (exit task -> external continuation).
  output [63:0]               argOut_TDATA,
  output                      argOut_TVALID,
  input                       argOut_TREADY,
  output [255:0]              argDataOut_TDATA,
  output                      argDataOut_TVALID,
  input                       argDataOut_TREADY,
  // Shared AXI4 memory master for all 2 read site(s).
  output m_axi_gmem_shared_AWVALID,
  input  m_axi_gmem_shared_AWREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_shared_AWADDR,
  output [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_AWID,
  output [7:0] m_axi_gmem_shared_AWLEN,
  output [2:0] m_axi_gmem_shared_AWSIZE,
  output [1:0] m_axi_gmem_shared_AWBURST,
  output [1:0] m_axi_gmem_shared_AWLOCK,
  output [3:0] m_axi_gmem_shared_AWCACHE,
  output [2:0] m_axi_gmem_shared_AWPROT,
  output [3:0] m_axi_gmem_shared_AWQOS,
  output [3:0] m_axi_gmem_shared_AWREGION,
  output m_axi_gmem_shared_AWUSER,
  output m_axi_gmem_shared_WVALID,
  input  m_axi_gmem_shared_WREADY,
  output [MEM_SHARED_DATA_WIDTH-1:0] m_axi_gmem_shared_WDATA,
  output [(MEM_SHARED_DATA_WIDTH/8)-1:0] m_axi_gmem_shared_WSTRB,
  output m_axi_gmem_shared_WLAST,
  output [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_WID,
  output m_axi_gmem_shared_WUSER,
  output m_axi_gmem_shared_ARVALID,
  input  m_axi_gmem_shared_ARREADY,
  output [MEM_ADDR_WIDTH-1:0] m_axi_gmem_shared_ARADDR,
  output [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_ARID,
  output [7:0] m_axi_gmem_shared_ARLEN,
  output [2:0] m_axi_gmem_shared_ARSIZE,
  output [1:0] m_axi_gmem_shared_ARBURST,
  output [1:0] m_axi_gmem_shared_ARLOCK,
  output [3:0] m_axi_gmem_shared_ARCACHE,
  output [2:0] m_axi_gmem_shared_ARPROT,
  output [3:0] m_axi_gmem_shared_ARQOS,
  output [3:0] m_axi_gmem_shared_ARREGION,
  output m_axi_gmem_shared_ARUSER,
  input  m_axi_gmem_shared_RVALID,
  output m_axi_gmem_shared_RREADY,
  input  [MEM_SHARED_DATA_WIDTH-1:0] m_axi_gmem_shared_RDATA,
  input  m_axi_gmem_shared_RLAST,
  input  [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_RID,
  input  m_axi_gmem_shared_RUSER,
  input  [1:0] m_axi_gmem_shared_RRESP,
  input  m_axi_gmem_shared_BVALID,
  output m_axi_gmem_shared_BREADY,
  input  [1:0] m_axi_gmem_shared_BRESP,
  input  [MEM_SHARED_ID_WIDTH-1:0] m_axi_gmem_shared_BID,
  input  m_axi_gmem_shared_BUSER
);

  // Context-ID space: one private cache line per resident loop.
  // NUM_CTX/CTX_W follow STATE_DEPTH: contexts = MAX_INFLIGHT
  // rounded up to a power of two. Undersizing collapses the hit
  // rate (measured 71.5% at 64 entries vs 2.5% at 32).
  localparam NUM_CTX = STATE_DEPTH;
  localparam CTX_W   = $clog2(STATE_DEPTH);

  wire [511:0] re_in_TDATA;
  wire re_in_TVALID;
  wire re_in_TREADY;
  wire [511:0] root_out_TDATA;
  wire root_out_TVALID;
  wire root_out_TREADY;
  wire [511:0] cont_loop_TDATA;
  wire cont_loop_TVALID;
  wire cont_loop_TREADY;
  wire [511:0] cont_loop_q_TDATA;
  wire cont_loop_q_TVALID;
  wire cont_loop_q_TREADY;
  wire [255:0] re_mem_TDATA;
  wire re_mem_TVALID;
  wire re_mem_TREADY;
  wire [255:0] re_mem_s1_TDATA;
  wire re_mem_s1_TVALID;
  wire re_mem_s1_TREADY;
  wire [127:0] re_exit_TDATA;
  wire re_exit_TVALID;
  wire re_exit_TREADY;
  wire [511:0] re_state_TDATA;
  wire re_state_TVALID;
  wire re_state_TREADY;
  wire [511:0] state_q_TDATA;
  wire state_q_TVALID;
  wire state_q_TREADY;
  wire [255:0] mem_data_TDATA;
  wire mem_data_TVALID;
  wire mem_data_TREADY;
  wire [255:0] mem_data_q_TDATA;
  wire mem_data_q_TVALID;
  wire mem_data_q_TREADY;
  wire [63:0] mem_argOut_TDATA;  wire mem_argOut_TVALID;  wire mem_argOut_TREADY;
  wire [255:0] mem_data_s1_TDATA;
  wire mem_data_s1_TVALID;
  wire mem_data_s1_TREADY;
  wire [255:0] mem_data_s1_q_TDATA;
  wire mem_data_s1_q_TVALID;
  wire mem_data_s1_q_TREADY;
  wire [63:0] mem_argOut_s1_TDATA;  wire mem_argOut_s1_TVALID;  wire mem_argOut_s1_TREADY;
  wire [511:0] cont_in_TDATA;
  wire cont_in_TVALID;
  wire cont_in_TREADY;
  wire [63:0] exit_applyFn_reentry0_cont2_argOut_TDATA; wire exit_applyFn_reentry0_cont2_argOut_TVALID; wire exit_applyFn_reentry0_cont2_argOut_TREADY;
  wire [255:0] exit_applyFn_reentry0_cont2_argData_TDATA; wire exit_applyFn_reentry0_cont2_argData_TVALID; wire exit_applyFn_reentry0_cont2_argData_TREADY;
  wire [63:0] exit_countIntersections_reentry1_cont0_argOut_TDATA; wire exit_countIntersections_reentry1_cont0_argOut_TVALID; wire exit_countIntersections_reentry1_cont0_argOut_TREADY;
  wire [255:0] exit_countIntersections_reentry1_cont0_argData_TDATA; wire exit_countIntersections_reentry1_cont0_argData_TVALID; wire exit_countIntersections_reentry1_cont0_argData_TREADY;

  // ── Root PE (loop initializer) ───────────────────────────────────────────
  countIntersections u_root (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(taskIn_TDATA), .taskIn_TVALID(taskIn_TVALID), .taskIn_TREADY(taskIn_TREADY),
    .taskGlobalOut_countIntersections_reentry1_TDATA(root_out_TDATA),
    .taskGlobalOut_countIntersections_reentry1_TVALID(root_out_TVALID),
    .taskGlobalOut_countIntersections_reentry1_TREADY(root_out_TREADY)
  );

  // ── Context-ID plumbing: declarations (logic follows the rounds) ─────────
  wire [512+CTX_W-1:0] re_in_wide;
  wire [512+CTX_W-1:0] cont_loop_q_wide;
  wire [CTX_W-1:0] ctx_in       = re_in_wide[512 +: CTX_W];
  wire [CTX_W-1:0] ctx_loopback = cont_loop_q_wide[512 +: CTX_W];
  wire [CTX_W-1:0] ctx_retire;                // ID of the loop that is exiting
  wire [CTX_W-1:0] ctxB_head;
  wire [512+CTX_W-1:0] state_q_wide;
  wire [CTX_W-1:0] ctx_state = state_q_wide[512 +: CTX_W];
  wire [CTX_W-1:0] ctxS_head;
  wire [CTX_W-1:0] re_mem_ctx_head;
  wire [CTX_W-1:0] re_mem_s1_ctx_head;
  assign re_in_TDATA = re_in_wide[511:0];
  assign cont_loop_q_TDATA = cont_loop_q_wide[511:0];
  assign state_q_TDATA = state_q_wide[511:0];

  // ── Loopback FIFO (breaks the reentry->...->continuation->reentry cycle) ──
  countIntersections_overlap_wrapper_fifo #(.WIDTH(512+CTX_W), .DEPTH(STATE_DEPTH)) u_loop_fifo (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data({ctxB_head, cont_loop_TDATA}), .in_valid(cont_loop_TVALID), .in_ready(cont_loop_TREADY),
    .out_data(cont_loop_q_wide), .out_valid(cont_loop_q_TVALID), .out_ready(cont_loop_q_TREADY)
  );

  // ── Admission control: keep in-flight tasks < buffer depth ───────────────
  localparam MAX_INFLIGHT = STATE_DEPTH - 8;
  localparam IW = $clog2(STATE_DEPTH+1);
  reg  [IW-1:0] inflight;
  // Free queue of context IDs; the old in-flight bound still applies.
  reg  [CTX_W-1:0] ctxq [0:NUM_CTX-1];
  reg  [IW-1:0] ctxq_wp, ctxq_rp;
  reg              ctxq_init;
  wire             ctxq_empty = (ctxq_wp == ctxq_rp);
  wire [CTX_W-1:0] ctx_alloc  = ctxq[ctxq_rp[IW-1:0] % NUM_CTX];
  wire credit_ok = ctxq_init && !ctxq_empty
                      && (inflight < MAX_INFLIGHT[IW-1:0]);
  wire arb_a_ready;
  wire admit_fire = root_out_TVALID && credit_ok && arb_a_ready;
  wire exit_fire  = re_exit_TVALID && re_exit_TREADY;
  assign root_out_TREADY = arb_a_ready && credit_ok;
  integer ci;
  always @(posedge ap_clk) begin
    if (!ap_rst_n) begin
      inflight <= 0; ctxq_wp <= 0; ctxq_rp <= 0; ctxq_init <= 1'b0;
      for (ci = 0; ci < NUM_CTX; ci = ci + 1) ctxq[ci] <= ci[CTX_W-1:0];
    end else begin
      if (!ctxq_init) begin
        // every ID starts free
        ctxq_wp <= NUM_CTX[IW-1:0];
        ctxq_init <= 1'b1;
      end else begin
        if (admit_fire) ctxq_rp <= ctxq_rp + 1'b1;
        if (exit_fire) begin
          ctxq[ctxq_wp[IW-1:0] % NUM_CTX] <= ctx_retire;
          ctxq_wp <= ctxq_wp + 1'b1;
        end
      end
      inflight <= inflight + (admit_fire ? 1'b1 : 1'b0)
                                 - (exit_fire ? 1'b1 : 1'b0);
    end
  end

  // ── reentry.taskIn arbiter: initial spawn + continuation loopback ─────────
  countIntersections_overlap_wrapper_arb2 #(.WIDTH(512+CTX_W)) u_re_arb (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .a_data({ctx_alloc, root_out_TDATA}),
    .a_valid(root_out_TVALID && credit_ok), .a_ready(arb_a_ready),
    .b_data({ctx_loopback, cont_loop_q_TDATA}),
    .b_valid(cont_loop_q_TVALID), .b_ready(cont_loop_q_TREADY),
    .o_data(re_in_wide), .o_valid(re_in_TVALID), .o_ready(re_in_TREADY)
  );

  // ── Reentry PE (condition + issue reads + push state) ────────────────────
  countIntersections_reentry1 u_reentry (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(re_in_TDATA), .taskIn_TVALID(re_in_TVALID), .taskIn_TREADY(re_in_TREADY),
    .taskGlobalOut_memrd0_depends_countIntersections_reentry1_cont0_TDATA(re_mem_TDATA),
    .taskGlobalOut_memrd0_depends_countIntersections_reentry1_cont0_TVALID(re_mem_TVALID),
    .taskGlobalOut_memrd0_depends_countIntersections_reentry1_cont0_TREADY(re_mem_TREADY),
    .taskGlobalOut_memrd1_depends_countIntersections_reentry1_cont0_TDATA(re_mem_s1_TDATA),
    .taskGlobalOut_memrd1_depends_countIntersections_reentry1_cont0_TVALID(re_mem_s1_TVALID),
    .taskGlobalOut_memrd1_depends_countIntersections_reentry1_cont0_TREADY(re_mem_s1_TREADY),
    .taskGlobalOut_countIntersections_exit1_TDATA(re_exit_TDATA),
    .taskGlobalOut_countIntersections_exit1_TVALID(re_exit_TVALID),
    .taskGlobalOut_countIntersections_exit1_TREADY(re_exit_TREADY),
    .contStateOut_countIntersections_reentry1_cont0_TDATA(re_state_TDATA),
    .contStateOut_countIntersections_reentry1_cont0_TVALID(re_state_TVALID),
    .contStateOut_countIntersections_reentry1_cont0_TREADY(re_state_TREADY)
  );

  // ── Continuation-state FIFO (holds loop-carried state per iteration) ──────
  countIntersections_overlap_wrapper_fifo #(.WIDTH(512+CTX_W), .DEPTH(STATE_DEPTH)) u_state_fifo (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data({ctxS_head, re_state_TDATA}), .in_valid(re_state_TVALID), .in_ready(re_state_TREADY),
    .out_data(state_q_wide), .out_valid(state_q_TVALID), .out_ready(state_q_TREADY)
  );

  // ── Read site for reply field 'a_i': stream re_mem on the shared reader ──
  assign mem_argOut_TREADY = 1'b1; // reply address unused in streaming mode
  countIntersections_overlap_wrapper_fifo #(.WIDTH(256), .DEPTH(REPLY_DEPTH)) u_memreader_rq (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(mem_data_TDATA), .in_valid(mem_data_TVALID), .in_ready(mem_data_TREADY),
    .out_data(mem_data_q_TDATA), .out_valid(mem_data_q_TVALID), .out_ready(mem_data_q_TREADY)
  );

  // ── Read site for reply field 'b_j': stream re_mem_s1 on the shared reader ──
  assign mem_argOut_s1_TREADY = 1'b1; // reply address unused in streaming mode
  countIntersections_overlap_wrapper_fifo #(.WIDTH(256), .DEPTH(REPLY_DEPTH)) u_memreader_s1_rq (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(mem_data_s1_TDATA), .in_valid(mem_data_s1_TVALID), .in_ready(mem_data_s1_TREADY),
    .out_data(mem_data_s1_q_TDATA), .out_valid(mem_data_s1_q_TVALID), .out_ready(mem_data_s1_q_TREADY)
  );

  // ── Merge unit: join 2 parallel reply channel(s) + STATE_FIFO head ──────
  // Each site has its own in-order channel, so the k-th reply of an
  // iteration is the head of channel k. All 2 are consumed in ONE cycle
  // and drive continuation field(s) 'a_i' ... 'b_j'.
  reg  [511:0] outbuf;    // stable joined closure
  reg  outbuf_v;
  wire [31:0] reply_data_0 = mem_data_q_TDATA[95:64];
  wire [31:0] reply_data_1 = mem_data_s1_q_TDATA[95:64];
  reg  [511:0] joined;
  always @* begin
    joined = state_q_TDATA;
    joined[415:384] = reply_data_0; // a_i
    joined[447:416] = reply_data_1; // b_j
  end
  // Output register is free to load when empty or draining this cycle.
  wire out_ready = !outbuf_v || cont_in_TREADY;
  wire all_replies = mem_data_q_TVALID && mem_data_s1_q_TVALID;
  wire gather    = all_replies && state_q_TVALID && out_ready;
  assign mem_data_q_TREADY = gather;
  assign mem_data_s1_q_TREADY = gather;
  assign state_q_TREADY  = gather;
  assign cont_in_TVALID  = outbuf_v;
  assign cont_in_TDATA   = outbuf;
  always @(posedge ap_clk) begin
    if (!ap_rst_n) begin
      outbuf_v <= 1'b0;
    end else begin
      if (cont_in_TVALID && cont_in_TREADY) outbuf_v <= 1'b0;
      if (gather) begin outbuf <= joined; outbuf_v <= 1'b1; end
    end
  end

  // ── Continuation PE (loop body; loops back to reentry) ───────────────────
  countIntersections_reentry1_cont0 u_cont (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(cont_in_TDATA), .taskIn_TVALID(cont_in_TVALID), .taskIn_TREADY(cont_in_TREADY),
    .taskGlobalOut_countIntersections_reentry1_TDATA(cont_loop_TDATA),
    .taskGlobalOut_countIntersections_reentry1_TVALID(cont_loop_TVALID),
    .taskGlobalOut_countIntersections_reentry1_TREADY(cont_loop_TREADY)
  );

  // ── Context-ID plumbing: logic (declarations precede the ring) ──────────
  wire re_in_fire = re_in_TVALID && re_in_TREADY;
  wire cont_loop_fire = cont_loop_TVALID && cont_loop_TREADY;
  wire re_state_fire = re_state_TVALID && re_state_TREADY;
  wire re_mem_fire = re_mem_TVALID && re_mem_TREADY;
  wire re_mem_s1_fire = re_mem_s1_TVALID && re_mem_s1_TREADY;
  assign ctx_retire = ctxS_head;

  countIntersections_overlap_wrapper_fifo #(.WIDTH(CTX_W), .DEPTH(STATE_DEPTH)) u_ctxS (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(ctx_in), .in_valid(re_in_fire), .in_ready(),
    .out_data(ctxS_head), .out_valid(),
    .out_ready(re_state_fire || exit_fire));
  countIntersections_overlap_wrapper_fifo #(.WIDTH(CTX_W), .DEPTH(STATE_DEPTH)) u_ctx_re_mem (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(ctx_in), .in_valid(re_in_fire), .in_ready(),
    .out_data(re_mem_ctx_head), .out_valid(),
    .out_ready(re_mem_fire || exit_fire));
  countIntersections_overlap_wrapper_fifo #(.WIDTH(CTX_W), .DEPTH(STATE_DEPTH)) u_ctx_re_mem_s1 (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(ctx_in), .in_valid(re_in_fire), .in_ready(),
    .out_data(re_mem_s1_ctx_head), .out_valid(),
    .out_ready(re_mem_s1_fire || exit_fire));
  countIntersections_overlap_wrapper_fifo #(.WIDTH(CTX_W), .DEPTH(STATE_DEPTH)) u_ctxB (
    .clk(ap_clk), .rst_n(ap_rst_n),
    .in_data(ctx_state), .in_valid(gather), .in_ready(),
    .out_data(ctxB_head), .out_valid(),
    .out_ready(cont_loop_fire));

  // ────────────────────────────────────────────────────────────────────────
  // All 2 read site(s) on one master; ARID = stream index, per-stream
  // credits equal the per-stream reply depth so RREADY stays high and no
  // site can head-of-line block another. Each cached site holds one private
  // line per resident context; every request, hit or miss, takes a slot in
  // that stream's in-order completion queue, so a hit can never overtake an
  // older miss (the merge unit pairs the k-th reply with the k-th state
  // entry — reordering here silently corrupts results).
  // ────────────────────────────────────────────────────────────────────────
  countIntersections_overlap_wrapper_memreader_cached #(
    .N(2), .TASK_W(256), .ARG_W(256),
    .ADDR_W(MEM_ADDR_WIDTH), .BUS_W(MEM_SHARED_DATA_WIDTH),
    .ID_W(MEM_SHARED_ID_WIDTH),
    .NUM_CTX(NUM_CTX), .CTX_W(CTX_W),
    .ELEM_LOG2_VEC({8'd2, 8'd2}),
    .ELEM_W_VEC({8'd32, 8'd32}),
    .IDX_W_VEC({8'd62, 8'd62}),
    .CACHE_EN(2'b11),
    .CONT_LSB(0), .BASE_LSB(64), .IDX_LSB(128),
    .PKT_ADDR_LSB(0), .PKT_DATA_LSB(64),
    .OUTSTANDING(MEM_SHARED_OUTSTANDING), .CQ_DEPTH(CQ_DEPTH)
  ) u_memreader_cached (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),

    .taskIn_TDATA({re_mem_s1_TDATA, re_mem_TDATA}),
    .taskIn_TVALID({re_mem_s1_TVALID, re_mem_TVALID}),
    .taskIn_TREADY({re_mem_s1_TREADY, re_mem_TREADY}),
    .taskIn_CTX({re_mem_s1_ctx_head, re_mem_ctx_head}),

    .argOut_TDATA({mem_argOut_s1_TDATA, mem_argOut_TDATA}),
    .argOut_TVALID({mem_argOut_s1_TVALID, mem_argOut_TVALID}),
    .argOut_TREADY({mem_argOut_s1_TREADY, mem_argOut_TREADY}),

    .argDataOut_TDATA({mem_data_s1_TDATA, mem_data_TDATA}),
    .argDataOut_TVALID({mem_data_s1_TVALID, mem_data_TVALID}),
    .argDataOut_TREADY({mem_data_s1_TREADY, mem_data_TREADY}),

    .m_axi_gmem_AWVALID(m_axi_gmem_shared_AWVALID),
    .m_axi_gmem_AWREADY(m_axi_gmem_shared_AWREADY),
    .m_axi_gmem_AWADDR(m_axi_gmem_shared_AWADDR),
    .m_axi_gmem_AWID(m_axi_gmem_shared_AWID),
    .m_axi_gmem_AWLEN(m_axi_gmem_shared_AWLEN),
    .m_axi_gmem_AWSIZE(m_axi_gmem_shared_AWSIZE),
    .m_axi_gmem_AWBURST(m_axi_gmem_shared_AWBURST),
    .m_axi_gmem_AWLOCK(m_axi_gmem_shared_AWLOCK),
    .m_axi_gmem_AWCACHE(m_axi_gmem_shared_AWCACHE),
    .m_axi_gmem_AWPROT(m_axi_gmem_shared_AWPROT),
    .m_axi_gmem_AWQOS(m_axi_gmem_shared_AWQOS),
    .m_axi_gmem_AWREGION(m_axi_gmem_shared_AWREGION),
    .m_axi_gmem_AWUSER(m_axi_gmem_shared_AWUSER),
    .m_axi_gmem_WVALID(m_axi_gmem_shared_WVALID),
    .m_axi_gmem_WREADY(m_axi_gmem_shared_WREADY),
    .m_axi_gmem_WDATA(m_axi_gmem_shared_WDATA),
    .m_axi_gmem_WSTRB(m_axi_gmem_shared_WSTRB),
    .m_axi_gmem_WLAST(m_axi_gmem_shared_WLAST),
    .m_axi_gmem_WID(m_axi_gmem_shared_WID),
    .m_axi_gmem_WUSER(m_axi_gmem_shared_WUSER),
    .m_axi_gmem_ARVALID(m_axi_gmem_shared_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_shared_ARREADY),
    .m_axi_gmem_ARADDR(m_axi_gmem_shared_ARADDR),
    .m_axi_gmem_ARID(m_axi_gmem_shared_ARID),
    .m_axi_gmem_ARLEN(m_axi_gmem_shared_ARLEN),
    .m_axi_gmem_ARSIZE(m_axi_gmem_shared_ARSIZE),
    .m_axi_gmem_ARBURST(m_axi_gmem_shared_ARBURST),
    .m_axi_gmem_ARLOCK(m_axi_gmem_shared_ARLOCK),
    .m_axi_gmem_ARCACHE(m_axi_gmem_shared_ARCACHE),
    .m_axi_gmem_ARPROT(m_axi_gmem_shared_ARPROT),
    .m_axi_gmem_ARQOS(m_axi_gmem_shared_ARQOS),
    .m_axi_gmem_ARREGION(m_axi_gmem_shared_ARREGION),
    .m_axi_gmem_ARUSER(m_axi_gmem_shared_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_shared_RVALID),
    .m_axi_gmem_RREADY(m_axi_gmem_shared_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_shared_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_shared_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_shared_RID),
    .m_axi_gmem_RUSER(m_axi_gmem_shared_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_shared_RRESP),
    .m_axi_gmem_BVALID(m_axi_gmem_shared_BVALID),
    .m_axi_gmem_BREADY(m_axi_gmem_shared_BREADY),
    .m_axi_gmem_BRESP(m_axi_gmem_shared_BRESP),
    .m_axi_gmem_BID(m_axi_gmem_shared_BID),
    .m_axi_gmem_BUSER(m_axi_gmem_shared_BUSER),
    .dbg_cache_hits(), .dbg_cache_misses()
  );

  // ── Exit PE (loop termination) ───────────────────────────────────────────
  countIntersections_exit1 u_exit (
    .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
    .taskIn_TDATA(re_exit_TDATA), .taskIn_TVALID(re_exit_TVALID), .taskIn_TREADY(re_exit_TREADY),
    .argOut_applyFn_reentry0_cont2_TDATA(exit_applyFn_reentry0_cont2_argOut_TDATA), .argOut_applyFn_reentry0_cont2_TVALID(exit_applyFn_reentry0_cont2_argOut_TVALID), .argOut_applyFn_reentry0_cont2_TREADY(exit_applyFn_reentry0_cont2_argOut_TREADY),
    .argDataOut_applyFn_reentry0_cont2_TDATA(exit_applyFn_reentry0_cont2_argData_TDATA), .argDataOut_applyFn_reentry0_cont2_TVALID(exit_applyFn_reentry0_cont2_argData_TVALID), .argDataOut_applyFn_reentry0_cont2_TREADY(exit_applyFn_reentry0_cont2_argData_TREADY),
    .argOut_countIntersections_reentry1_cont0_TDATA(exit_countIntersections_reentry1_cont0_argOut_TDATA), .argOut_countIntersections_reentry1_cont0_TVALID(exit_countIntersections_reentry1_cont0_argOut_TVALID), .argOut_countIntersections_reentry1_cont0_TREADY(exit_countIntersections_reentry1_cont0_argOut_TREADY),
    .argDataOut_countIntersections_reentry1_cont0_TDATA(exit_countIntersections_reentry1_cont0_argData_TDATA), .argDataOut_countIntersections_reentry1_cont0_TVALID(exit_countIntersections_reentry1_cont0_argData_TVALID), .argDataOut_countIntersections_reentry1_cont0_TREADY(exit_countIntersections_reentry1_cont0_argData_TREADY)
  );

  // 'applyFn_reentry0_cont2' is outside the collapsed loop: expose the result.
  assign argOut_TDATA  = exit_applyFn_reentry0_cont2_argOut_TDATA;
  assign argOut_TVALID = exit_applyFn_reentry0_cont2_argOut_TVALID;
  assign exit_applyFn_reentry0_cont2_argOut_TREADY = argOut_TREADY;
  assign argDataOut_TDATA  = exit_applyFn_reentry0_cont2_argData_TDATA;
  assign argDataOut_TVALID = exit_applyFn_reentry0_cont2_argData_TVALID;
  assign exit_applyFn_reentry0_cont2_argData_TREADY = argDataOut_TREADY;
  // 'countIntersections_reentry1_cont0' is internal to the loop (fed by the merge unit); sink the exit's path.
  assign exit_countIntersections_reentry1_cont0_argOut_TREADY = 1'b1;
  assign exit_countIntersections_reentry1_cont0_argData_TREADY = 1'b1;

endmodule
