#include "vitis/VitisHLSTclGen.hpp"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"

#include <cmath>
#include <filesystem>
#include <fstream>
#include <string>
#include <system_error>

// ─── FPGA model → Xilinx part string ─────────────────────────────────────────

static std::string fpgaModelToPart(const std::string &Model) {
  if (Model == "ALVEO_U55C")  return "xcu55c-fsvh2892-2L-e";
  if (Model == "ALVEO_U280")  return "xcu280-fsvh2892-2L-e";
  if (Model == "ALVEO_U250")  return "xcu250-figd2104-2L-e";
  if (Model == "ALVEO_U50")   return "xcu50-fsvh2104-2L-e";
  if (Model == "ALVEO_U200")  return "xcu200-fsgd2104-2-e";
  // Fall back: return the model name as-is so the TCL is still useful.
  return Model;
}

// ─── Per-PE TCL file ──────────────────────────────────────────────────────────

void PrintVitisHLSTaskTcl(const std::string &AppName,
                           const std::string &TaskName,
                           bool HasAXI,
                           const std::string &FpgaModel,
                           int FreqMhz,
                           llvm::raw_ostream &Out) {
  std::string Part = fpgaModelToPart(FpgaModel);
  // Format clock period to 4 decimal places (ns).
  char ClockBuf[32];
  std::snprintf(ClockBuf, sizeof(ClockBuf), "%.4f", 1000.0 / FreqMhz);

  Out << "# =============================================================================\n";
  Out << "# Generated by bombyx-cc — Vitis HLS synthesis script\n";
  Out << "# Application : " << AppName << "\n";
  Out << "# Kernel      : " << TaskName << "\n";
  Out << "# Part        : " << Part << "\n";
  Out << "# Clock       : " << FreqMhz << " MHz  (" << ClockBuf << " ns)\n";
  Out << "#\n";
  Out << "# Run from the PE work directory:\n";
  Out << "#   mkdir -p vitis_hls_work/" << TaskName << "\n";
  Out << "#   cd vitis_hls_work/" << TaskName << "\n";
  Out << "#   vitis_hls -f ../../hls_tcl/" << TaskName << ".tcl\n";
  Out << "# =============================================================================\n\n";

  // Use [file dirname [info script]] so the TCL remains relocatable when the
  // output directory is moved.  Sources live one level above hls_tcl/.
  Out << "set script_dir [file normalize [file dirname [info script]]]\n";
  Out << "set src_dir    [file normalize [file join $script_dir \"..\"]]\n\n";

  Out << "# ── Project setup ─────────────────────────────────────────────────────────────\n";
  Out << "open_project -reset " << TaskName << "_proj\n";
  Out << "set_top " << TaskName << "\n\n";

  Out << "# ── Source files ──────────────────────────────────────────────────────────────\n";
  Out << "add_files [file join $src_dir " << AppName << ".cpp]\n";
  Out << "add_files [file join $src_dir " << AppName << "_defs.h]\n\n";

  Out << "# ── Solution configuration ────────────────────────────────────────────────────\n";
  Out << "open_solution -reset \"solution1\" -flow_target vitis\n";
  Out << "set_part {" << Part << "}\n";
  Out << "create_clock -period " << ClockBuf << " -name default\n\n";

  if (HasAXI) {
    Out << "# ── AXI memory interface directives ──────────────────────────────────────────\n";
    Out << "config_interface -m_axi_addr64\n";
    Out << "config_interface -m_axi_num_read_outstanding 32\n";
    Out << "config_interface -m_axi_num_write_outstanding 32\n\n";
  }

  Out << "# ── Synthesis ─────────────────────────────────────────────────────────────────\n";
  Out << "csynth_design\n\n";

  Out << "# ── Teardown ──────────────────────────────────────────────────────────────────\n";
  Out << "close_project\n";
  Out << "exit\n";
}

// ─── Master build script ──────────────────────────────────────────────────────

void PrintVitisHLSArtifacts(const std::string &AppName,
                             const TaskInfosTy &TaskInfos,
                             const std::string &FpgaModel,
                             int FreqMhz,
                             const std::string &OutputDir) {
  namespace fs = std::filesystem;

  // Create hls_tcl/ subdirectory.
  fs::path TclDir = fs::path(OutputDir) / "hls_tcl";
  fs::create_directories(TclDir);

  // Collect non-synthetic task names for the build script.
  std::vector<std::string> KernelNames;

  for (auto &[Task, Info] : TaskInfos) {
    if (Info.IsSynthetic)
      continue;
    KernelNames.push_back(Task->getName());

    fs::path TclPath = TclDir / (Task->getName() + ".tcl");
    std::error_code EC;
    llvm::raw_fd_ostream TclOut(TclPath.string(), EC,
                                llvm::sys::fs::OF_Text);
    if (EC) {
      llvm::errs() << "warning: could not write " << TclPath.string()
                   << ": " << EC.message() << "\n";
      continue;
    }
    PrintVitisHLSTaskTcl(AppName, Task->getName(), Info.HasAXI,
                          FpgaModel, FreqMhz, TclOut);
  }

  // Sort for deterministic script order.
  std::sort(KernelNames.begin(), KernelNames.end());

  // Write build_hls.sh
  fs::path ScriptPath = fs::path(OutputDir) / "build_hls.sh";
  std::error_code EC;
  llvm::raw_fd_ostream Out(ScriptPath.string(), EC, llvm::sys::fs::OF_Text);
  if (EC) {
    llvm::errs() << "warning: could not write build_hls.sh: " << EC.message()
                 << "\n";
    return;
  }

  Out << "#!/usr/bin/env bash\n";
  Out << "# =============================================================================\n";
  Out << "# Generated by bombyx-cc — Vitis HLS multi-PE build script\n";
  Out << "# Application : " << AppName << "\n";
  Out << "# FPGA model  : " << FpgaModel << "\n";
  Out << "# Clock       : " << FreqMhz << " MHz\n";
  Out << "#\n";
  Out << "# Usage:\n";
  Out << "#   ./build_hls.sh [--debug] [-jN | --jobs N]\n";
  Out << "#\n";
  Out << "# Options:\n";
  Out << "#   --debug        Keep intermediate Vitis HLS project directories.\n";
  Out << "#   -jN, --jobs N  Max PEs to synthesise in parallel (default: nproc).\n";
  Out << "#\n";
  Out << "# Requirements:\n";
  Out << "#   vitis_hls must be on PATH.\n";
  Out << "#   Source: source /tools/Xilinx/Vitis_HLS/<version>/settings64.sh\n";
  Out << "#\n";
  Out << "# Output:\n";
  Out << "#   vitis_hls_output/<kernel>/   — synthesised Verilog RTL per PE\n";
  Out << "# =============================================================================\n\n";

  // NOTE: '-e' is intentionally omitted: each PE runs as a backgrounded job and
  // failures are handled explicitly via per-kernel status files (subshell
  // variable updates do not propagate to the parent).
  Out << "set -uo pipefail\n\n";

  Out << "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"\n";
  Out << "WORK_ROOT=\"${SCRIPT_DIR}/vitis_hls_work\"\n";
  Out << "RTL_ROOT=\"${SCRIPT_DIR}/vitis_hls_output\"\n\n";

  Out << "DEBUG=\"\"\n";
  Out << "MAX_JOBS=\"$(nproc 2>/dev/null || echo 4)\"\n";
  Out << "while [[ $# -gt 0 ]]; do\n";
  Out << "    case \"$1\" in\n";
  Out << "        --debug)   DEBUG=\"--debug\"; shift ;;\n";
  Out << "        --jobs)    MAX_JOBS=\"$2\"; shift 2 ;;\n";
  Out << "        --jobs=*)  MAX_JOBS=\"${1#--jobs=}\"; shift ;;\n";
  Out << "        -j*)       MAX_JOBS=\"${1#-j}\"; shift ;;\n";
  Out << "        *)         shift ;;\n";
  Out << "    esac\n";
  Out << "done\n";
  Out << "[[ \"$MAX_JOBS\" =~ ^[0-9]+$ && \"$MAX_JOBS\" -ge 1 ]] || MAX_JOBS=1\n\n";

  Out << "RED='\\033[0;31m'; GREEN='\\033[0;32m'; CYAN='\\033[0;36m'\n";
  Out << "BOLD='\\033[1m'; NC='\\033[0m'\n";
  Out << "info()    { echo -e \"${CYAN}[INFO]${NC}  $*\"; }\n";
  Out << "success() { echo -e \"${GREEN}[OK]${NC}    $*\"; }\n";
  Out << "error()   { echo -e \"${RED}[ERROR]${NC} $*\" >&2; }\n\n";

  Out << "command -v vitis_hls &>/dev/null \\\n";
  Out << "    || { error \"'vitis_hls' not found — source the Vitis HLS settings64.sh first.\"; exit 1; }\n\n";

  Out << "mkdir -p \"$WORK_ROOT\" \"$RTL_ROOT\"\n";
  Out << "STATUS_DIR=\"$(mktemp -d)\"\n";
  Out << "trap 'rm -rf \"$STATUS_DIR\"' EXIT\n\n";

  Out << "KERNELS=(";
  for (size_t i = 0; i < KernelNames.size(); ++i) {
    if (i) Out << " ";
    Out << KernelNames[i];
  }
  Out << ")\n\n";

  // Per-PE build, run as a backgrounded job. stdout/stderr of vitis_hls go to a
  // log file (not the console) so parallel runs do not interleave their output.
  Out << "build_one() {\n";
  Out << "    local KERNEL=\"$1\"\n";
  Out << "    local WORK_DIR=\"${WORK_ROOT}/${KERNEL}\"\n";
  Out << "    local TCL_FILE=\"${SCRIPT_DIR}/hls_tcl/${KERNEL}.tcl\"\n";
  Out << "    mkdir -p \"$WORK_DIR\"\n";
  Out << "    info \"Synthesising PE: ${BOLD}${KERNEL}${NC}\"\n";
  Out << "    if (cd \"$WORK_DIR\" && vitis_hls -f \"$TCL_FILE\" > vitis_hls.log 2>&1); then\n";
  Out << "        local RTL_SRC=\"${WORK_DIR}/${KERNEL}_proj/solution1/syn/verilog\"\n";
  Out << "        if [[ -d \"$RTL_SRC\" ]]; then\n";
  Out << "            mkdir -p \"${RTL_ROOT}/${KERNEL}\"\n";
  Out << "            cp -r \"${RTL_SRC}/.\" \"${RTL_ROOT}/${KERNEL}/\"\n";
  Out << "            success \"${KERNEL} → ${RTL_ROOT}/${KERNEL}/\"\n";
  Out << "            [[ \"$DEBUG\" == \"--debug\" ]] || rm -rf \"$WORK_DIR\"\n";
  Out << "            echo PASS > \"${STATUS_DIR}/${KERNEL}\"\n";
  Out << "        else\n";
  Out << "            error \"${KERNEL}: Verilog not found: ${RTL_SRC}\"\n";
  Out << "            echo FAIL > \"${STATUS_DIR}/${KERNEL}\"\n";
  Out << "        fi\n";
  Out << "    else\n";
  Out << "        error \"${KERNEL} failed. Log: ${WORK_DIR}/vitis_hls.log\"\n";
  Out << "        echo FAIL > \"${STATUS_DIR}/${KERNEL}\"\n";
  Out << "    fi\n";
  Out << "}\n\n";

  Out << "info \"Building ${#KERNELS[@]} PEs with up to ${MAX_JOBS} parallel job(s).\"\n";
  Out << "for KERNEL in \"${KERNELS[@]}\"; do\n";
  Out << "    while (( $(jobs -rp | wc -l) >= MAX_JOBS )); do wait -n; done\n";
  Out << "    build_one \"$KERNEL\" &\n";
  Out << "done\n";
  Out << "wait\n\n";

  Out << "PASS=(); FAIL=()\n";
  Out << "for KERNEL in \"${KERNELS[@]}\"; do\n";
  Out << "    if [[ \"$(cat \"${STATUS_DIR}/${KERNEL}\" 2>/dev/null)\" == \"PASS\" ]]; then\n";
  Out << "        PASS+=(\"$KERNEL\")\n";
  Out << "    else\n";
  Out << "        FAIL+=(\"$KERNEL\")\n";
  Out << "    fi\n";
  Out << "done\n\n";

  Out << "echo -e \"${BOLD}══════════════════ SUMMARY ══════════════════${NC}\"\n";
  Out << "echo -e \"  Total  : ${#KERNELS[@]}\"\n";
  Out << "echo -e \"  ${GREEN}Passed${NC} : ${#PASS[@]}  ${PASS[*]:-}\"\n";
  Out << "echo -e \"  ${RED}Failed${NC} : ${#FAIL[@]}  ${FAIL[*]:-}\"\n";
  Out << "\n[[ ${#FAIL[@]} -gt 0 ]] && exit 1 || exit 0\n";

  // Make the script executable.
  fs::permissions(ScriptPath,
                  fs::perms::owner_exec | fs::perms::group_exec |
                      fs::perms::others_read,
                  fs::perm_options::add, EC);
}
